### ISSUE TITLE
Send game options to specific clients

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#101]
# Api Suggestion

## Suggestion
Currently if we want to modify game settings you have to update everyone's settings. We should be able to give different options to different clients.

## Use case
Make it so one crewmate has a big vision value and another crewmate has a small vision value. 

## Expected result
Clients will have different game options.

**Comment by js6pak** [comment]
Same problem as [#158](https://github.com/Impostor/Impostor/issues/158#issuecomment-746572254).
