### ISSUE TITLE
Allow plugins to send game state changes

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#103]
# Api Suggestion

## Suggestion
Plugins should be able to send a packet changing all of the clients game states. 

## Use case
Having a custom victory / loss scenario. I currently achieve this but setting all clients to Impostor to end the round. 

## Expected result
Plugins able to set the game state and the clients act accordingly.

**Comment by AeonLucid** [comment]
This is kind of a global request. There are a lot of packets that modify game state.

**Comment by danbudworthmead** [comment]
> This is kind of a global request. There are a lot of packets that modify game state.

I meant more like having a Game.SetGamrState(GameStates.Fimished) function

**Comment by AeonLucid** [comment]
But how do you propose the finished screen to show? There's not really a packet for it so we need to use hacky methods.

**Comment by danbudworthmead** [comment]
> But how do you propose the finished screen to show? There's not really a packet for it so we need to use hacky methods.

Does MessageFlags.EndGame not put all the clients into an end of game state?

**Comment by AlexejheroYTB** [comment]
> Does MessageFlags.EndGame not put all the clients into an end of game state?

Nope, as I described in my comment on #108:
 
> This causes everyone but the host to stop receiving packets, and does not end the game as intended.

I do not think there is a way to achieve this without client-side mods, unless what you said actually works:

> I currently achieve this by setting all clients to Impostor to end the round.

**Comment by AlexejheroYTB** [comment]
Update: Sending an EndGame message could potentially work.
