### ISSUE TITLE
Build a 32-Bit Client

### ISSUE THREAD

**Issue by yaymuffins** [Impostor/Impostor#104]
# Feature Request

## Feature Information:
On other OSes than Windows, the game work on Wine, however the game is also 32 bit, meaning it is a better choice to use it inside a Wine 32bit prefix, however the client binaries doesn't seem available for Windows 32bit

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

I'm guessing it is just a question of changing the target in Visual Studio, it should be pretty easy to do :)

**Comment by AeonLucid** [comment]
> it should be pretty easy to do

Then you might as well do it yourself? 

We won't be providing 32 bit builds. I suggest you to use the CLI client on non-windows platforms.

**Comment by js6pak** [comment]
You don't have to run patcher (aka client) in the same wine perfix as the game, you can run it on host os pointing to `regionInfo.dat` that is inside wine prefix
