### ISSUE TITLE
Disconnect while reporting body, emergency call...

### ISSUE THREAD

**Issue by kptLucek** [Impostor/Impostor#105]
# Bug Report

## Base Information
- Operating System - win10
- Imposter Version - build 75
- Among Us Version - 9.22s

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 
This happened in 3 of 4 attempts for both of crewmate & impostor, and those 3 people got instantly DC.

### Case 1. Report dead body
- Ask an Impostor to kill someone
- Try to report the body

### Case 2. Push an emergency button
- Go and press emergency button

### Case 3. Kill someone
- As an impostor kill someone

## Logs
For both **1** and **2** cases:
```
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]: [00:01:06 ERR] Invoking data received failed
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]: System.NullReferenceException: Object reference not set to an instance of an object.
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]:    at Impostor.Server.Net.Inner.Objects.InnerPlayerControl.HandleRpc(ClientPlayer sender, ClientPlayer target, RpcCalls call, IMessageReader reader)
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]:    at Impostor.Server.Net.State.Game.HandleGameDataAsync(IMessageReader parent, ClientPlayer sender, Boolean toPlayer)
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]:    at Impostor.Server.Net.Client.HandleMessageAsync(IMessageReader reader, MessageType messageType)
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]:    at Impostor.Server.Net.Hazel.HazelConnection.ConnectionOnDataReceived(DataReceivedEventArgs e)
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]:    at Impostor.Hazel.Connection.InvokeDataReceived(IMessageReader msg, MessageType messageType)
Nov 01 00:01:06 SERVER_IP IMPOSTOR_DEV[32587]: [00:01:06 INF] QNURBK - Player XXX (126) has left.

```

for **3** case:
```
Oct 31 23:44:41 SERVER_IP  IMPOSTOR_DEV[32587]: [23:44:41 INF] Client 65 disconnecting, reason: Client sent SetPet to an unowned InnerPlayerControl

```

**Comment by Xiloe** [comment]
Same issue with latest dev branch running on Debian 10

**Comment by AeonLucid** [comment]
To reproduce properly:
- Start Impostor
- Create and play a game with 4 clients
- Keep the clients open and play another game (doesn't matter if server restarts)
- Kill someone and report their body
