### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by geniuskouta** [Impostor/Impostor#106]
# Feature Request

I would like to help implement Japanese language for Among Us.

## Feature Information:

 Just like Korean and Spanish languages are added, I think Japanese language should be added to the game. I can help with the translation and implementation.
 
## I confirm:
- [ x ] that I have searched for an existing feature request matching the description.

**Comment by tuxinal** [comment]
this is not the place to ask this, if you want to do that you have to contact innersloth themselves, this project is not related to innersloth

**Comment by AeonLucid** [comment]
What @tuxinal said.
