### ISSUE TITLE
SetInfectedAsync method does not produce the proper packet

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#115]
![unknown](https://user-images.githubusercontent.com/32238504/98292211-0813f780-1fb5-11eb-9e63-86fc9afccf47.png)
![unknown](https://user-images.githubusercontent.com/32238504/98292228-0cd8ab80-1fb5-11eb-9b34-337bf8ebeced.png)

**Comment by AeonLucid** [comment]
@danbudworthmead This is your code.
