### ISSUE TITLE
Add spawn positions for players depending on which map to API event

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#116]
The Skeld
(-2.1, 2.75), (-1.8, 2.9), (-1.47, 3), (-1.15, 3.12), (-0.82, 3.25), (0.94, 3.25), (1.25, 3.12), (1.57, 3), (1.9, 2.9), (2.2, 2.75)
MIRA HQ
(-2.1, 2.75), (-1.8, 2.9), (-1.47, 3), (-1.15, 3.12), (-0.82, 3.25), (0.94, 3.25), (1.25, 3.12), (1.57, 3), (1.9, 2.9), (2.2, 2.75)
Polus
(-2.1, 2.75), (-1.8, 2.9), (-1.47, 3), (-1.15, 3.12), (-0.82, 3.25), (0.94, 3.25), (1.25, 3.12), (1.57, 3), (1.9, 2.9), (2.2, 2.75)

**Comment by AeonLucid** [comment]
Undefined behavior for > 10 users?

**Comment by js6pak** [comment]
Among us client uses `PlayerId % SpawnPositions.Length`

**Comment by Mm2PL** [comment]
These are hard-coded, correct?

**Comment by danbudworthmead** [comment]
I guess so? This is from 6pak's dump.

**Comment by codyphobe** [comment]
Those are the lobby spawn positions, which explains why they are the same across each map.

The map spawn positions are based on two fields, `SpawnCenter` & `SpawnRadius`, and are generated using the method `ShipStatus#GetSpawnLocation(int playerId, int numPlayer)` where `numPlayer` is the length of the `Palette.PlayerColors` array

```C#
public Vector2 GetSpawnLocation(int playerId, int numPlayer)
{
	Vector2 up = Vector2.up; // new Vector2(0f, 1f)
	up = up.Rotate((float) (playerId - 1) * (360f / (float) numPlayer)); // 30 points of rotation derived from the 12 possible colors
	up *= SpawnRadius;
	return (Vector2) SpawnCenter.position + up + new Vector2(0f, 0.36363f);
}
```

**Comment by AlexejheroYTB** [comment]
What event could this be added to? Would we have to create a new event? If so, where could we call it from? Also, don't forget about pre-moving.

**Comment by danbudworthmead** [comment]
> Those are the lobby spawn positions, which explains why they are the same across each map.
> 
> The map spawn positions are based on two `ShipStatus` fields, `SpawnCenter` & `SpawnRadius`, and are generated using the method `ShipStatus#GetSpawnLocation(int playerId, int numPlayer)` where `numPlayer` is `GameData.Instance.PlayerCount`.
> 
> ```cs
> public Vector2 GetSpawnLocation(int playerId, int numPlayer)
> {
> 	Vector2 up = Vector2.up; // new Vector2(0f, 1f)
> 	up = up.Rotate((float) (playerId - 1) * (360f / (float) numPlayer));
> 	up *= SpawnRadius;
> 	return (Vector2) SpawnCenter.position + up + new Vector2(0f, 0.3636f);
> }
> ```

So we just need a way to do Game.GetSpawnPosition(clientID, mapID) then right?
We'd need to hardcode the SpawnCenter.position for each map I guess.

Do you have access to the spawn center positions? If you post them I can add it to our skeld.net server.

**Comment by cybershard** [comment]
I dumped the spawn positions of Skeld, Mira and Polus.

Skeld
Initial Spawn Center x: -0.72, y: 0.62

Mira
Initial Spawn Center x: -4.4, y: 2.2

Polus
Initial Spawn Center x: 16.64, y: -2.46
