### ISSUE TITLE
 Unable to start a game

### ISSUE THREAD

**Issue by Hooooki** [Impostor/Impostor#121]
I'm sorry to open an issue for that but I can't launch an hosted game. "Among Us" warns me that my game version is too old.

If anyone has already fixed this problem I would be happy to have the solution.

Thanks for your work !

**Comment by Gideon357** [comment]
@Hooooki this is not an Impostor issue. You just need to upgrade your game.

**Comment by Hooooki** [comment]
@Gideon357 Thanks for you response.

I'm already in the latest version (2020.10.22s)  and when I create a hosted game from a official server 
it works.

**Comment by Hooooki** [comment]
@Gideon357 
"You are running an older version of the game. Please update to play with others".

I tried to uninstall my game, but when I do the error remains the same.

**Comment by Gideon357** [comment]
@Hooooki did you delete your game data as well?

**Comment by Hooooki** [comment]
@Gideon357 Yes, I will try to remove steam and try again.

**Comment by Gideon357** [comment]
@Hooooki you need to get the experimental release of the server, see the readme.

**Comment by Hooooki** [comment]
@Gideon357 
I'm going to try, thank you for your answers
