### ISSUE TITLE
Enable Venting / Sabotaging / Killing

### ISSUE THREAD

**Issue by Rubyboat1207** [Impostor/Impostor#122]
# Api Suggestion
Let the player kill /vent / sabotage whether they are an impostor or not
## Suggestion
I want a bit of code that works something like this potentially
`
for each player in playerlist, e
e.EnableVent = true
e.EnableSabotage = true
e.EnableKill = true
`
Also make it so disabling these for impostors is a thing, it shouldn't matter what side you are on.
## Use case
Lets say I want to make a gamemode where everybody can vent then I would simply have something that gets every player then enables venting for each of them
## Expected result
(e is the selected player, we presume I have already selected the desired player)
e.EnableVent = false
then an impostor can no longer vent
e.EnableKill
crewmates now can vent

**Comment by Bevan0** [comment]
While I'm no expert on Among Us, I am unsure if this can be done without modding the client, or setting players to Impostors/Crewmates while they are in proximity to vents/other players.

**Comment by benjaminpants** [comment]
As far as I know this is impossible without clientside mods.

**Comment by Mm2PL** [comment]
Pretty sure that there is some in between state where you can kill but not vent or sabotage.

**Comment by AlexejheroYTB** [comment]
Disabling venting / killing / sabotaging as impostor could in theory be possible, but disabling killing would be hard.

Also, from what I've seen, there is no in-between state.

**Comment by AeonLucid** [comment]
Sorry this requires client modifications.
