### ISSUE TITLE
IPlayerReportedBodyEvent and IPlayerMurderedEvent doesn't work

### ISSUE THREAD

**Issue by TheFanTasMo97** [Impostor/Impostor#125]
It seems be that those events doesn't work, even with a simple logger to test it.

My code:
```CSharp
public void onPlayerKilled(IPlayerMurderedEvent)
{
    _logger.LogInformation("test kill");
}

public void OnBodyReported(IPlayerReportedBodyEvent e)
{
    _logger.LogInformation("test body");
}
```

**Comment by reecebenson** [comment]
Are you sure this is the code? As your example has a syntax error... and do these function declarations also have `[EventListener]` above them? You can refer to the [plugin documentation here](https://github.com/Impostor/Impostor/blob/dev/docs/Writing-a-plugin.md) for an example.

**Comment by TheFanTasMo97** [comment]
Okey totaly my bad, i forgot to put `[EventListener]` before
I'm really sorry to open a new issue for a simple error..

**Comment by AeonLucid** [comment]
No problem, glad you figured it out.
