### ISSUE TITLE
[API] upgrade MeetingStartEvent / PlayerReportedBody event does not fire when the body reporter is the host

### ISSUE THREAD

**Issue by Mr-VIT** [Impostor/Impostor#127]
# Bug Report

## Base Information
- Imposter Version 1.2.2-ci.97
- Among Us Version 2020.10.22s

## Symptoms 
- PlayerReportedBody event does not fire when the body reporter is the host
- PlayerReportedBody event fires on non-host Emergency call

## Update
- [x] upgrade MeetingStartEvent
  - [x] add reason: PressedButton/ReportedBody
  - [x] add sender: player who Pressed/Reported
  - [x] add Body: if reason is ReportedBody

**Comment by reecebenson** [comment]
Please provide a snippet of your code.

**Comment by Mr-VIT** [comment]
everything is as usual
```cs
[EventListener]
public async void OnPlayerReportedBody(IPlayerReportedBodyEvent e)
{
    _logger.LogInformation("body reported"); // does not fire when the body reporter is the host
}
```

**Comment by AeonLucid** [comment]
Sadly this is intended behavior from Among Us. Below snippet is from the older mono version of Among Us.

```csharp
public void CmdReportDeadBody(GameData.PlayerInfo target)
{
  if (AmongUsClient.Instance.AmHost)
  {
    this.ReportDeadBody(target);
  }
  else
  {
    MessageWriter messageWriter = AmongUsClient.Instance.StartRpc(NetId, 11); // ReportDeadBody
    messageWriter.Write(target != null ? target.PlayerId : byte.MaxValue);
    messageWriter.EndMessage();
  }
}
```

The "ReportDeadBody" is sent by players to the host, and then the host broadcasts "StartMeeting" rpc to all players with the body as parameter. In the case of the host being the reporter, the "StartMeeting" rpc is sent directly.

**Comment by AeonLucid** [comment]
I propose we fully remove the `PlayerReportedBodyEvent` and replace it with an improved `MeetingStartEvent` that has the body reported as property.
