### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by Rylienewson** [Impostor/Impostor#136]
# Bug Report

## Base Information
- Operating System
- Imposter Version
- Among Us Version

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Enter Symptoms on this line.

## Reproduction

Enter reproductions steps here.

**Comment by reecebenson** [comment]
Are... you the.. issue? 👀

**Comment by AlexejheroYTB** [comment]
It seems like you didn't fill out any of the issue details.

**Comment by marie6324** [comment]
Closed due to this being a useless troll post.
