### ISSUE TITLE
[Question] Does remote server have to be HTTPS?

### ISSUE THREAD

**Issue by user670** [Impostor/Impostor#138]
I put Impostor on a remote server I had, and configured my game to connect to said server. However, server executable didn't show anything when I tried to connect, and game says "You disconnected from the server. Reliable packet 1 (size=16) was not ack'd after 7500ms (9 resends)". I tried a few things that I can think of:

- Maybe I had the config wrong. I checked the docs, and realized I needed "public ip" to be my server's IP, so I changed that. Still didn't work.
- Maybe my server isn't configured to allow access from port 22023. I know for a fact that it does allow port 8888, so I changed the port to 8888. Still didn't work. (Yes I did turn off that application that was previously using port 8888 before starting Impostor on port 8888.)

The last thing I could think of is, the app (like every single other mobile app) might be using HTTPS to connect, and my server doesn't have HTTPS (only HTTP). I can't test that because I don't know how to set up HTTPS on my server, and it probably costs money as well.

Can someone confirm or deny that it is the HTTPS causing the problem? If not I'll try look into other reasons. Also I'd appreciate it if someone can suggest other possible reasons why it won't work.

Impostor version 1.2.2 on Windows x64, Windows server 2012.
Among Us game version 2020.10.22a on Android 9. Server config changed using [NaokiStark/Crewmate-switcher](https://github.com/NaokiStark/Crewmate-switcher).

**Comment by reecebenson** [comment]
The server doesn't use the HTTPS protocol, it uses UDP.

**Comment by reecebenson** [comment]
The server doesn't use the HTTPS protocol, it uses UDP. You may need to add an Inbound / Outbound Windows Firewall rule.

**Comment by user670** [comment]
> The server doesn't use the HTTPS protocol, it uses UDP. You may need to add an Inbound / Outbound Windows Firewall rule.

Well, thanks, but that didn't help for some reason. I added the firewall rules but still get the same disconnect error.

**Comment by AeonLucid** [comment]
Sounds like you configured your firewall for TCP and not UDP, please change it to use UDP.

**Comment by user670** [comment]
> Sounds like you configured your firewall for TCP and not UDP, please change it to use UDP.

I did choose UDP :-/
