### ISSUE TITLE
[QUESTION] Is there a way to change the max player amount?

### ISSUE THREAD

**Issue by Krxwallo** [Impostor/Impostor#139]
# Api Suggestion
[QUESTION] Is there a way to change the max player amount?

## Use case

E.g. for writing a plugin for something like 100 player lobbies

## Expected result

A way to change the max player amount by writing a server plugin. (Maybe you would have to mod the client side too).

**Comment by AlexejheroYTB** [comment]
(This is not an API suggestion)

Currently, Impostor can modify the number of maximum players by modifying `<IGame>.Options.MaxPlayers` and using a method which I think is called `<IGame>.SyncSettingsAsync` (but I might be wrong).
However, that won't work without client-side mods.

**Comment by AeonLucid** [comment]
https://github.com/Impostor/Impostor/blob/57cce72df592084fb2829afd00e826b1f183c6b5/src/Impostor.Plugins.Example/Handlers/PlayerEventListener.cs#L57-L64

**Comment by Saghetti0** [comment]
Attempting to join a 11th player just by modifying Impostor will cause the client to freeze. You're out of luck without client side mods.

**Comment by Krxwallo** [comment]
Ok thx for your replies! 👍

**Comment by irux** [comment]
Does anybody got it to work with more players ?  @Krxwallo  @Saghetti0

**Comment by XtraCube** [comment]
> 
> 
> Does anybody got it to work with more players ? @Krxwallo @Saghetti0

There are some mods in development, but nothing public for 11.17 yet.
