### ISSUE TITLE
GameData packets sometimes dont get handled

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#141]
# Bug Report

## Base Information
- Operating System: Windows 10
- Impostor Version: Latest dev
- Among Us Version: 2020.10.22s

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Sometimes, GameData packets are forwarded without being handled. Clients correctly receive the packet, but the server doesn't log `Server got 6.`, and any event listeners listening for these packets will not be triggered.

## Reproduction

I couldn't find a way to reliably reproduce this issue. From my testing, I've concluded that this is not plugin-related.

**Comment by xtcp** [comment]
#258 maybe it's the same issue that I'm having?

**Comment by js6pak** [comment]
Seems like this issue got solved silently?
