### ISSUE TITLE
[API] Ability to set map to dleks eht 

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#147]
Step 1. Check if this is possible to do using only server-side plugins.
Step 2. Try to implement it
Step 3. ???
Step 4. Don't profit because there likely isn't a way to tell the host to flip the map, since the host is the one sending the packet.

**Comment by AlexejheroYTB** [comment]
Halloween map customizations are handled strictly client-side.

I also can't find which packet tells clients if Skeld should be flipped or not.

**Comment by AeonLucid** [comment]
Pretty sure you need to change the id of the spawned shipcontrol object to another spawnable object. But host might not like this, can try to despawn the one it tries to spawn and spawn a new one for it.

**Comment by AlexejheroYTB** [comment]
Update: this is definitely possible. 

Here's how I would do it: If host sends skeld map and plugin called set dleks, send dleks to other clients instead of skeld, then send despawn packet for host's skeld, and send spawn packet for dleks.
