### ISSUE TITLE
Minimum And Maxium Players Allowed.

### ISSUE THREAD

**Issue by RealEnzoTDZ** [Impostor/Impostor#152]
I was just wondering how i would change the minimum and maximum players allowed in a server. As the dev build does NOT have game.cs in the net folder of Impostor.Server

**Comment by AlexejheroYTB** [comment]
You cannot change the minimum amount of players, but you can change the maximum. In an event listener, assuming that the event parameter is called e, you can do e.Game.Options.MaxPlayers = x; and e.Game.SyncSettingsAsync();

**Comment by RealEnzoTDZ** [comment]
Okay thank you for this info! I would like it to be able to change minimun players but i am happy that maximum players is changeable thank you
