### ISSUE TITLE
Certain game options reset when calling IGame.SyncSettingsAsync

### ISSUE THREAD

**Issue by oliver4888** [Impostor/Impostor#154]
# Bug Report

## Base Information
- Operating System
  - Windows 10 1909
- Impostor Version
  - 1.2.2-ci.111
- Among Us Version
  - 2020.10.22 and 2020.11.4

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Using the latest Among Us (2020.10.22) or public beta (2020.11.4) versions any setting that is after version 2 of the Game Options Data [(ref this wiki)](https://wiki.weewoo.net/wiki/Game_Options_Data) will get reset if a plugin calls `IGame.SyncSettingsAsync`.

The following table describes each setting and the value it get resets to.
| Setting | Value | Since Version |
| --- | --- | --- |
| Confirm Ejects | On | 3 |
| Visual Tasks | On | 3 |
| Anonymous Votes | Off | 4 |
| Task Bar Updates | Always | 4 |

## Reproduction

Create a plugin using [the guide](https://github.com/Impostor/Impostor/blob/dev/docs/Writing-a-plugin.md).
In the `OnGameCreated` event handler, call `e.Game.SyncSettingsAsync();` eg:
```csharp
        [EventListener]
        public void OnGameCreated(IGameCreatedEvent e)
        {
            Task.Run(async () =>
            {
                // The delay is to make the change easier to notice
                await Task.Delay(3000);
                await e.Game.SyncSettingsAsync();
            });
        }
```
Host a game and watch the Confirm Ejects setting (you may need to set this to false if you normally play with it turned on).

## Other information

I logged the `GameOptionsData.Version` value to see what version my client was reporting using the following event handler:
```csharp
        [EventListener]
        public void OnGameCreated(IGameCreatedEvent e)
        {
            _logger.LogInformation($"Ver {e.Game.Options.Version}");
        }
```
This logs `Ver 2` for both Among Us versions I listed earlier, and the settings that are being reset are all version 3 or 4 according to [this wiki](https://wiki.weewoo.net/wiki/Game_Options_Data).

I tried reinstalling my game including deleting the `AppData\LocalLow\Innersloth` folder to ensure that I was on the latest version and had a friend connect on v2020.10.22 to ensure that it wasn't just my game.

I checked and the settings are being correctly synced to all players when the lobby is created (and when players join), but they are reset to the values in the table under Symptoms when `IGame.SyncSettingsAsync` is called.

**Comment by AeonLucid** [comment]
I have a feeling it has something to do with this.
https://github.com/Impostor/Impostor/blob/7ec5bc1fdc263515dda23c26b0ce3de3792cb469/src/Impostor.Api/Innersloth/GameOptionsData.cs#L12

**Comment by oliver4888** [comment]
That appears to be the case. I changed the `GameOptionsData.LatestVersion` to `4` and now the Confirm Ejects and Visual Tasks settings don't get reset. However the Anonymous Votes and Task Bar Updates still do, I believe this is because the `GameOptionsData.Serialize` method uses two different variables to check whether something should be serialized or not, as seen by the `version` and `Version` in the following file: https://github.com/Impostor/Impostor/blob/7ec5bc1fdc263515dda23c26b0ce3de3792cb469/src/Impostor.Api/Innersloth/GameOptionsData.cs#L184-L204
This method is always called with the `GameOptionsData.LatestVersion` as the second parameter.

**Comment by AeonLucid** [comment]
Right, upper and lowercase version. That's definitely a bug, does it get fixed if you change that?

**Comment by oliver4888** [comment]
Still able to reproduce the issue, but I think it might be a different bug now.
Placing a breakpoint in the `GameOptionsData.Deserialize` method I looked at the `Version` that got read from the bytes, when the client creates a lobby this is set to `2` and when we get down to read the newer settings, shown below, the byte span is empty. As if the client isn't sending these when it joins?
https://github.com/Impostor/Impostor/blob/ad0408d0dea9a826b13d5db016ab4746fa719625/src/Impostor.Api/Innersloth/GameOptionsData.cs#L243-L253
However when I change settings in game, the `Version` is set to `4` and the newer settings are set correctly.
