### ISSUE TITLE
IGameDestroyedEvent doesn't get fired when the server closes. Redis keys also don't get deleted.

### ISSUE THREAD

**Issue by Saghetti0** [Impostor/Impostor#155]
# Bug Report

## Base Information
- Operating System: Windows 10
- Impostor Version: Latest build
- Among Us Version 2020.10.22s

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 

When the server closes using Ctrl+C and the rooms close, IGameDestroyedEvent never gets fired. Keys created by NodeLocatorRedis also don't get deleted.

## Reproduction

Write a small plugin to print a message on IGameDestroyedEvent. Create a game and close it normally, the text will be printed. Now create a game and close Impostor using Ctrl+C. The event never gets fired, and the text doesn't get printed.

Using a Redis database viewer (RedisInsight) also shows that keys created by NodeLocatorRedis also don't get deleted. Create a game and close Impostor using Ctrl+C. The key called ImpostorRedisXXXXXX (where X is the game code) never gets deleted until it expires.

**Comment by AeonLucid** [comment]
> Keys created by NodeLocatorRedis also don't get deleted.

This is why the keys have an expiration. Also useful in the case that the application crashed and wouldn't be able to clean itself up.

I will look into calling OnDisable on shutdown.

**Comment by danbudworthmead** [comment]
> The event never gets fired, and the text doesn't get printed.

This could also be related to the client leak in client manager? 
If the host is not getting destroyed sometimes, then IGameDestroyedEvent won't get called and the ClientManager continues to leak clients.
