### ISSUE TITLE
Possibility of ARMv6 support with Mono.

### ISSUE THREAD

**Issue by TheProgramableTurtle** [Impostor/Impostor#156]
# Feature Request
Could Impostor be built for ARMv6 using Mono or is there a specific requirement for .NET 5.0? And if doing so would require porting some of the codebase, how much work would this take?
## Feature Information:

This would mean that Impostor could be run on Raspberry Pi Zero and 1 devices. This would be of great convenience because the Zero is the cheapest model.
## I confirm:
- [X] that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
.NET 5 can not build for ARMv6. I'm not sure how you would do it with mono and if it's even possible, but it's not something I'd like to support officially.

**Comment by TheProgramableTurtle** [comment]
So you wouldn’t have any idea of what would be necessary to port to Mono?

**Comment by AeonLucid** [comment]
No, sorry.
