### ISSUE TITLE
Simply can't get it to work

### ISSUE THREAD

**Issue by willmendil** [Impostor/Impostor#157]
Hi, I know this must be an annoying message, but I cannot get this to work. I've followed your difference doc, I found my public ip address, modified the config.json file, forward ports on my router, but in the game, although I can see the imposter in the lower right, I cannot get to connect to it. 
I'm running the windows version on the 1.2.2.

**Comment by willmendil** [comment]
It works if I use 127.0.0.1 on the client side. 
here's my config file

```
{
  "Server": {
    "PublicIp": "93.19.XXX.XXX",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "BanIpFromGame": true
  }
}
```

**Comment by CodeEasyYT** [comment]
İ'm having the same issue. But I didn't know about config.json file. Can anybody help?

**Comment by willmendil** [comment]
UDP, it's a UDP forward not TCP.
