### ISSUE TITLE
Add GameDataTo overloads for all api methods

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#158]
# Api Suggestion

## Suggestion
Add an overload to all api methods to use GameDataTo instead of GameData and target a specific player.

## Use case
Change color/name only for one player, sabotage comms only for impostors, etc.

**Comment by AeonLucid** [comment]
How will this work internally? i.e. we keep track of state changes for the broadcasted packets, what happens when sending to a specific player?

**Comment by AlexejheroYTB** [comment]
We could update all API methods that use data from their class properties / server tracked data (such as SyncSettings/SyncOptions whatever its called) to use data from parameters, like most other api functions do (such as SetName), and we could let the plugin specify if the server should track that data or not.

**Comment by AeonLucid** [comment]
That's going to be one messy API. I guess we can just append `To` to all methods that end up being a RPC, for example `SetHatAsync` and `SetHatToAsync`, `SetSkinAsync` and `SetSkinToAsync`.

**Comment by AlexejheroYTB** [comment]
SetHatToAsync doesn't make sense as a method name. Keep in mind that the API methods should be easy to understand by people who've never seen them before.

**Comment by js6pak** [comment]
This is something that shouldn't be directly in api imo, if skin of the player is set, it should be set - game state should be updated and all players should receive the update, just exposing packet api is better way to do this.

**Comment by AlexejheroYTB** [comment]
That could work as well and would require much less maintenance.

**Comment by gavinsteinhoff** [comment]
I think this topic should be revisited. It would open plugins up way more past just vanilla. 

The method could be `SetHatFromPov(HatType, IClientPlayer)`

This way we could set a hat, but only from the view of the client player you pass in, defaulting to selected player.
