### ISSUE TITLE
[API Bug] Task indices being cast to TaskTypes

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#159]
This issue was reported by `Cybershard#3935` on Discord.

---

> https://github.com/Impostor/Impostor/blob/d590da0d27388e5b95db9c7bc7ba3558b1a57135/src/Impostor.Server/Net/Inner/Objects/InnerPlayerInfo.cs#L69-L76 Unless I'm missing something, this code gets called when RPC updategamedata or the gamedata object's deserialize method gets called, but in any case, **the reader contains the index of the task for that InnerPlayerInfo, and if its completed or not. Right now, its being treated as a TaskType**

> Same goes for this code: https://github.com/Impostor/Impostor/blob/d590da0d27388e5b95db9c7bc7ba3558b1a57135/src/Impostor.Server/Net/Inner/Objects/InnerPlayerControl.cs#L83-L85

> The id from the RPC CompleteTask is the index of what task the player completed in regards to their InnerPlayerInfo. But, the code at https://github.com/Impostor/Impostor/blob/d590da0d27388e5b95db9c7bc7ba3558b1a57135/src/Impostor.Server/Events/Game/Player/PlayerCompletedTaskEvent.cs#L11-L17 is casting it as a TaskType.

**Comment by cybershard** [comment]
In the game, RPC SetTasks gets called with the tasks array , and then RPC UpdateGameData with the index of the task/if its complete or not. I would keep the `InnerPlayerInfo#Tasks` as a `List<TaskType>`, and on the `InnerPlayerInfo#Deserialize` call, mutate the current `List<TaskType> Tasks` by index (and create a new `TaskInfo` if it is currently null).
