### ISSUE TITLE
Accessing Game.Host.Character.PlayerInfo.PlayerName throws exception

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#160]
Reported by `Saghetti#7380` on Discord.

---

> error while doing Game.Host.Character.PlayerInfo.PlayerName
>
> ![](https://media.discordapp.net/attachments/760921187781312533/777780076602851348/unknown.png?width=583&height=223)

**Comment by AeonLucid** [comment]
This is intended behavior because the host is set when the first player joins the created game.

**Comment by AlexejheroYTB** [comment]
Perhaps the exception message could be adjusted then?

**Comment by KernelErr0r** [comment]
I think the best exception in this case is InvalidOperationException, it's quite informative as-is and would be even more informative with a message describing why it's invalid in this particular case.

**Comment by MrKrakenied** [comment]
> This is intended behavior because the host is set when the first player joins the created game. This was called from "OnGameCreated", where nobody has joined the game yet. It is not possible to assign the host here because the one that created the game reconnects with the server to join it.

e.Game isn't set too
