### ISSUE TITLE
[API] Create game from API without host

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#162]
# Api Suggestion

## Suggestion
The ability to create a game from the API, without having any players in it and without having a host.

## Use case
Perhaps lobby browser for custom gamemodes

**Comment by AeonLucid** [comment]
Not possible without filling in a player spot and it being a "real" player in-game.

**Comment by AlexejheroYTB** [comment]
It could be a real player in-game until the first player connected, when they would receive the host. Get game listings could check if the player is fake, and if it is, show 0 connected players instead of 1.

**Comment by AeonLucid** [comment]
Ohhh, you meant like pre-creating games. Yeah that can be done, but I think this can already be done at the moment with a plugin when `GameManager.CreateAsync` is exposed to the API. Just create it and set it to public, the first player that joins becomes host.

Haven't tried it myself but it makes sense.

**Comment by xtcp** [comment]
I've tested #241 and it works, however if a player connects and disconnects the game is closed, I've tried forcing the game to stay open, but everything because when connecting again, probably because of the host assignment. How would we go about keeping the room alive without a host?
