### ISSUE TITLE
You are running an older version of the game

### ISSUE THREAD

**Issue by amitco2468** [Impostor/Impostor#165]
# Bug Report

## Base Information
- Operating System: Windows
- Impostor Version: 1.1.0
- Among Us Version: 10.22s

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Problem
Among us types "You are running an older version of the game" only when im using the impostor servers

**Comment by Mr-VIT** [comment]
check the table of supported versions https://github.com/Impostor/Impostor/blob/dev/README.md

**Comment by AlexejheroYTB** [comment]
You need to update impostor to v1.2.2 to work with 10.22s

**Comment by AeonLucid** [comment]
Read the read me.
