### ISSUE TITLE
Is there a way to change player location with the current API?

### ISSUE THREAD

**Issue by NickNish09** [Impostor/Impostor#166]
I was aiming something like changing 
**player.Character.PlayerInfo.x = 20.31233
player.Character.PlayerInfo.y = 25.14323**
and the player will be teletransported (or spawned) in that location in the map.
I'm still studying this API so I don't really know where to modify things.
Any way thanks for the attention! Great Api!

**Comment by AlexejheroYTB** [comment]
I do not think this can be done without client-side modifications.

**Comment by cybershard** [comment]
@NickNish09, this already exists as IInnerCustomNetworkTransform#SnapToAsync 
https://github.com/Impostor/Impostor/blob/d590da0d27388e5b95db9c7bc7ba3558b1a57135/src/Impostor.Api/Net/Inner/Objects/Components/IInnerCustomNetworkTransform.cs#L6-L14

**Comment by NickNish09** [comment]
> @NickNish09, this already exists as IInnerCustomNetworkTransform#SnapToAsync
> https://github.com/Impostor/Impostor/blob/d590da0d27388e5b95db9c7bc7ba3558b1a57135/src/Impostor.Api/Net/Inner/Objects/Components/IInnerCustomNetworkTransform.cs#L6-L14

Great, I was able to do what I wanted. Thanks!
