### ISSUE TITLE
Is there a way to get the player current position on the map?

### ISSUE THREAD

**Issue by NickNish09** [Impostor/Impostor#167]
I was trying to do a plugin that changes a player position with other player
I was able to change the player position with player.Character.NetworkTransform.SnapToAsync(newPosition), but I wanted to know if it is possible to know all the players position at a given time, something like this:

public void OnGameStarted(IGameStartedEvent e)
{
  _logger.LogInformation($"Game is starting.");

  foreach (var player in e.Game.Players)
    {
       _logger.LogInformation($"{player.Character.NetworkTransform.CurrentPlayerPosition}") // here we know the player position
     }
}

Also, I did not see how people get the Map coordinates limits (like, in Skeld which coordinates the Admin/Cafeteria is, something like that). Does anyone know that?

Also, is there a way to allow the chat use during the game phase (not only in the discussion phase)? So the users can type a message like:
/teleport (2.5, -1.53)
and be teleported to that location (using the message listener).

Anyway, thanks for the attention. Great Api!

**Comment by NickNish09** [comment]
Ok, after some reverse engineering I was able to get some coordinates on Skeld map, for those who are interested:
(Place)   - (X, Y)
Cafeteria: -1 -1
MedBay: -8.8 -3
Security: -13.5 -4.5
Reactor: -20.5 -6
Upper Engine: -17.5 2.5
Storage: -1 -10 // -2 -15.5
Weapons: 9.4 2.8
Shields: 9.4 -12
Communications: 4 -15.5
Electrical: -7.5 -8.5
Lower Engine: -15 -12
O2: 6.5 -3.5
Navigation: 16.5 -5

Those are aproximate

**Comment by cybershard** [comment]
Nice work. How did you get these values?

**Comment by NickNish09** [comment]
So, I don't know if this is the best way kk, but what I did was:

I putted this in the OnPlayerChat event listener:
`

        [EventListener]
        public void OnPlayerChat(IPlayerChatEvent e)
        {
            string[] command = e.Message.Split(' ');
            if(command[0] == "/t"){
                Vector2 newPos;
                newPos.X = (float)Convert.ToDouble(command[1]);
                newPos.Y = (float)Convert.ToDouble(command[2]);
                e.PlayerControl.NetworkTransform.SnapToAsync(newPos);
            }
        }
`

Then, I entered a custom game with 4 players, killed one (so one becomes a ghost), and as the ghost can talk, I started to manually input chat messages with the ghost:
/t -1 -1 (then the ghost was teleported to cafeteria)

and did that to find out where the other places where. I'm gonna do that for the other maps later.

**Comment by NickNish09** [comment]
Just to update, for those who are interested, I got the other maps coordinates:

```
// MIRA CONSTANTS

        public static readonly float MIRA_LAUNCHPAD_X = -4.5F;
        public static readonly float MIRA_LAUNCHPAD_Y = 2.0F;
        public static readonly float MIRA_MEDBAY_X = 15.4F;
        public static readonly float MIRA_MEDBAY_Y = 0.0F;
        public static readonly float MIRA_COMMUNICATIONS_X = 14.4F;
        public static readonly float MIRA_COMMUNICATIONS_Y = 4.3F;
        public static readonly float MIRA_LOCKER_ROOM_X = 8.4F;
        public static readonly float MIRA_LOCKER_ROOM_Y = 1.4F;
        public static readonly float MIRA_OFFICE_X = 14.7F;
        public static readonly float MIRA_OFFICE_Y = 19.5F;
        public static readonly float MIRA_ADMIN_X = 20.0F;
        public static readonly float MIRA_ADMIN_Y = 20.4F;
        public static readonly float MIRA_BALCONY_X = 22.0F;
        public static readonly float MIRA_BALCONY_Y = -2.0F;
        public static readonly float MIRA_CAFETERIA_X = 25.3F;
        public static readonly float MIRA_CAFETERIA_Y = 4.3F;
        public static readonly float MIRA_DECONTAMINATION_X = 6.3F;
        public static readonly float MIRA_DECONTAMINATION_Y = 5.5F;
        public static readonly float MIRA_HALLWAY_X = 17.7F;
        public static readonly float MIRA_HALLWAY_Y = 11.0F;
        public static readonly float MIRA_LABORATORY_X = 9.0F;
        public static readonly float MIRA_LABORATORY_Y = 12.5F;
        public static readonly float MIRA_REACTOR_X = 2.4F;
        public static readonly float MIRA_REACTOR_Y = 11.2F;
        public static readonly float MIRA_STORAGE_X = 19.4F;
        public static readonly float MIRA_STORAGE_Y = 4.3F;
        public static readonly float MIRA_GREENHOUSE_X = 17.8F;
        public static readonly float MIRA_GREENHOUSE_Y = 23.0F;

        // POLUS constants
        public static readonly float POLUS_DROPSHIP_X = 16.7F;
        public static readonly float POLUS_DROPSHIP_Y = -3.5F;
        public static readonly float POLUS_ELECTRICAL_X = 7.5F;
        public static readonly float POLUS_ELECTRICAL_Y = -12.0F;
        public static readonly float POLUS_EXTERIOR_X = 28.3F;
        public static readonly float POLUS_EXTERIOR_Y = -12.5F;
        public static readonly float POLUS_OFFICE_X = 21.5F;
        public static readonly float POLUS_OFFICE_Y = -17.5F;
        public static readonly float POLUS_O2_X = 2.2F;
        public static readonly float POLUS_O2_Y = -17.3F;
        public static readonly float POLUS_ADMIN_X = 21.0F;
        public static readonly float POLUS_ADMIN_Y = -22.7F;
        public static readonly float POLUS_BOILER_ROOM_X = 2.3F;
        public static readonly float POLUS_BOILER_ROOM_Y = -24.0F;
        public static readonly float POLUS_COMMUNICATIONS_X = 11.1F;
        public static readonly float POLUS_COMMUNICATIONS_Y = -17.8F;
        public static readonly float POLUS_DECONTAMINATION_X = 39.2F;
        public static readonly float POLUS_DECONTAMINATION_Y = -16.8F;
        public static readonly float POLUS_LABORATORY_X = 33.2F;
        public static readonly float POLUS_LABORATORY_Y = -7.6F;
        public static readonly float POLUS_MEDBAY_X = 40.4F;
        public static readonly float POLUS_MEDBAY_Y = -7.7F;
        public static readonly float POLUS_SECURITY_X = 3.0F;
        public static readonly float POLUS_SECURITY_Y = -12.0F;
        public static readonly float POLUS_SPECIMEN_ROOM_X = 36.6F;
        public static readonly float POLUS_SPECIMEN_ROOM_Y = -21.8F;
        public static readonly float POLUS_STORAGE_X = 20.3F;
        public static readonly float POLUS_STORAGE_Y = -12.0F;
        public static readonly float POLUS_WEAPONS_X = 12.0F;
        public static readonly float POLUS_WEAPONS_Y = -23.2F;
```

**Comment by Tiebe** [comment]
@NickNish09 How did you convert x1 y1 to just one float number? Could you do that for the skeld as well?
