### ISSUE TITLE
This is not a feature i just need help

### ISSUE THREAD

**Issue by amitco2468** [Impostor/Impostor#168]
# Help Request

## Help Information:
How can I host Impostor server on heroku? i dont understand it

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by marie6324** [comment]
You use the discord for support, just like everyone else.

**Comment by amitco2468** [comment]
What?

**Comment by amitco2468** [comment]
What's Your discord link?

**Comment by KnucklesYT6** [comment]
https://discord.gg/FkJqx6QEyq
