### ISSUE TITLE
Read plugin info from Assembly Info instead of ImpostorPluginAttribute arguments

### ISSUE THREAD

**Issue by Mr-VIT** [Impostor/Impostor#172]
Replacement table:
|Current argument|Assembly attribute|.csproj property
|-:|-|-
|name|Title|AssemblyTitle
|author|Company|Authors
|version|InformationalVersion|Version

dev writes into `Impostor.Plugins.Example.csproj`:
```csproj
<Project Sdk="Microsoft.NET.Sdk">
...
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>

    <Version>1.2.3</Version>
    <AssemblyTitle>Example</AssemblyTitle>
    <Authors>AeonLucid</Authors>
  </PropertyGroup>
...
</Project>
```

**Comment by AlexejheroYTB** [comment]
What are the advantages to this? I personally only see the disadvantage that this file is hard to access since you can't double click it in most IDEs.

**Comment by Mr-VIT** [comment]
advantages:
+ no info duplication: 1 for dll info and 1 for server output

> that this file is hard to access

Editing csproj is just one of several ways change assembly information. You can edit or create custom `AssemblyInfo.cs` or use Assembly Information Editor in IDE, for ex. in VStudio: Right-Click on the Project name in the Solution Explorer --> then Click on Properties --> click on Application tab from left side --> then click on Assembly Information. Now you can find all the properties for your Assembly.

**Comment by AlexejheroYTB** [comment]
Yeah, `AssemblyInfo.cs` seems to be the best way to do this in my opinion.

**Comment by AlexejheroYTB** [comment]
@AeonLucid What are your thoughts about this?

**Comment by AeonLucid** [comment]
I don't like it. An disadvantage for it is that we can't support multiple plugins in one assembly if we ever want to do that.

@GerardSmit

**Comment by XtraCube** [comment]
Bump(Stale bot will not win)
