### ISSUE TITLE
Send Messages via Players in game

### ISSUE THREAD

**Issue by Keleonix** [Impostor/Impostor#177]
Hello, I am pretty new to all this.

I am trying to setup a Leaderboard/Scoring pluging, using an SQL database. It keeps track of your name, score, stats, etc...
I was wondering if there was a way to make a player write in tchat, via an event listener.

For example:
public void OnPlayerChat(IPlayerChatEvent e)
{
      [...]
      if (e.Message.Equals("/score"))
                {
                    string score = GetScore(playerName);
                    _logger.LogInformation($"{playerName} score is {score}");
                    TchatMessage(name, score);
                }
}

Where TchatMessage would send a string to the tchat, via the player {playerName}?

**Comment by gavinsteinhoff** [comment]
Are you talking about getting a response back in the Among Us chat? If so is this might be what you need:

```
e.ClientPlayer.Character.SendChatAsync("");
e.ClientPlayer.Character.SendChatToPlayerAsync("");
```

SendChatToPlayerAsync will only send a chat to the ClientPlayer I believe.

**Comment by danbudworthmead** [comment]
> Are you talking about getting a response back in the Among Us chat? If so is this might be what you need:
> 
> ```
> e.ClientPlayer.Character.SendChatAsync("");
> e.ClientPlayer.Character.SendChatToPlayerAsync("");
> ```
> 
> SendChatToPlayerAsync will only send a chat to the ClientPlayer I believe.

ValueTask SendChatToPlayerAsync(string text, IInnerPlayerControl? player = null);
It sends it from current playerControl player to a target playerControl, if player is null, it sends it to itself only.
