### ISSUE TITLE
[API Suggestion] 

### ISSUE THREAD

**Issue by wasmake** [Impostor/Impostor#178]
# Api Suggestion

## Suggestion

- [ ] Player actual location / Player move event.
- [ ] Meeting vote listener: Casts (who voted against who in real time), End of voting (Improved).

_Also a question regarding the Murder Event:
 Does (e.ClientPlayer, e.Victim) corresponds to (Killer, Victim) ?_

## Use case
1.- To do a proximity voice chat.
2.- To make some animations on voting progress and also make an animation of the exiled player.

**Comment by dimaguy** [comment]
Umm there are already ways to do proximity voice chat.(mumble plugin for example)
I dont see the point of this

**Comment by reecebenson** [comment]
> Does (e.ClientPlayer, e.Victim) corresponds to (Killer, Victim)

Yes

> Player actual location / Player move event.

This is in progress, I believe Aeon is still trying to figure out the best approach for this as many people are looking for this feature, but the workaround and available option at the moment is to take the clients target position (not their actual location).

> Meeting vote listener: Casts (who voted against who in real time), End of voting (Improved).

Does #181 add what you're looking for?

**Comment by AlexejheroYTB** [comment]
Recommend closing as duplicate of other issues/some features already pr'd/
