### ISSUE TITLE
Non-default server ports dont work

### ISSUE THREAD

**Issue by Azim** [Impostor/Impostor#179]
# Bug Report

## Base Information
- Server: Windows Server 2012
- Impostor Version: dev build https://github.com/Impostor/Impostor/commit/4ebba13076dc25ddf1f9820d6dcf30f3955dd4ea
- Among Us Version: v2020.10.22s

## I confirm:
- [*] that I have searched for an existing bug report for this issue.

## Symptoms 

When using non-default server port, the clients are unable to connect to existing lobbies, while are still able to create new lobbies.
![image](https://user-images.githubusercontent.com/16478424/99899938-d80b6a80-2cbd-11eb-862a-4ab8e9cc0165.png)

## Reproduction

1. Create a server with non-default port (i used 27777)
2. Create a lobby on said server
3. Noone is able to join that lobby, since they get this error:
![image](https://user-images.githubusercontent.com/16478424/99899938-d80b6a80-2cbd-11eb-862a-4ab8e9cc0165.png)

**Comment by dimaguy** [comment]
This error is not because of the port.
Did you set public ip to something other than 0.0.0.0 and 192.x.x.x. or 127.0.0.1?
Please refer to [this documentation](https://github.com/dimaguy/Impostor/blob/dev/docs/TROUBLESHOOTING.md) (keep in mind that this troubleshooting is yet to be accepted in a PR, hence it being in a forked repo)

**Comment by Azim** [comment]
> Did you set public ip to something other than 0.0.0.0 and 192.x.x.x. or 127.0.0.1?
yes
> Please refer to [this documentation](https://github.com/dimaguy/Impostor/blob/dev/docs/TROUBLESHOOTING.md) (keep in mind that this troubleshooting is yet to be accepted in a PR, hence it being in a forked repo)
i will take a look, but the issue disappeared when i switched server to use default port, so there's that

**Comment by dimaguy** [comment]
You could have missed something in the firewall or the nat forwardings

**Comment by Azim** [comment]
> You could have missed something in the firewall or the nat forwardings

i did not, i followed the guide carefully.

**Comment by dimaguy** [comment]
I can assure you that non default ports work. As long as the public port matches the port that machines connect to

**Comment by Azim** [comment]
> I can assure you that non default ports work. As long as the public port matches the port that machines connect to

then why do you think i made an effort to create an issue here?

**Comment by dimaguy** [comment]
No idea. Generally people go on discord for this kind of stuff

**Comment by dimaguy** [comment]
Also one thing. Did you use the website or the desktop patcher?

**Comment by Azim** [comment]
> Also one thing. Did you use the website or the desktop patcher to generate the regioninfo.dat?

`build\Impostor-Patcher_1.2.2-ci.117_win-x64.zip` from here:
https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts

**Comment by Chicken** [comment]
Server: ubuntu 20.04 LTS x86_64
Impostor Version: dev build 4ebba13
Among Us version: v2020.11.4s
Desktop patcher

Can reproduce this issue on my server by using another port instead of the default one.

**Comment by dimaguy** [comment]
Use this website: https://impostor.github.io/Impostor/

**Comment by dimaguy** [comment]
> Server: ubuntu 20.04 LTS x86_64
> Impostor Version: dev build [4ebba13](https://github.com/Impostor/Impostor/commit/4ebba13076dc25ddf1f9820d6dcf30f3955dd4ea)
> Among Us version: v2020.11.4s
> Desktop patcher
> 
> Can reproduce this issue on my server by using another port instead of the default one.

Did you follow the troubleshooting steps I linked above?

**Comment by Chicken** [comment]
Yes. I have the server working under the normal port. I'm using the public ip of my server and the port is open on ufw for tcp/udp.

**Comment by Azim** [comment]
> Use this website: https://impostor.github.io/Impostor/

just tested with it, and the issue persists

**Comment by dimaguy** [comment]
> Yes. I have the server working under the normal port. I'm using the public ip of my server and the port is open on ufw for tcp/udp.
> Edit: also I don't have port forwarding as the ipv4 is dedicated for the server.

Could you quickly test with ufw disabled

**Comment by dimaguy** [comment]
> > Use this website: https://impostor.github.io/Impostor/
> 
> just tested with it, and the issue persists

Well Ive just received prints of a friend that doesnt have github but was reading this issue and it was working correctly. Im on mobile rm but I can link the images later to prove it working

**Comment by Azim** [comment]
> > > Use this website: https://impostor.github.io/Impostor/
> > 
> > 
> > just tested with it, and the issue persists
> 
> Well Ive just received prints of a friend that doesnt have github but was reading this issue and it was working correctly. Im on mobile rm but I can link the images later to prove it working

sure go ahead

**Comment by Chicken** [comment]
Still having the issue even when ufw disabled

**Comment by dimaguy** [comment]
> Still having the issue even when ufw disabled

Could you share your config partially censoring the public ip

**Comment by dimaguy** [comment]
@Azim you too please ^

**Comment by Chicken** [comment]
```
{
  "Server": {
    "PublicIp": "5.189.***.***",
    "PublicPort": 22022,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22022
  },
  "AntiCheat": {
    "BanIpFromGame": true
  }
}
```

**Comment by Azim** [comment]
This works:
```
{
  "Server": {
    "PublicIp": "146.66.***.***",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "BanIpFromGame": true
  }
}
```

This doesnt:
```
{
  "Server": {
    "PublicIp": "146.66.***.***",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "BanIpFromGame": true
  }
}
```

**Comment by dimaguy** [comment]
> This works:
> 
> ```
> {
>   "Server": {
>     "PublicIp": "146.66.***.***",
>     "PublicPort": 22023,
>     "ListenIp": "0.0.0.0",
>     "ListenPort": 22023
>   },
>   "AntiCheat": {
>     "BanIpFromGame": true
>   }
> }
> ```
> 
> This doesnt:
> 
> ```
> {
>   "Server": {
>     "PublicIp": "146.66.***.***",
>     "PublicPort": 27777,
>     "ListenIp": "0.0.0.0",
>     "ListenPort": 27777
>   },
>   "AntiCheat": {
>     "BanIpFromGame": true
>   }
> }
> ```

Could you send me a pic with the rule youve done in the router

**Comment by Azim** [comment]
> Could you send me a pic with the rule youve done in the router

are you implying i dont know how to port forward?
The rules are identical, with only difference being that for one i created a fresh rule with **only** port 22023, and for other i have a **range** 25000-28000

**Comment by Chicken** [comment]
<img width="222" alt="ss" src="https://user-images.githubusercontent.com/45627874/99901938-19961880-2cb2-11eb-9ca0-5ef56b6c323f.png">
I don't have a router in between because it's a vps with dedicated ipv4 but heres my identical ufw rules anyway.

**Comment by dimaguy** [comment]
> > Could you send me a pic with the rule youve done in the router
> 
> are you implying i dont know how to port forward?
> The rules are identical, with only difference being that for one i created a fresh rule with **only** port 22023, and for other i have a **range** 25000-28000

No, I am not asking anything. Im asking for the pic

**Comment by dimaguy** [comment]
> <img alt="ss" width="222" src="https://user-images.githubusercontent.com/45627874/99901938-19961880-2cb2-11eb-9ca0-5ef56b6c323f.png">
> 
> I don't have a router in between because it's a vps with dedicated ipv4 but heres my identical ufw rules anyway.

I dont see the protocol in that pic

**Comment by Chicken** [comment]
Without protocol = tcp/udp

**Comment by realfaceitkantesilvestrs** [comment]
@Azim I think you need to check your attitude a bit

**Comment by dimaguy** [comment]
![imagem](https://user-images.githubusercontent.com/7207103/99906530-8e2b8000-2ccf-11eb-8090-7b7cb9d10a04.png)
owo whats this

**Comment by Chicken** [comment]
Maybe try running the test with someone and not just everything running on the same machine. *(also how does one even open 2 clients so I could test this)*

**Comment by Azim** [comment]
> owo whats this? Impostor in a non-standard port?
this doesnt anyhow help nor prove your point - both clients and server are running on the same machine

**Comment by dimaguy** [comment]
Well but that still doesnt change the fact THAT IS IS USING A NON DEFAULT PORT.

**Comment by Azim** [comment]
> As far as I know, that means that non-default server ports DO WORK

it really doesnt

**Comment by dimaguy** [comment]
> 
> 
> > As far as I know, that means that non-default server ports DO WORK
> 
> it really doesnt

How so?
I mean, the traffic leaves and enters in that port... therefore it means they are working

**Comment by Chicken** [comment]
If you believe so. Why would it not work for us? The first user is able to connect and create a lobby but second user isn't able to join it. That proves that the port is open and forwarded correctly but something is still wrong.

**Comment by Azim** [comment]
> How so?
> I mean, the traffic leaves and enters in that port... therefore it means they are working
> Even if it is localhost, the traffic still uses that port

becouse in both reports the server is running on the different machine while you run it locally, and after that you are claiming that it works on your side, even though you couldnt bother to reproduce it properly?

**Comment by dimaguy** [comment]
> 
> 
> If you believe so. Why would it not work for us? The first user is able to connect and create a lobby but second user isn't able to join it. That proves that the port is open and forwarded correctly but something is still wrong.

Lets see... hmmm that still means that the ports are working. If at least one can connect they are working

**Comment by dimaguy** [comment]
> 
> 
> > How so?
> > I mean, the traffic leaves and enters in that port... therefore it means they are working
> > Even if it is localhost, the traffic still uses that port
> 
> becouse in both reports the server is running on the different machine while you run it locally, and after that you are claiming that it works on your side, even though you couldnt bother to reproduce it properly?

Give me money and Ill reproduce it with 2 machines. better yet how about I open a server on a non standard port and make you connect to it

**Comment by Azim** [comment]
> better yet how about I open a server on a non standard port and make you connect to it

sounds good to me

**Comment by dimaguy** [comment]
208.110.239.187:25570
Ill delete this message in 10 minutes

**Comment by Azim** [comment]
> this machine is running impostor 1.1.0 so make sure you are not running beta
which is outdated and can not be connected to by the version in question

**Comment by dimaguy** [comment]
> 
> 
> > this machine is running impostor 1.1.0 so make sure you are not running beta
> 
> which is outdated and can not be connected to by the version in question
Hmm well then all I can say is that Impostor has no way of distinguishing lan and wan. So port behaviour should be the same

**Comment by Azim** [comment]
> Hmm well then all I can say is that Impostor has no way of distinguishing lan and wan. So port behaviour should be the same

just put some effort and properly try to reproduce the bug before saying that it isnt a bug?

**Comment by dimaguy** [comment]
> 
> 
> > Hmm well then all I can say is that Impostor has no way of distinguishing lan and wan. So port behaviour should be the same
> 
> just put some effort and properly try to reproduce the bug before saying that it isnt a bug?

I reproduced it on the needed environment. there is really no reason for me to pull up another machine as this behavior is known and generally the problem is the human and some mistake.
NOTE: Behaviour in localhost is 100% the same as if you were using the internet

**Comment by dimaguy** [comment]
Also you never showed me your router port forward allocation

**Comment by Chicken** [comment]
Well could you atleast tell me how to open 2 clients at the same because steam doesn't seem to like it.

**Comment by dimaguy** [comment]
> 
> 
> Well could you atleast tell me how to open 2 clients at the same because steam doesn't seem to like it.

Get Itch.io version or android emulator

**Comment by Azim** [comment]
> I reproduced it on the needed environment.

on the wrong Impostor server version built for different client version

> this behavior is known and generally the problem is the human and some mistake.

then why would it work on defaul port and not on the custom one, if all the other factors (port forwarding, etc) are accounted for?

**Comment by dimaguy** [comment]
> 
> 
> > I reproduced it on the needed environment.
> 
> on the wrong Impostor server version built for different client version

Nop, if you see the print I sent the one there is 1.2.2
> 
> > this behavior is known and generally the problem is the human and some mistake.
> 
> then why would it work on defaul port and not on the custom one, if all the other factors (port forwarding, etc) are accounted for?

Then someone needs to go back to networking 101

**Comment by Azim** [comment]
> Nop, if you see the print I sent the one there is 1.2.2

but the one you invited me to join clearly wasnt

**Comment by dimaguy** [comment]
> 
> 
> > Nop, if you see the print I sent the one there is 1.2.2
> 
> but the one you invited me to join clearly wasnt

And? I wouldnt send you to my main machine lel.
I sent you an ip of a vps I had running Pterodactyl

**Comment by Azim** [comment]
> And? I wouldnt send you to my main machine lel.
> I sent you an ip of a vps I had running Pterodactyl

then how does it help troubleshoot the issue at all? you are opposite of helpful here

**Comment by dimaguy** [comment]
> 
> 
> > And? I wouldnt send you to my main machine lel.
> > I sent you an ip of a vps I had running Pterodactyl
> 
> then how does it help troubleshoot the issue at all? you are opposite of helpful here

You are the opposite of nice here. I already told you the fault is somewhere in between you, the configurations, your router or the patcher. and not in the main subject of this issue

**Comment by Azim** [comment]
> You are the opposite of nice here. I already told you the fault is somewhere in between you, the configurations, your router or the patcher. and not in the main subject of this issue

oh excuse me, your highness, would you be so kind to properly reproduce the issue before throwing out such accusations?

**Comment by dimaguy** [comment]
> 
> 
> > You are the opposite of nice here. I already told you the fault is somewhere in between you, the configurations, your router or the patcher. and not in the main subject of this issue
> 
> oh excuse me, your highness, would you be so kind to properly reproduce the issue before throwing out such accusations?

I did, the screenshot proves it. I dont need to whip up more machines to prove my point

**Comment by AeonLucid** [comment]
Please join the discord server in the readme. GitHub issues are not meant for conversations.

**Comment by AeonLucid** [comment]
Not an Inpostor issue.
