### ISSUE TITLE
[Feature Request] Announcement server implementation

### ISSUE THREAD

**Issue by Sanae6** [Impostor/Impostor#186]
# Feature Request
Enabling an Impostor server to serve announcements.
## Feature Information:
Announcement servers allow for sending info from the server to the users, and will be polled every time they go to the main menu. It supports [coloured text and links too](https://wiki.weewoo.net/wiki/Text), so it's not all plain text. All the information for setting up an announcement server should be found [here](https://wiki.weewoo.net/wiki/Announcements) Ideally an implementation would allow for servers to have a config option and a specific event to manage their announcements.

![Hello World announcement test](https://user-images.githubusercontent.com/32604996/100038043-ec885980-2dc8-11eb-804e-8b991017681b.png)

**Comment by Sanae6** [comment]
Because it's been like 21 days and nobody's said anything, I may as well just put [my alternative](https://github.com/Sanae6/announce/releases) until someone or myself starts making a C# implementation. It shouldn't be as hard to write as my last two implementations because both of them didn't have Hazel in their original languages, so it would be comparatively easy to implement one into Impostor. I'll try to submit a PR after I get some time but no promises.

**Comment by gavinsteinhoff** [comment]
Sounds Cool.

**Comment by dimaguy** [comment]
[ImpostorHQ](https://dimaguy.github.io/ImpostorHQ/) Plugin has this as a feature, would be nice to see it embedded in Impostor.
I also suggest that a filewatch could be setup so Impostor keeps track of announcement file changes while it doesn't have a console input setup yet.

**Comment by js6pak** [comment]
imo this should just cause plugin event, and don't have any implementation (like loading text form file) by default
