### ISSUE TITLE
A fatal error occurred. The required library hostfxr.dll could not be found

### ISSUE THREAD

**Issue by anunkai** [Impostor/Impostor#187]
sorry for the bad english

when i tried to open the run.bat i got this message and i don't know how to fix
![image](https://user-images.githubusercontent.com/50621779/100048227-253d2880-2df3-11eb-9506-ba64a19f078a.png)

i tried to reinstall the .net runtime and didn't work

**Comment by gabriel-nsiqueira** [comment]
Open the link in the cmd and install dotnet

**Comment by reecebenson** [comment]
Please install .NET Core 5's runtime libraries:


OS | Installers
-- | --
Linux | [Package manager instructions](https://docs.microsoft.com/dotnet/core/install/linux-package-managers)
macOS | [x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-macos-x64-installer)
Windows | [Arm64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-arm64-installer \| [x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-x64-installer) \| [x86](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-x86-installer)
All | [dotnet-install scripts](https://dotnet.microsoft.com/download/dotnet-core/scripts)

You're more than likely looking for .NET Core 5 for Windows 64-bit, which is [found here](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-x64-installer).

**Comment by js6pak** [comment]
appveyor still has RC version of .net core?

**Comment by anunkai** [comment]
> Please install .NET Core 5's runtime libraries:
> 
> OS	Installers
> Linux	[Package manager instructions](https://docs.microsoft.com/dotnet/core/install/linux-package-managers)
> macOS	[x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-macos-x64-installer)
> Windows	[Arm64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-arm64-installer) | [x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-x64-installer) | [x86](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-x86-installer)
> All	[dotnet-install scripts](https://dotnet.microsoft.com/download/dotnet-core/scripts)
> You're more than likely looking for .NET Core 5 for Windows 64-bit, which is [found here](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.0-windows-x64-installer).

i already did that at least 20 times and nothing

**Comment by anunkai** [comment]
> Open the link in the cmd and install dotnet core

don't work

**Comment by anunkai** [comment]
> appveyor still has RC version of .net core?

sorry i didn't understand the question

**Comment by anunkai** [comment]
for some reason the archive was in the wrong folder, i changed that and everything worked

thanks for the help
