### ISSUE TITLE
Ctrl+C doesn't properly shut down services when players are connected

### ISSUE THREAD

**Issue by Saghetti0** [Impostor/Impostor#193]
# Bug Report

## Base Information
- Operating System: Ubuntu 18.04
- Impostor Version: latest
- Among Us Version: 2020.11.04s

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms

Services don't properly shut down when the server is terminated while under load. This prevents the OnDisable of plugins from getting called.

## Reproduction

1. Get like 300 players online (this one might be a bit difficult)
2. Try and use Ctrl+C to shut down the server
3. Watch as the errors roll in
![unknown](https://user-images.githubusercontent.com/60995055/100321097-0798cc00-2f77-11eb-925b-fc0b6ceafc1b.png)

**Comment by roobscoob** [comment]
26 days with no relevant comments lmao

**Comment by LorenzoPapi** [comment]
Looks like the fatal error (that makes Impostor close unexpectedly), comes from `Impostor.Plugins.SkeldSync`, which doesn't exist on the base Impostor, which means that no-one can help since the server is running a modified Impostor version

**Comment by dimaguy** [comment]
I mean taking a look at the error stack you can immediately tell which part is failing to be disabled and it for sure isn't impostor.
I am not a C# Developer but I can *read*. SkeldSync calls for an enumeration of a collection which at the moment is modified(somehow... its a system lib which again isn't Impostor's scope). Impostor cannot properly shut down services properly when ***the services ask to execute some broken code on exit***

**Comment by roobscoob** [comment]
@Saghetti0 is this replicable on Base impostor, w/o skeldsync?

**Comment by LorenzoPapi** [comment]
From the stack trace, no, because the error is exactly there.

**Comment by Saghetti0** [comment]
@dimaguy How about... the hundreds of other exceptions being thrown like right above?

**Comment by LorenzoPapi** [comment]
The other errors before (ERR, not FTL, like the last one), are a consequence of the CTRL+ C, and they mean that the connections are closing

**Comment by dimaguy** [comment]
Its exacly what Lorenzo is saying, If you are shutting off Impostor that means that it will close all connections currently on it. So it cannot sent data to them nor receive/send awaited ACKs from previous requests. It is not Impostor's fault as it is an expected error from Hazel protocol.
If you want the errors to be gone wait for all last requests to be finished and only then close the server

**Comment by Saghetti0** [comment]
Reopening this issue under a different title
