### ISSUE TITLE
PlayerCompletedTaskEvent Task is wrong

### ISSUE THREAD

**Issue by benhartland** [Impostor/Impostor#194]
/src/Impostor.Server/Events/Game/Player/PlayerCompletedTaskEvent.cs

Task reports back the wrong task completed.

First task completed seems to be submitScan which is 0, and the number seems to increment upward from there through the task list skipping a few along the way, but still incrementing. 

I stopped at 14 (Divert Power) 

My testing setup: 
Add logging to PlayerCompletedTaskEvent after Task = (TaskTypes)taskID; 
System.Console.WriteLine($"{playerControl.PlayerInfo.PlayerName} completed {Task.ToString()}");

Set common tasks to 30 (this gives a bunch of swipe card I can do back to back) 

It's more likely that taskID is not the task, but an index of that players task, which means Task = (TaskTypes)taskID; returns the wrong task. It could be more like Task = (TaskTypes)player.Character.Tasks[taskID] (would need to check, but you get the idea)

**Comment by benhartland** [comment]
More info.

Task List in game display order. 
0 Admin: Fix Wiring
1 Admin: Swipe Card
2 Admin: Swipe Card
3 Storage: Fix Wiring
4 Navigation: Fix Wiring
5 Admin: Swipe Card
6 Admin: Swipe Card
7 Storage: Fix Wiring
8 Admin: Swipe Card
9 Admin: Fix Wiring
10 Admin: Swipe Card 

Going straight to admin and doing swipe card gives following on console. 

Crewmate completed PrimeShields (1)
Crewmate completed FuelEngines (2) 
Crewmate completed SwipeCard (5) 
Crewmate completed ClearAsteroids (6)
Crewmate completed InspectSample (8)
Crewmate completed EmptyGarbage (10)

This matches the enum TaskTypes, so Task = (TaskTypes)taskID; gives the wrong task that was completed. 
I've also tried Task = playerControl.PlayerInfo.Tasks[(int)taskID].Type; but this gives the same number.

**Comment by Mr-VIT** [comment]
https://github.com/Impostor/Impostor/pull/164
