### ISSUE TITLE
General purpose config folder for plugins to host their configuration files or folders

### ISSUE THREAD

**Issue by kantesilvestrs** [Impostor/Impostor#195]
# Api Suggestion

## Suggestion
- On server start check if config folder exists and create it.
- Standardize usage of the config folder in Impostor docs for plugin developers

## Use case
- Currently every plugin developer is putting their config folders or files wherever they want them to be, this becomes an issue when users want to set-up container instances in cloud environment, not only users need to create separate volumes for each config folder but in certain scenarios the Impostor server folder `/app` just needs to be mounted as a volume - because developers put their config files directly in `/app`

**Comment by gavinsteinhoff** [comment]
Why not store configs in a folder in side the plugins folder? 

So if a your plugin is called Test, it would be plugins/Test/config.json

This could even be automated by the server, and there could be a method to get your plugin's data folder.
