### ISSUE TITLE
Patcher Client don't accept host names.

### ISSUE THREAD

**Issue by diegobh** [Impostor/Impostor#196]
# Bug Report

## Base Information
- W10 Pro
- Impostor v1.2.2
- Among Us v2020.11.17s

## Reproduction

Open Impostor.exe
Put in Ip Adress some hostname that redirects to the ip: myamongus.tk
Click Save Button
It will save the latest ip of the list, not my hostname: myamongus.tk

Any way to fix this, please?

ty!!!

**Comment by reecebenson** [comment]
The Patcher Client intentionally does a DNS lookup to grab the IP address from the host name.

Among Us does not support host names, hence why it resolves to an IP.

**Comment by diegobh** [comment]
> The Patcher Client intentionally does a DNS lookup to grab the IP address from the host name.
> 
> Among Us does not support host names, hence why it resolves to an IP.

o.o =(
ok, thank you!!!

**Comment by AeonLucid** [comment]
Valid issue, keep it open.
