### ISSUE TITLE
Can't connect on Public

### ISSUE THREAD

**Issue by diegobh** [Impostor/Impostor#199]
# Bug Report

## Base Information
- w10
- Impostor Version: 1.2.2
- Among Us Version: Latest

## I confirm:
- [ x ] that I have searched for an existing bug report for this issue.

## Reproduction

**Host pc:** 
Openned the game
Clicked Online and Host a server
Set the server to Public

**Other Pc:**
Opened the game
Found the Public Server
Double Clicked the Public Server
Can't connect: Connect error.

It works nice if the server is private and connect with the server key/password.
But can't connect with server set as public.

How fix it, please?
Thank you!

**Comment by diegobh** [comment]
Any help, please?

I just want to play with out need to give the key to others join the game. I want then double clicked the server listed in server list and can join the lobby.

Thank you!

**Comment by Mr-VIT** [comment]
Can't reproduce the problem. I always successfully connect to public game.

**Comment by AeonLucid** [comment]
Set the `PublicIp` properly in your configuration.
See https://github.com/Impostor/Impostor/blob/dev/docs/Server-configuration.md#required-server-configuration.
