### ISSUE TITLE
Infinite Players

### ISSUE THREAD

**Issue by LouayAttahiri** [Impostor/Impostor#200]
How can i play with Infinite Players?

**Comment by dimaguy** [comment]
You can already play with infinite players, each in their own lobbies as long as you have enough hardware power

**Comment by LouayAttahiri** [comment]
The max is 10? When i reach then he say its full?

**Comment by dimaguy** [comment]
The max per-lobby is 10, for more you need client mods

**Comment by dimaguy** [comment]
That is outside of the scope of this issue
