### ISSUE TITLE
Make Imposter Able to run on other ports

### ISSUE THREAD

**Issue by RehanPlayz** [Impostor/Impostor#204]
# Feature Request

## Feature Information: Run on other Ports
 A way to run imposter on other ports other than 22023

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by realcheesegames** [comment]
Did you even look at the config.json file? It has a section for ports!
`
﻿{
  "Server": {
    "PublicIp": "127.0.0.1",
    **"PublicPort": 22023,**
    "ListenIp": "0.0.0.0",
    **"ListenPort": 22023**
  },
  "AntiCheat": {
    "BanIpFromGame": true
  }
}
`

**Comment by RehanPlayz** [comment]
Oh ok NVM
