### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by LouayAttahiri** [Impostor/Impostor#205]
How can i use mods in my own server without get banned?

**Comment by LouayAttahiri** [comment]
Or how can i delete anti cheat?

**Comment by gabriel-nsiqueira** [comment]
Edit out everywhere it says throw new ImpostorCheat in the source code

**Comment by dimaguy** [comment]
> How can i use mods in my own server without get banned?

Set BanIpFromGame to false so you dont get banned


> Or how can i delete anti cheat?

By learning c# and removing it from source code

**Comment by LouayAttahiri** [comment]
Thanks guys :)

**Comment by LouayAttahiri** [comment]
> > How can i use mods in my own server without get banned?
> 
> Set BanIpFromGame to false so you dont get banned
> 
> > Or how can i delete anti cheat?
> 
> By learning c# and removing it from source code

Is this true someone said to me its not working?

**Comment by dimaguy** [comment]
> 
> 
> > > How can i use mods in my own server without get banned?
> > 
> > 
> > Set BanIpFromGame to false so you dont get banned
> > > Or how can i delete anti cheat?
> > 
> > 
> > By learning c# and removing it from source code
> 
> Is this true someone said to me its not working?

*you no longer get banned thats for sure*

**Comment by LouayAttahiri** [comment]
> Edit out everywhere it says throw new ImpostorCheat in the source code

which ddl file???

**Comment by XtraCube** [comment]
It's not in a DLL file. You need to rebuild the source in Visual Studio

**Comment by LouayAttahiri** [comment]
> It's not in a DLL file. You need to rebuild the source in Visual Studio

imposter files or among us files?

**Comment by dimaguy** [comment]
Impos***O***r's

**Comment by LouayAttahiri** [comment]
> Impos_**O**_r's

thanks
