### ISSUE TITLE
Change region name

### ISSUE THREAD

**Issue by Richardk2n** [Impostor/Impostor#207]
# Feature Request

## Feature Information:

I noticed, that it is possible to change the region name in the regionInfo.dat file to any 8 characters. If this is not a limit by the game but by the server, could this be changed to support other name lengths as well?
## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by EduZIKAAMOUNGUS** [comment]
Yes I confim

**Comment by gavinsteinhoff** [comment]
Are you talking about changing this Region name?
![image](https://user-images.githubusercontent.com/10859074/101214360-86f66180-3641-11eb-8b6e-00e466c11fa4.png)

**Comment by Richardk2n** [comment]
> Are you talking about changing this Region name?
> ![image](https://user-images.githubusercontent.com/10859074/101214360-86f66180-3641-11eb-8b6e-00e466c11fa4.png)

yes

**Comment by gavinsteinhoff** [comment]
Ok, so you are requesting the impostor patcher to support custom region names.

**Comment by Richardk2n** [comment]
If this is something that would be part of the patcher yes.

I would like to have custom region names, but have no idea what would be required to allow that.

**Comment by Richardk2n** [comment]
Found a manual way:
The reason changing the name does not work, is because the length of the name is coded into the file if one can read javascript it is easy to use https://impostor.github.io/Impostor/ to make files for custom names.

Open your browsers console while on the website and while having the form filled out and enter:
```
a = function(n){
        let serverIp = $("#ip").val();
        let serverPort = $("#port").val();
        let serverFileBytes = generateServerFile(n, serverIp, serverPort);
        let blob = new Blob([serverFileBytes.buffer]);
        saveFile(blob, "regionInfo.dat");
    }
```
Then you can write:
`a("Whatever name you want")`
To get your special file

For anyone doing that as well: The website/javascript uses utf-16 while the game uses utf-8 as far as i can tell, so if for example you want the umlaut ö you cannot input ö or the expected \u00F6 but have to use \u00C3\u00B6 which will probably look wrong in the output file but correct ingame.

**Comment by js6pak** [comment]
Actually cli version already supports chaning region name - `./Impostor.Patcher.Cli --address 127.0.0.1 --name localhost`
