### ISSUE TITLE
PlayerJoined and PlayerLeft are missing data

### ISSUE THREAD

**Issue by Lauriichan** [Impostor/Impostor#210]
# Api missing data

## Data

[IGamePlayerLeftEvent ](https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Api/Events/Game/IGamePlayerLeftEvent.cs) and [IGamePlayerJoinedEvent ](https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Api/Events/Game/IGamePlayerJoinedEvent.cs) do not provide methods to get the player
Even tho their implementations got such methods, see: 
[GamePlayerLeftEvent](https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Server/Events/Game/GamePlayerLeftEvent.cs)
[GamePlayerJoinedEvent](https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Server/Events/Game/GamePlayerJoinedEvent.cs)

## Use-case

To get the player that joined or left

**Comment by XtraCube** [comment]
bump to prevent stale bot from closing this issue
