### ISSUE TITLE
IGamePlayerLeftEvent doesn't fire 

### ISSUE THREAD

**Issue by LorenzoPapi** [Impostor/Impostor#214]
So I have this test plugin and I have a listener for `IGamePlayerLeftEvent`, but when a player leaves the event doesn't seem to fire and nothing I write in the listener happens.
1. Create a simple plugin with a listener for the event and put it in an Impostor server.
2. Create a lobby and make another person join.
3. Make the person that last joined (not the host) leave
4. The event doesn't fire.

Same thing happens with the host, but I think it might be because the room destruction has more priority over the LeftEvent (didn't look at this, just guessing).
I'm using latest impostor server and latest api.

**Comment by XtraCube** [comment]
Valid issue, won't let stale bot close

**Comment by js6pak** [comment]
I'm not able to reproduce?
