### ISSUE TITLE
Bug .NET with nodes

### ISSUE THREAD

**Issue by DoctaEnkoda** [Impostor/Impostor#219]
# Bug Report
## Base Information
- Windows Server 2019 / Linux Debian Buster
- 1.2.2
- 2020-12-05

## I confirm:
- [x ] that I have searched for an existing bug report for this issue.

## Symptoms 

`System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=token`

## Reproduction
Just set redis server and try connect

**Comment by AeonLucid** [comment]
Do you have plugins installed?

**Comment by DoctaEnkoda** [comment]
no
