### ISSUE TITLE
Add the Glitch Pet to the API

### ISSUE THREAD

**Issue by CheepYT** [Impostor/Impostor#220]
# Add the Glitch Pet to the API

## Data
Add the Glitch Pet to Impostor.API.Innersloth.Customization.
Pet ID is 11

![image](https://user-images.githubusercontent.com/19333294/101756116-f652d200-3ad5-11eb-9330-a4fa01fe4f45.png)

![image](https://user-images.githubusercontent.com/19333294/101756083-ee932d80-3ad5-11eb-8c6d-445d9898df65.png)

**Comment by McMistrzYT** [comment]
It's called the Twitch Pet, but yeah, it's a good idea.
