### ISSUE TITLE
RpcCalls.EnterVent is not working per me

### ISSUE THREAD

**Issue by SushiBtw** [Impostor/Impostor#226]
Hey! ``RpcCalls.EnterVent`` is not firing for me when i define a case in ``InnerPlayerControl.cs`` file.

I am not receiving the RPC event when someone is Entering the Vent.

**Comment by js6pak** [comment]
Because its rpc of [`InnerPlayerPhysics`](https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Server/Net/Inner/Objects/Components/InnerPlayerPhysics.cs#L24) not `InnerPlayerControl`

**Comment by SushiBtw** [comment]
Already aware of it, I will create a PR asap I test the function.
For now, all is looking good.
