### ISSUE TITLE
[Question] Debian package for iOS

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Impostor/Impostor#249]
Does anyone know where I can get a Debian package for iOS?

**Comment by fullonrager** [comment]
There is no Impostor Server package for iOS. If you're asking for a way to connect to a private server on iOS, use the jailbreak tweak ImpostorConfig by pixelomer.

**Comment by TheAwesome98-Real** [comment]
> There is no Impostor Server package for iOS. If you're asking for a way to connect to a private server on iOS, use the jailbreak tweak ImpostorConfig by pixelomer.

Thanks!
