### ISSUE TITLE
Issue connecting to Imposter Server on Among Us v2020.11.17a

### ISSUE THREAD

**Issue by GDEngine** [Impostor/Impostor#251]
# Bug Report

## Base Information
- Operating System: Android 10 for client, Windows 10 for server.
- Impostor Version: v1.2.2-ci.123
- Among Us Version: v2020.11.17a.

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

Whenever I try to click "Find Game" or try to host a game when connected to my server hosted on my PC using my android phone, it sends out this error for find game: `You disconnected from the server. Reliable packet 1 (size=18) was not ack'd after 7511ms (9 resends)` and for creating a game its the same thing. I have double checked that the public ip and port in config.json is the same as in regionInfo.dat, and they are. My router has not been port forwarded however both my pc and my phone are connected to the same network. Is there something wrong with my current version of among us, or is something else going wrong?

**Comment by przebor** [comment]
Besides that in English you can spell it both Impostor and Imposter, on Github, this project is named Impost**o**r.
😄

**Comment by GDEngine** [comment]
yes i know that

**Comment by Dycool** [comment]
Instead of using your public ip on the regionInfo.dat, why not using the local ip?

**Comment by GDEngine** [comment]
I have tried that, and this also resulted in the same error message as before. Not quite sure what's happening or if I'm doing something wrong.

**Comment by schuub** [comment]
I suggest you try to connect from the PC where you are running the server from to check if it's a network problem or not.
use `127.0.0.1` in `regionInfo.dat` for that.
It would also help if you can find a way to ping your server from your phone for troubleshooting, I'm not sure if Android can do that.

**Comment by GDEngine** [comment]
I would do that, but at the moment steam is being a bit funky and won't let me launch among us. I will try again tomorrow when I have the time.

**Comment by Foolius** [comment]
I have the same problem. I tried different configurations with the server being on the same machine as the game but it's always OP's error message. However I can't find regionInfo.dat where is that file?

**Comment by lexouma** [comment]
I have the same problem, if there are any solution ? thks

**Comment by HondaCorollaSTi** [comment]
I have this problem as well. I'm not sure what I am doing wrong.

**Comment by marie6324** [comment]
The solution is to not look for software support in a bug tracker.  Go to the discord if you're after support.
