### ISSUE TITLE
Google Chromebook Support

### ISSUE THREAD

**Issue by ETE-Design** [Impostor/Impostor#255]
Would be really nice if it could work on Google Chromebook.

**Comment by dimaguy** [comment]
It is possible.
Put linux on the chromebook and use the linux build of Impostor.

**Comment by ETE-Design** [comment]
@dimaguy Not possible to make many changes since it is in my daughters Chromebook for Scholl :-( They All Play it but often get kickers out and have errors, so would create my own Dedicated Server they can joint :-)

**Comment by dimaguy** [comment]
If you cannot run linux. Then I believe it is game over

**Comment by ETE-Design** [comment]
@dimaguy Where to finc Linux Imposter Client?

**Comment by js6pak** [comment]
How are you running among us on chromebook in the first place? wine or android build?
