### ISSUE TITLE
Host doesn't broadcast vote to server?

### ISSUE THREAD

**Issue by xtcp** [Impostor/Impostor#258]
Hello,

As the title says, I've been handling "RpcCalls.CastVote" and when the host votes, it doesn't even get triggered, is it that the host only broadcasts the vote directly to the players and not the server?

Thank you in advance,
Regards

**Comment by Mr-VIT** [comment]
> is it that the host only broadcasts the vote directly to the players and not the server?

yes.

**Comment by Mr-VIT** [comment]
The host does not need to call  `CastVote`. This RPC is only from regular clients to the host

**Comment by js6pak** [comment]
Host doesn't send CastVote, he just changes player states and sets a dirty flag, causing `MeetingHud.Deserialize` on server
