### ISSUE TITLE
Forum or other discussion area

### ISSUE THREAD

**Issue by shepherdjerred** [Impostor/Impostor#265]
Is there a forum or other place to discuss Imposter? If not I'd be willing to set one up. I have an old XenForo license laying around...

**Comment by Sanae6** [comment]
Discussion for Impostor development happens either on the Discord server, or over issue/pr comments. Hope I could answer your question :)

**Comment by shepherdjerred** [comment]
Are there any places where plugins are shared?

**Comment by dimaguy** [comment]
> Are there any places where plugins are shared?

Pinned in #support
