### ISSUE TITLE
Adding mobile support?

### ISSUE THREAD

**Issue by dannysmc95** [Impostor/Impostor#268]
# Feature Request

## Feature Information:
I was wondering if you plan to add support for mobile applications? So adding support for iOS and Android? Even if it's not hosted directly on the app store, but just installable via external sources (not sure if iOS can do that though).

Would be awesome if this could become a thing, as we run a gaming server, we would like to have a little more control over the servers, as the public servers (as everyone knows) are fairly... touch and go.

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by gavinsteinhoff** [comment]
Do you mean having players connect to your custom server via their phone? If so, there is an android app that might work for you: https://github.com/NaokiStark/Crewmate-switcher

**Comment by dimaguy** [comment]
There are instructions for mobile devices in the readme, feel free to take a look over there

**Comment by dannysmc95** [comment]
@gavinsteinhoff ooooooooo, that is interesting, I haven't seen that.

@dimaguy my bad, I hadn't even seen that, shall check now tho, thanks!
