### ISSUE TITLE
virus total report

### ISSUE THREAD

**Issue by Xyz00777** [Impostor/Impostor#272]
FYI
I have uploaded the Imposter-Client-win-x64.zip version 1.1.0
https://www.virustotal.com/gui/file/af471238b3a3cc3fb5270d75c0215f01178235e9917689e86117b055b0e24263/detection
and here is the exe file
https://www.virustotal.com/gui/file/6e91c05888f7c4b9a65852454ce900359cb200136fe81418093a35250aa4f6aa/detection
i dont think you have something in there but i would like if you could recheck

**Comment by dimaguy** [comment]
You do realize that not everyone has a hundred bucks at hand to sign a piece of software with microsoft dev certificate so that antiviruses shut up right?

**Comment by gavinsteinhoff** [comment]
The code is not signed, so there will be some anti-virus software programs that will not like it. 

That is just how it will be unless Impostor gets a Certificate. These can range in price, but are fairly expensive. 

The code is all open source and you can even compile it yourself if you have any worries.

**Comment by Xyz00777** [comment]
yeah i know that ;) but the zip one dont need a license and it should has also the malware within.
i know that it can be simple a wrong information but i just wanted to let you know that there is a response.
what you want to do with it is your choice (contact the support and let them know propably, i dont know) :)

**Comment by dimaguy** [comment]
The sole AV that flagged the file isnt properly one that is famous for its accuracy.
Some heuristics are just too sensible...
Anyways the source is provided so theres nothing under hiding.
