### ISSUE TITLE
Find game gives disconnect error

### ISSUE THREAD

**Issue by varun31415** [Impostor/Impostor#280]
# Bug Report

## Base Information
- Operating System: bluestacks 4 for client, mac os x catalina for server
- Impostor Version: latest
- Among Us Version: v2020.11.17

## I confirm:
- that I have searched for an existing bug report for this issue.

Whenever I click find game and select a game, it gives the "you disconnected from the server" error. Creating a game and joining through the game code is working fine. Could someone help? I am running the game locally.

**Comment by js6pak** [comment]
Whats your server config? Is your public ip set correctly?
