### ISSUE TITLE
Ability to disable name/color checks with config

### ISSUE THREAD

**Issue by Galster-dev** [Impostor/Impostor#281]
# Feature Request

## Feature Information:
Since [last commit](https://github.com/Impostor/Impostor/commit/f2d653106331a5a8ed5d0f15d5e9c97fca463cff) Impostor does not allow people to have the same color, which is required for 12+ player game. I don't think everyone is able to patch the server themselves, so the best solution is to make this feature configurable

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by Phoenix616** [comment]
Ideally this would be a per-lobby setting but maybe exposing that (e.g. in commands) should be left up to plugins?
