### ISSUE TITLE
I can't host a game

### ISSUE THREAD

**Issue by aelias1234** [Impostor/Impostor#292]
# Bug Report

## Base Information
- Operating System Windows 10 x64 Home
- Impostor Version 1.1.0
- Among Us Version 12.9S

## I confirm:
- [ Yes] that I have searched for an existing bug report for this issue.

## Symptoms 
I can't host a game

Write symptoms here.
-->https://gyazo.com/bc64cc71c04666dbe1c4c2d47c0dcd0a

Enter Symptoms on this line.
https://gyazo.com/bc64cc71c04666dbe1c4c2d47c0dcd0a

**Comment by Tom60chat** [comment]
How can i join a custom server?
Go to your game directory and open BepInEx/config/org.bepinex.plugins.SheriffMod.txt. There you can set the hostname or IP of the server. Then set the server region to CUSTOM.

**Comment by Tom60chat** [comment]
https://impostor.github.io/Impostor/

**Comment by EVOWill** [comment]
Yes, I met the same symptoms

**Comment by js6pak** [comment]
Can you post your config?
