### ISSUE TITLE
Anticheat false positive - MurderPlayer too fast

### ISSUE THREAD

**Issue by JohnTranQUT** [Impostor/Impostor#294]
# Bug Report

## Base Information
- Linux ubuntu 18.04
- Impostor ver 1.2.2 compiled into unbuntu 18.04
- Among Us vs 2020 11 17a on Andriod via Bluestacks.

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 
- False negative flagging of players that had killed faster than kill cool down time.

## Reproduction
Req:
- Bluestack/Andriod version of Among Us
- Impostor server
- Kill cooldown was set at 22.5s by host
Do:
- Kill as fast as possible

```
[03:45:01 INF] RAKBPJ - Azn3 murdered AznDumbum.
[03:45:23 INF] RAKBPJ - Player Azn3 (9) has left.
[03:45:23 INF] RAKBPJ - [9] has disconnected
[03:45:23 INF] Client 9 disconnecting, reason: Client sent MurderPlayer too fast
[03:45:23 INF] RAKBPJ - Game ended by HumansByVote
```

**Comment by JohnTranQUT** [comment]
Actually, this is happening across the broad.
I am unsure but I believe if there is latency involved, the timings could be overlapping, causing false positives for murders.

**Comment by XtraCube** [comment]
Yes I noticed this issue happening a lot on my modded server, which is PC only

**Comment by js6pak** [comment]
Is anyone able to reproduce this with latest master?

**Comment by JohnTranQUT** [comment]
@js6pak I have gotten logs of kills too early based off of the latest master.
Its less frequent but there are stil false positives, as the follow screenshot can show.
![image](https://user-images.githubusercontent.com/22422390/111086925-96534800-856a-11eb-84bc-be8bb8b7e95e.png)

**Comment by js6pak** [comment]
Does it happen only with mobile?
Failed ownership check also looks scary.

**Comment by js6pak** [comment]
Now that I think about it, it makes perfect sense. Client resets his kill timer without waiting for any response, so if he has high ping, server will have incorrect time.

**Comment by JohnTranQUT** [comment]
> Now that I think about it, it makes perfect sense. Client resets his kill timer without waiting for any response, so if he has high ping, server will have incorrect time.

@js6pak Pretty much what I'd figured it would be. The ping is a steady 200-250ms.
Somehow compensating for ping descreprency would solve the false positive timing of this.

> Does it happen only with mobile?
> Failed ownership check also looks scary.

I've managed to make it happen on the PC in a previous branch. For this branch, I haven't tested it thoroughly.

Please ignore that. I believe it happens likely because of the issue around https://github.com/Impostor/Impostor/issues/344 , Instead, I used a try and catch to at get by. Janky solution to from a novice coder.

**Comment by js6pak** [comment]
@JohnTranQUT Could you check this again but with #387?
