### ISSUE TITLE
2020.12.9 pls

### ISSUE THREAD

**Issue by epicwappy20** [Impostor/Impostor#302]
# Feature Request

## I confirm:
- [ ] that I have searched for an existing feature request matching the description.

**Comment by dimaguy** [comment]
Have you tried using version 1.2.2? We support all versions at the moment

**Comment by epicwappy20** [comment]
oh well that ver has adware on the server

**Comment by dimaguy** [comment]
What do you mean has adware? You do realize that it is entirely open source if you want to compile yourself

**Comment by epicwappy20** [comment]
the server zip that is downloadable has adware in it

**Comment by dimaguy** [comment]
It is an unsigned executable, so antiviruses have a bone to pick with it. if you dont trust it just compile from source anyways

**Comment by Mm2PL** [comment]
> the server zip that is downloadable has adware in it

Sounds like an antivirus false-positive to me. I don't believe anyone would want to sacrifice their own project's good reputation to send some adware to people.

**Comment by epicwappy20** [comment]
how do i compile it

**Comment by epicwappy20** [comment]
idk how

**Comment by dimaguy** [comment]
https://github.com/Impostor/Impostor/blob/dev/docs/Building-from-source.md
errata:net 5 was already released "recently" so you only need to get visual studio community stable

**Comment by epicwappy20** [comment]
oh thx

**Comment by epicwappy20** [comment]
cloning using github desktop

**Comment by dimaguy** [comment]
This is now out of the issue scope, please close the issue and use discord for further support
