### ISSUE TITLE
how to ban player?

### ISSUE THREAD

**Issue by epicwappy20** [Impostor/Impostor#309]
how do you ban someone

**Comment by XtraCube** [comment]
There are multiple ways to do this. First, you could write a plugin that lets you ban people. You could also use an existing plugin like [ImpostorHQ](https://github.com/dimaguy/impostorhq) to achieve this. It has its own plugin to allow IP banning players.

**Comment by epicwappy20** [comment]
um okalso i am using extra roles mod and i need a way to not ban the engineer for venting

**Comment by XtraCube** [comment]
This will require a lot of extra modifications to the server. You will need to modify RPC handling, vent handling, and much more.

**Comment by dimaguy** [comment]
Or just use the reactor fork of impostor. Which we dont support either

**Comment by js6pak** [comment]
> how do you ban someone

with plugin api

> um okalso i am using extra roles mod and i need a way to not ban the engineer for venting

out of scope
