### ISSUE TITLE
Apache proxy how to ?

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [Impostor/Impostor#311]
Hi, Have anyone proxyed there impostor server instance with apache ?? if so i'm interested so i could do it too :)

**Comment by dimaguy** [comment]
Theres no point in doing apache reverse proxy.
Just run impostor in the place of apache as it uses no resources

**Comment by TomAvecLeVdsl** [comment]
for me there is a point as it's my main and most powerfull server, i use it to host Imposor, Crewlink, and my website ... i cant run apache and impostor both at the same time on port 80 and 433 🤔

**Comment by dimaguy** [comment]
You do realize that impostor uses udp not tcp and can actually run at the same time on those ports right?

**Comment by TomAvecLeVdsl** [comment]
👀 i'l try it :) thanks for the help

**Comment by TomAvecLeVdsl** [comment]
![image](https://user-images.githubusercontent.com/29174751/106941832-b1d56280-6723-11eb-9212-fc4203372133.png)
Well it has well started untill ... :(

**Comment by dimaguy** [comment]
Surprise you need to listen at port 80 too

**Comment by TomAvecLeVdsl** [comment]
That's what i did on the 2nd try ...

**Comment by dimaguy** [comment]
Do you have anything udp listening in port 80?

**Comment by TomAvecLeVdsl** [comment]
Euh ... apache isnt udp ? if so i have apache :joy:

**Comment by dimaguy** [comment]
No apache is tcp.

**Comment by Mm2PL** [comment]
Try replacing port 80 in your config with the default, 22023. Also could the other listening thing be another instance of the server?

**Comment by TomAvecLeVdsl** [comment]
yes with the default it works (with my isp public ip not with cloudflare) but on port 80 it does not

**Comment by dimaguy** [comment]
Cloudflare wouldnt let you do it proxied anyways.
Use linux networking tools to figure out whats bogging port 80 udp

**Comment by TomAvecLeVdsl** [comment]
udp        0      0 0.0.0.0:80              0.0.0.0:*                           -
udp6       0      0 [::]:80                 [::]:*                               -

A non existant program :eyes: i dont actualy like that ... same on UDPV6

**Comment by dimaguy** [comment]
What tool did you use?

**Comment by TomAvecLeVdsl** [comment]
i used netstat, ss & lsof ... impossible to identify the udp 80  program

**Comment by dimaguy** [comment]
> 
> 
> i used netstat, ss & lsof ... impossible to identify the udp 80 program

Either identify it or move onto 443

**Comment by js6pak** [comment]
Among Us still has 22023 hard coded in few places, its better to just use it.
Pretty sure `Permission denied` means that system denied your access to the port, can you try running impostor with `sudo`?
If you really want, you can proxy udp with nginx/apache, just google it, but its not really needed.
And I'm pretty sure that cloudflare doesn't proxy udp.

**Comment by TomAvecLeVdsl** [comment]
Hi, i'l think about that ... maybe doing an "srv record" could be enough so i dont have to give my public ip everytime (Yeah just thinking about the srv record now 👀  LUL
