### ISSUE TITLE
Why "high" ping?

### ISSUE THREAD

**Issue by zokradonh** [Impostor/Impostor#313]
I have a dedicated root server in a near computing center. If I ping the linux machine I have a ping of 18ms. I run the Among Us Impostor gameserver there and in the lobby I have a ping of 50. Which is of course not very high and never a problem, but I would like to know where the bottleneck is.

Is it Among Us API that round trips multiple times?
Is it Impostor somehow?

Other gameservers on my server have good pings (ARK).

**Comment by dimaguy** [comment]
Among Us shows a minimum of 50 ms at all times, even if it is lower

**Comment by zokradonh** [comment]
ah thank you! So it is just visual issue?

**Comment by dimaguy** [comment]
Yes it is merely visual
