### ISSUE TITLE
Comms between Impostor/Hazel and Reactor.gg/Client side plugin?

### ISSUE THREAD

**Issue by victorwiebe** [Impostor/Impostor#314]
# Feature Request
Documentation or integration for custom communication - server custom to client reactor.gg custom plugin

## Feature Information:
Basically, we are looking to create a Reactor.gg mod, which will allow us to pull custom skins into the game. We want to query these custom skins from our own impostor server instance.

I do not want to perform database queries or API calls from the client side Reactor.gg app, we feel there might be security issues with that as other mods can just do whatever they want reverse engineering that.

We want to query a REST API or database from inside this project in order to connect out for an interesting project we are working on.

So if you guys can provide me documentation how to talk via Hazel from the server side to a custom client side Reactor.gg plugin, that would be great.

If this is not possible through custom hazel code, please let me know and we can discuss if this is a suitable feature request.

Glad to be here, looking forward to working with you
Victor

## I confirm:
- [X ] that I have searched for an existing feature request matching the description.

**Comment by js6pak** [comment]
Use reactor.gg custom rpc api, go into reactor's discord for help.
Its not a topic for stock impostor tho, so closing.
