### ISSUE TITLE
Random player disconnects

### ISSUE THREAD

**Issue by ParanoikCZE** [Impostor/Impostor#317]
- Operating System: clients W10 + me W7 with locally running Server
- Impostor Version: 1.2.2
- Among Us: 2020.12.9s with Sheriff Mod v1.01

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 
Random player disconnects during play (2 issues during ~20 games), see attached log
20:31 of 4 players at once
20:58 of 1 player (Tris)
[log.txt](https://github.com/Impostor/Impostor/files/5974107/log.txt)
These may be caused by network issues on server side (not very reliable ISP), but logs says that connection was dropped by client side.

## Reproduction
There are no known steps to reproduce.

note:
If there is any way to set debug log level and capture to file (console output is limitted), I'll setup this for next events.

**Comment by dimaguy** [comment]
There seems to be a newer version of sheriff mod available(1.1), try it out and see if it still happens

**Comment by ParanoikCZE** [comment]
I've checked that everyone is on latest version and during ~30 games, no issues, so closing. Thanks for noticing that we are not on latest.
