### ISSUE TITLE
Could not load file or assembly 'BepInEx.IL2CPP, Version=6.0.0.297, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by luixiuno** [Impostor/Impostor#318]
# Bug Report

## Base Information
- Operating System Windows
- Impostor Version 1.2.2
- Among Us Version 2020.11.17s

## I confirm:

- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Could not load file or assembly 'BepInEx.IL2CPP, Version=6.0.0.297, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

## Reproduction

Starting impostor

**Comment by dimaguy** [comment]
Bepinex is a client mod, not a server plugin
