### ISSUE TITLE
[MOD] Others can't see Engineer Vent

### ISSUE THREAD

**Issue by pedroumbelino** [Impostor/Impostor#319]
# Others can't see Engineer Vent properly

## Base Information
- Windows 10 64 bits
- Impostor 1.1.0
- Among Us Version v2020.12.9s

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 

When in a mod with Engineer that can vent, the player itself sees the vent but others don't.

## Reproduction

Stay next to the Engineer in a vent and ask him to vent. The player will stay still on top of the vent, even if he already vented to another area. Only when the Engineer moves is when you see him 'disapper'.

**Comment by dimaguy** [comment]
We do not support mods, please open a ticket with the enginneer mod author
