### ISSUE TITLE
Add tests for packet serialization and deserialization

### ISSUE THREAD

**Issue by Mm2PL** [Impostor/Impostor#32]
# Feature Request

## Feature Information:

I would like to have (de)serialization tests added for `Message00HostGame`, `Message01JoinGame` etc. to reduce possible problems with changing those classes.

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by js6pak** [comment]
@AeonLucid isn't this technically already a thing with ServerReplay?

**Comment by AeonLucid** [comment]
Yes but it does not have 100% coverage. These tests might be useful later.
