### ISSUE TITLE
game says it needs to update and its latests update

### ISSUE THREAD

**Issue by Aturok87** [Impostor/Impostor#320]
# Bug Report

## Base Information
- Operating System windows 10
- Impostor Version 1.1.0
- Among Us Version 2020 12. 9s

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Enter Symptoms on this line.

## Reproduction

Enter reproductions steps here.

**Comment by dimaguy** [comment]
Get Impostor 1.2.2 from readme

**Comment by Aturok87** [comment]
ok i have the new one and the server doesnt stay running

**Comment by Aturok87** [comment]
![among us server](https://user-images.githubusercontent.com/24662968/107941325-2ba0f380-6f4f-11eb-82b3-41fa066b77b5.png)

**Comment by Aturok87** [comment]
ok got it working thank you
