### ISSUE TITLE
You're running an older version of the game

### ISSUE THREAD

**Issue by PouletteMC** [Impostor/Impostor#321]
# Bug Report

## Base Information
- Operating System => Game is on Windows, Server is on Docker using pterodactyl (quay.io/parkervcp/pterodactyl-images:debian_nodejs-12 is the image)
- Impostor Version => 1.1.0 for Linux-x64
- Among Us Version => v2020.12.9s

## I confirm:
- [✔ ] that I have searched for an existing bug report for this issue.

## Symptoms 

I started the server, which compiles and runs fine. I start the game and used bot the Impostor Client and CustomServerSelector mod to change to my server. When trying to create a game I immedaitely get [this](https://ibb.co/h2fMVh6) error.
I know 

## Reproduction

- Start the server
- Start the game
- Connect to the server
- Try to create a new game on the server

**Comment by XtraCube** [comment]
Please update to Impostor 1.2.2

**Comment by PouletteMC** [comment]
It's not in the releases ?

**Comment by XtraCube** [comment]
https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts

**Comment by PouletteMC** [comment]
I'll try that thank you

**Comment by XtraCube** [comment]
You're welcome

**Comment by PouletteMC** [comment]
That did it

**Comment by mindfuucker** [comment]
I seem te be having the same problem. 

Using the docker nightly version, even tried latest to see if that would fix it. 
Among Us was updated last night, could that be it?

**Comment by PouletteMC** [comment]
Yes probably
