### ISSUE TITLE
Where can we found impostor 123 

### ISSUE THREAD

**Issue by fatalterreur** [Impostor/Impostor#326]
Is it possible to downgrade Impostor 124 to 123 to bypass 10 max players ? Or to have the sources of Impostor 124 ?

**Comment by dimaguy** [comment]
The limit is imposed by the client not the server. Please look elsewhere for support with that

**Comment by fatalterreur** [comment]
ok thank you

**Comment by js6pak** [comment]
there https://github.com/Impostor/Impostor
