### ISSUE TITLE
Building a linux version

### ISSUE THREAD

**Issue by MatuxGG** [Impostor/Impostor#329]
Hello,

After cloning the repository, how do you build a Linux version for Impostor.Server ?
In facts, in the download section, there is a Linux version but I don't know how to get the same result.
Maybe it's kinda easy, but I'm pretty new to .NET and all that.

Thanks.

**Comment by dimaguy** [comment]
https://github.com/Impostor/Impostor/blob/dev/docs/Building-from-source.md

**Comment by MatuxGG** [comment]
Yes but an Impostor.Server.dll is built, and it's different from what is provided in Linux release.

**Comment by js6pak** [comment]
What platform are you building it on? `.dll` should work on all platforms, so you can just run server using `dotnet Impostor.Server.dll`, eventually use `-r linux-x64` dotnet build flag to build linux only exe

**Comment by dimaguy** [comment]
On second look, you need to specify that it is building for linux-x64
`dotnet publish -r linux-x64 -c Release`
@js6pak You may want to add that to building instructions

**Comment by MatuxGG** [comment]
With these instructions, it worked perfectly.

Thank you ! :)
