### ISSUE TITLE
Client sent CheckColor with invalid color

### ISSUE THREAD

**Issue by Popeye4242** [Impostor/Impostor#332]
When a player joins that has a modded color (for example the rainbow color from Town of Us) then the whole lobby gets closed. 

![image](https://user-images.githubusercontent.com/35311793/109796164-1cd96280-7c18-11eb-8ecd-2988b8d583dc.png)

The server should not validate the color.

**Comment by dimaguy** [comment]
Impostor in itself does not support modded clients, you will need to make the due changes to the source or maybe use a more adequated fork for the mod

**Comment by Phoenix616** [comment]
You need to disable the anti cheat in the config for such mods to work or I think it's also possible now for the mod to provide a server plugin/communicate via modded RPC calls instead.

**Comment by Popeye4242** [comment]
> You need to disable the anti cheat in the config for such mods to work or I think it's also possible now for the mod to provide a server plugin/communicate via modded RPC calls instead.

I see that #327 refactored the anti cheat logic but it does not seem to be documented if and how the anti cheat can be disabled.

**Comment by Phoenix616** [comment]
https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Server/config-full.json#L14
