### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by epicwappy20** [Impostor/Impostor#340]
among us was updated and impostor should be updated now

**Comment by danbudworthmead** [comment]
@js6pak this guy right here

**Comment by gOOvER** [comment]
Or móve Beta to github, not the shitty Way you have atm. Noone can use impostor really

**Comment by JohnTranQUT** [comment]
> among us was updated and impostor should be updated now
@epicwappy20

Agreed. Works fine as before. This ticket will need to be closed.
The released version is not upto date (download on the Right Hand Side of Github) however if you download the branched codes and compile, they are up to date and working fine.

I noticed they've updated VERY quickly so I believed you had missed or not noticed the 2021.03.05 version.

**Comment by gOOvER** [comment]
> > Or móve Beta to github, not the shitty Way you have atm. Noone can use impostor really
> 
> no problems at all. everything works fine also with the new amongus update.

it cant be used to automate Serverinstalls. Guthub have also solutions to compile and Release the Beta

**Comment by jono99** [comment]
Have downloaded master and 2021.3.5 branch, compiled both and still get outdated version error message in game

**Comment by JohnTranQUT** [comment]
> Have downloaded master and 2021.3.5 branch, compiled both and still get outdated version error message in game

I've redownloaded and recompiled and it worked in windows and ubuntu builds.
I also tested the main branch. The error shows up on main branch but the 2021.3.5 was fine.

**Comment by jono99** [comment]
> > Have downloaded master and 2021.3.5 branch, compiled both and still get outdated version error message in game
> 
> I've redownloaded and recompiled and it worked in windows and ubuntu builds.
> I also tested the main branch. The error shows up on main branch but the 2021.3.5 was fine.

Okay, will try again, thanks.
Nothing in particular that I need to change or set?

**Comment by JohnTranQUT** [comment]
@jono99 I don't think anything needs to be changed. Run the impostor patcher, open sever, and I'm in. I think you might need check the version you've download. Already had over 300 games on the 2021.3.5 version.

**Comment by js6pak** [comment]
Implemented in 72f1e81c5f52d08d42bb3dda010a85dab156bce5
