### ISSUE TITLE
Failed to find player that spawned the InnerPlayerControl

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#344]
# Bug Report
![image](https://user-images.githubusercontent.com/9319945/110271974-f96c3a00-7fc0-11eb-983d-c6ee2073b640.png)

Not sure if this is causing other issues, no visible symptoms.
Not sure why this occurs, it is quite rare.
It only starts to occur once hundreds of players are joining and leaving.

**Comment by JohnTranQUT** [comment]
### I think I am having the same issue
I needed to merge with https://github.com/Impostor/Impostor/pull/181 and so can't say if it's with the main https://github.com/Impostor/Impostor/tree/2021.3.5 branch or with the pull itself.

**Comment by js6pak** [comment]
https://github.com/Impostor/Impostor/issues/410#issuecomment-858939147
