### ISSUE TITLE
ban for cheat ?

### ISSUE THREAD

**Issue by Lunastellia** [Impostor/Impostor#346]
I put a server online (on a vps) and people can join the lobby but when I start the game we are all banned for cheating ... any idea what to do?

![158829930_1679781392232872_4017008000388107835_n](https://user-images.githubusercontent.com/35262707/110486526-05551a80-80ed-11eb-9a57-7547af1d9734.jpg)

**Comment by IrishBruse** [comment]
the server doesnt support the latest among us version currently its being worked on https://github.com/Impostor/Impostor/tree/2021.3.5

**Comment by Lunastellia** [comment]
Dosnt work i use 2020.12.9s gameversion and u have anticheat = false in my config

**Comment by js6pak** [comment]
First of all, please don't use facebook trackers (wtf?)
Can you post your config? From your logs it seems like you have anticheat enabled.

**Comment by js6pak** [comment]
enable or Enabled?

**Comment by Lunastellia** [comment]
Enabled ^^it seems to work I restarted all the test accounts on the game and the server thank you ^^
