### ISSUE TITLE
Impostor 1.2.2 files

### ISSUE THREAD

**Issue by CBowlen** [Impostor/Impostor#347]
Hello, 

Could the files for 1.2.2 Be put in released.

Thank you

**Comment by IrishBruse** [comment]
https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts
there there

**Comment by CBowlen** [comment]
It says 1.2.2 on the click here to download but the files within are for
1.3.0.

**Comment by js6pak** [comment]
https://github.com/Impostor/Impostor/releases/tag/v1.2.2
