### ISSUE TITLE
Extra colors getting banned on entering or selection

### ISSUE THREAD

**Issue by davisa6477** [Impostor/Impostor#348]
I must apologize as I am very green to impostor server and github and finding information that I can understand is very difficult. I have a new server set up that will ban someone when they enter the lobby, or select a modded color. I've tried searching for the information in different areas, but I can't understand enough to get a fix. I have tried changing the config.json file so that it does not ban cheaters, but it still happens. Any help I can get would be appreciated.

**Comment by JohnTranQUT** [comment]
@davisa6477 I think there is ImpostorHQ that has options for you to do that however... I don't know it's compatibility anymore.
Would need someone else to respond to this message with further details.

This is not an issue and belongs in either Discussions or on their discord server for support/help.

I suggest to close this ticket and ask on their discord support channel.

**Comment by dimaguy** [comment]
> @davisa6477 I think there is ImpostorHQ that has options for you to do that however... I don't know it's compatibility anymore.
> Would need someone else to respond to this message with further details.
> 
> This is not an issue and belongs in either Discussions or on their discord server for support/help.
> 
> I suggest to close this ticket and ask on their discord support channel.

ImpostorHQ has been updated to work with Impostor 1.3.0, so it is all fine in that part

**Comment by js6pak** [comment]
ImpostorHQ has nothing to do with this, you are just trying to use mods (aka cheats) on server with enabled anticheat.

**Comment by boemhe** [comment]
I've disabled anti cheat  or at least I thought I did, my conig.json looks like this:

```
{
  "Server": {
    "PublicIp": "MyIPv4",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "BanIpFromGame": false
  }
} 
```

, but friends that are joining still get IP banned after restarted the server for having the wrong color. Any idea why?

**Comment by js6pak** [comment]
Client mods are generally unsupported, in this case you can just disable the anticheat: https://github.com/Impostor/Impostor/blob/master/docs/Server-configuration.md#anticheat
