### ISSUE TITLE
You are running an older version of the game

### ISSUE THREAD

**Issue by gamer4life1** [Impostor/Impostor#354]
# Bug Report

## Base Information
- Operating System: Linux
- Impostor Version: 1.3.0-dev, docker nightly
- Among Us Version: 2021.3.5

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

When trying to join a game with Among Us 2021.3.5 and Impostor 1.3.0, it simply says "You are running an older version of the game".

## Reproduction

Start an Impostor server version 1.3.0 with anticheat disabled and connect to it. This might or might not be related to the change in storing server data: the move from the dat to the json file.

**Comment by gamer4life1** [comment]
fixed issue, accidentally put everything in comments

**Comment by Spokloo** [comment]
i have the same issue and don't know how to fix this

**Comment by js6pak** [comment]
Docker image is not yet updated

**Comment by Spokloo** [comment]
oh ok thanks, is there another way to fix this issue ? or should i wait until the release ?

**Comment by js6pak** [comment]
You can build the docker image yourself

**Comment by Spokloo** [comment]
ok thanks!

**Comment by gamer4life1** [comment]
@js6pak how would we build it ourselves? 
I get this error:
```
Step 1/15 : FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:5.0 AS build
failed to parse platform : "" is an invalid component of "": platform specifier
```

**Comment by js6pak** [comment]
use docker buildx, but docker CI is already fixed, you can just use nightly tag
