### ISSUE TITLE
Unable to set up Impostor Server on Centos 8

### ISSUE THREAD

**Issue by MatuxGG** [Impostor/Impostor#355]
# Bug Report

## Base Information
- Operating System : Centos 8
- Impostor Version : 1.3.0
- Among Us Version : 2021.3.5s

## I confirm:
- [ x] that I have searched for an existing bug report for this issue.

## Symptoms 

Even after a "good configuration" (I guess), I can't connect to the Impostor server.
![image](https://user-images.githubusercontent.com/12508157/111343031-4e701600-867b-11eb-845a-efcef45cec54.png)

## Reproduction

On client side, I'm using Unify to add my server to region list (regionInfo.json).
![image](https://user-images.githubusercontent.com/12508157/111343122-68a9f400-867b-11eb-8505-46492716a7eb.png)
The server ip is 152.228.160.91.

On server side, I'm running the linux x64 (no arm) version of Impostor server.
I changed the public ip in config.json.
![image](https://user-images.githubusercontent.com/12508157/111343514-c9393100-867b-11eb-99dc-9e9a13acd399.png)

I also opened the 22023 port in the firewall.
![image](https://user-images.githubusercontent.com/12508157/111343436-b7578e00-867b-11eb-92a3-38515ae65c26.png)

Even after that, it doesn't work.

Do you have any idea about what I did wrong ? Is it a bug maybe ?

Best regards,

**Comment by lerichardson** [comment]
Are you using a domain name to connect to the server? If so, is the domain a reverse proxy? (Reverse proxies and game servers almost never work)

**Comment by MatuxGG** [comment]
In Unify, only the ip is used to connect.
To access the server myself, I use the domain name matux.fr. There is no reverse proxy setup right now I think

**Comment by DaemonBeast** [comment]
It might be possible that Unify isn't functioning properly. I'll look into the mod to ensure it's working as expected.

**Comment by DaemonBeast** [comment]
@MatuxGG I was able to connect to my Raspberry Pi (32-bit ARM Linux) running Impostor 1.3.0 150 completely fine using Unify. It seems to be an issue with the server you are hosting.

**Comment by MatuxGG** [comment]
I managed to fix this issue, thanks for your help :)
