### ISSUE TITLE
Problems running plugins

### ISSUE THREAD

**Issue by 201508876PMH** [Impostor/Impostor#356]
Having complete success running and connecting to the imposter server 👍 . However, i'm having problems running and installing mods. How would i go about doing this?

As an example, i've tried downloading the 'Town Of Imposters' mod from curseforge (https://www.curseforge.com/among-us/all-mods/town-of-impostors) - Game Version: 2021.3.5s. I've dragged the contents into the Plugins folder on the vm hosting the server, but it starts up without loading the mods. Any help would be appreciated.

**Comment by js6pak** [comment]
Mod you linked is a client side mod, not server side plugin.

**Comment by 201508876PMH** [comment]
How would i go about installing it client side?

**Comment by dimaguy** [comment]
Following the mod's instructions, not our problem

**Comment by js6pak** [comment]
There is installation guide in the page you linked

**Comment by 201508876PMH** [comment]
I had hoped i could get it working with the imposter client

**Comment by dimaguy** [comment]
There is no such thing as impost*o*r client, theres a server ip patcher

**Comment by 201508876PMH** [comment]
For the sever side plugins. What plugins would be available?

**Comment by 201508876PMH** [comment]
> 
> 
> There is no such thing as impost_o_r client, theres a server ip patcher

Ah ok, makes sense

**Comment by dimaguy** [comment]
> For the sever side plugins. What plugins would be available?

Available on the discord server, pinned in #support

**Comment by 201508876PMH** [comment]
You have a link for that?

**Comment by dimaguy** [comment]
https://discord.gg/DhmbkKAnsz

**Comment by 201508876PMH** [comment]
Thanks!
