### ISSUE TITLE
Docker file does not work on Linux server

### ISSUE THREAD

**Issue by Giganox** [Impostor/Impostor#357]
The 1.3.0 nightly build of the Docker file deos not work properly on Linux servers.
Error message when trying to connect:
"You are using an older version of the game.
Please update to play with others."

The same Docker file works on a Windows machine.

Manually installing the latest dev build on the Linux server resolved the issue.

**Comment by js6pak** [comment]
Can you post the logs of the server running in docker on linux?
Also pretty sure you actually are running linux docker on windows when using linux images.
And its probably old version is just cached so update it with `docker pull aeonlucid/impostor:nightly`
