### ISSUE TITLE
If bhd

### ISSUE THREAD

**Issue by efraimefraty** [Impostor/Impostor#359]
# Bug Report

## Base Information
- Operating System
- Impostor Version
- Among Us Version

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Enter Symptoms on this line.

## Reproduction

Enter reproductions steps here.

**Comment by dimaguy** [comment]
This is just a template

**Comment by efraimefraty** [comment]
Ok

**Comment by efraimefraty** [comment]
Gh

**Comment by efraimefraty** [comment]
efraim

**Comment by efraimefraty** [comment]
Good

**Comment by efraimefraty** [comment]
Hdgfd

**Comment by dimaguy** [comment]
Are you having a stroke

**Comment by efraimefraty** [comment]
UfuducjdhdYdjfdyh

**Comment by Mm2PL** [comment]
you okay there?

**Comment by efraimefraty** [comment]
359#

**Comment by efraimefraty** [comment]
Ryetutirethcftycgcghxhgfhfyc gh c hi

**Comment by efraimefraty** [comment]
Do vkxf
