### ISSUE TITLE
Doesn't work with TheOtherRoles mod

### ISSUE THREAD

**Issue by Saars1337** [Impostor/Impostor#362]
# Bug Report

## Base Information
- Operating System
- Impostor Version 1.3.0
- Among Us Version: v2021.3.5s - TheOtherRoles v1.7

## I confirm:
- [x] that I have searched for an existing bug report for this issue.
yes

## Symptoms 

Players can join server but when starting the game all players get kicked for cheating

## Reproduction

Run Among Us, with mod The Other Roles

**Comment by dimaguy** [comment]
We dont support mods

**Comment by Saars1337** [comment]
> We dont support mods

I know, but is there a reason that the anti-cheat can't be disabled?

**Comment by dimaguy** [comment]
> 
> 
> > We dont support mods
> 
> I know, but is there a reason that the anti-cheat can't be disabled?

It can be disabled, on config.json
https://github.com/Impostor/Impostor/blob/master/src/Impostor.Server/config-full.json

**Comment by js6pak** [comment]
Mods are not supported. If you have any problems, report it to the mod author.
Anticheat can be disabled (https://github.com/Impostor/Impostor/blob/master/docs/Server-configuration.md#anticheat), keep in mind you still could have problems, as state will be incorrect.

**Comment by Saars1337** [comment]
Legends... thanks guys
Silly question... but how can I do this from Docker? Is there a ENV variable?
