### ISSUE TITLE
Imposter v1.3.0-ci.129, with Among Us v2021.3.5s - "You are running an older version of the game"

### ISSUE THREAD

**Issue by bjarne** [Impostor/Impostor#364]
# Bug Report

## Base Information
- Operating System: Windows 10 Pro Insider Preview
- Impostor Version: v1.3.0-ci.129
- Among Us Version: v2021.3.5s

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

When I try to host/ create a game, I got an error that "You are running an older version of the game. Please update to play with others"

## Reproduction

Run windows binary build v1.3.0-ci.129 of Imposter server with public IP on 127.0.0.1
Run Impostor-Patcher_1.3.0-ci.129_win-x64  pointing to 127.0.0.1
Run Among Us from Steam, click "Online", click "Create Game", "confirm"

**Comment by js6pak** [comment]
2021.3.5 support was added in build 149, just update your server

**Comment by bjarne** [comment]
ah...I missed that. Thanks.
