### ISSUE TITLE
I can't play with mobile friend

### ISSUE THREAD

**Issue by Pietrodjaowjao** [Impostor/Impostor#365]
How i play with mobile players, and this is possible right now?

**Comment by js6pak** [comment]
It is possible, just follow instructions at https://impostor.github.io/Impostor/

**Comment by Pietrodjaowjao** [comment]
I already tried this but it didn't work could this be a problem on my ip or on the activated firewall?

**Comment by HelpfulStranger999** [comment]
Are you hosting this on your computer with the other player on another network? If so, you need to make sure you have port forwarded the proper ports on your router and that the ports are open on the firewall.

**Comment by Pietrodjaowjao** [comment]
> Você está hospedando isso no seu computador com o outro jogador em outra rede? Nesse caso, você precisa se certificar de que encaminhou as portas adequadas em seu roteador e que as portas estão abertas no firewall.

I did everything right the doors everything I saw a complete tutorial but I can only play with devices close to my house I really don't know how to solve it if my english is wrong is because i'm using google translator

**Comment by js6pak** [comment]
Anyways, you can play with mobile on impostor, so closing the issue.
If you need support, join the [discord](https://discord.gg/Mk3w6Tb)
