### ISSUE TITLE
Support for v2021.3.31s

### ISSUE THREAD

**Issue by TheChilliPL** [Impostor/Impostor#368]
# Feature Request

## Feature Information:

It'd be great to support the currently newest version (v2021.3.31s) together with the new Airship map

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by DaemonBeast** [comment]
A bit quick aren't you? 😂

**Comment by JABirchall** [comment]
Better early then never

**Comment by SandeQ** [comment]
DIY

**Comment by FreshImmuc** [comment]
Yes, Please add that! Normal Among US servers are overloaded.

**Comment by dimaguy** [comment]
You guys underestimate the work needed to allow a new version with this amount of changes.

**Comment by FreshImmuc** [comment]
Yes. I understand that. Just wanted to say that I also want this feature! When do u think its implemented?

**Comment by FreshImmuc** [comment]
Also, I found this [CrowdedMods/CustomServersClient](https://github.com/CrowdedMods/CustomServersClient) and I wanted to ask, what the differences are?

**Comment by dimaguy** [comment]
ETA is unknown. Remember this is free work and it comes out whenever it comes out

**Comment by dimaguy** [comment]
> 
> 
> Also, I found this [CrowdedMods/CustomServersClient](https://github.com/CrowdedMods/CustomServersClient) and I wanted to ask, what the differences are?

Thats an alternative to the patcher, just that

**Comment by FreshImmuc** [comment]
So it basically does the same thing?

**Comment by dimaguy** [comment]
Yup

**Comment by FreshImmuc** [comment]
K and another question. What if a new version of this here comes out? Will it update automatically?

**Comment by dimaguy** [comment]
No, youll have to replace the binary files manually. you should have nothing to worry about if you point your containers to the same mounts

**Comment by FreshImmuc** [comment]
So what does that mean? xd mabe you could add a Wiki for how to update it? haha

**Comment by dimaguy** [comment]
Basically copy paste the new version files (except the config.json) on top of the old ones. This does not need a wiki

**Comment by FreshImmuc** [comment]
Server or client?

**Comment by dimaguy** [comment]
Depends, what is being updated? You might find an answer if you figure out this question

**Comment by dimaguy** [comment]
Tip: it is not both

**Comment by realfaceitkantesilvestrs** [comment]
@FreshImmuc stick to the original ticket subject, for discussion go to discord server.

**Comment by FreshImmuc** [comment]
Yes. Sorry haha

**Comment by FreshImmuc** [comment]
Can u send me a Discord Invite?

**Comment by realfaceitkantesilvestrs** [comment]
@FreshImmuc  https://github.com/Impostor/Impostor/blob/master/README.md

**Comment by FreshImmuc** [comment]
k, saw it

**Comment by ToxicToast** [comment]
Anyways and maybe an out of topic comment, but what is neccessary - codewise- in order to update to the newest version?
as far as i know it isnt just update the GameVersion in the ClientManager right?

**Comment by dimaguy** [comment]
> Anyways and maybe an out of topic comment, but what is neccessary - codewise- in order to update to the newest version?
> as far as i know it isnt just update the GameVersion in the ClientManager right?

You forget that this new version includes a new map, compatibility needs to be added
