### ISSUE TITLE
Remove Version from Filename

### ISSUE THREAD

**Issue by gOOvER** [Impostor/Impostor#374]
# Feature Request

## Feature Information:
You add the Version in the Filename, whats not needed. You allready have the tag

https://github.com/Impostor/Impostor/releases/download/v1.2.2/Impostor-Server_1.2.2_linux-x64.tar.gz

So its not really possilbe to do an automated Serverinstall.
Please remove 1.2.2 from Filename

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
Not necessary, you can still automate with it. Look into wildcards.

**Comment by gOOvER** [comment]
> Not necessary, you can still automate with it. Look into wildcards.

Thats not only done with an Wildcard. You have a lot of different assets and a simple "*" dont work. But i bet, you know this.

so why you dont follow normal Release Rules and release all assets without Versionnumber

**Comment by AeonLucid** [comment]
Yes you are not supposed to use wildcards in http. If you want to automate you should write a small script that finds the latest release and the archive of the OS you need.
