### ISSUE TITLE
Modded Handshake

### ISSUE THREAD

**Issue by MrF1uff** [Impostor/Impostor#378]
Custom mods no longer respond to modded handshake for private server

**Comment by JohnTranQUT** [comment]
I noticed that the entire Reactor modding setup was pulled from the https://github.com/Impostor/Impostor/tree/airship in one of it's commitment.

Believe it takes a bit of time to work on it's compatibility with the current version. Believe there is more work towards it's stability and coding structure before the coders are working on compatibility with the Mods again.

**Comment by js6pak** [comment]
Functionality for this was implemented in ce62815dc5990a89b7ff47d817e4ed6c528b4cf1
Actual modded handshake was moved from base to https://github.com/NuclearPowered/Reactor.Impostor
