### ISSUE TITLE
Migrate Appveyor/Cake implementation to a GitHub Actions pipeline

### ISSUE THREAD

**Issue by aleks-ivanov** [Impostor/Impostor#384]
Migrate the current CI/CD implementation to a GitHub Actions pipeline for all the required automated processes.

We can start working on this promptly, just please let us know if you are interested in the implementation of the idea 🙂

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by AeonLucid** [comment]
No thank you, please stop advertising your stuff in our issue's and pull requests.
GitHub actions does not suit our usecase at the moment.
