### ISSUE TITLE
I got kicked from the room when trying to create a game

### ISSUE THREAD

**Issue by MatuxGG** [Impostor/Impostor#386]
# Bug Report

## Base Information
- Operating System : Centos 8 for server, client on Windows 10
- Impostor Version : Latest of Airship branch, manually built
- Among Us Version : Latest, 3.31.3s

## I confirm:
- [ x ] that I have searched for an existing bug report for this issue.

## Symptoms 

When I try to create a game on an Impostor server made by building the airship branch, I have this error on client side :

![image](https://user-images.githubusercontent.com/12508157/114279944-5bdcae00-9a37-11eb-92fa-627c84a1e4f5.png)

As well, there is this log message in Impostor's logs :

![image](https://user-images.githubusercontent.com/12508157/114279971-6eef7e00-9a37-11eb-9d85-55a7d336e235.png)

Enter Symptoms on this line.

## Reproduction

On client side, you can :
- use Mod Manager (see my github) and install Unify & Crowded mod
- Install Unify & Crowded mod (build it from airship branch)

On server side, you have to build Impostor, airship branch.

Then, use Unify to connect to the server that you set up and try to create a game.

**Comment by DaemonBeast** [comment]
It turns out is was due to some small reckless code in my Unify mod.

Whoops 😅.
