### ISSUE TITLE
Impostor Patcher doesn't update region name

### ISSUE THREAD

**Issue by JohnTranQUT** [Impostor/Impostor#390]
# Bug Report

## Base Information
- Windows/PC
- Impostor 1.4
- Among Us Version Version release approximately on 2021 04 14

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 
The patcher for Windows/PC writes out a region.dat file. However it doe not do the changes such that the in game Region into **__Impostor__**.

Despite that, Among Us client still able to connect to the designated Impostor server.

### Noteworthy changes
The Among Us client software remodifies region.json. Appears to appended the newly added details onto the ed

## Reproduction

1. Download/Compile latest branch
2. Run impostor.exe
3. Enter hostname/IP and hit save.
4. Open Among Us
5. Incorrect Region name but still able to host/join lobbies on the private server saved in step 3.

**Comment by js6pak** [comment]
Its a game client bug that already has been reported.
