### ISSUE TITLE
docker hub image

### ISSUE THREAD

**Issue by blackb0ld** [Impostor/Impostor#392]
It looks like the aeonlucid/impostor:nightly image on hub.docker.com still runs the version 1.3.0

Is there already a update scheduled ? because i saw that an update was made 2 days ago. 

thanks in advance

**Comment by js6pak** [comment]
`aeonlucid/impostor:latest` is currently 1.3.0 release
`aeonlucid/impostor:nightly` is pushed by github actions from `master` branch, it should always be up to date

**Comment by blackb0ld** [comment]
ah layer 8 error - we did not delete the image from the local images - so i close this one
