### ISSUE TITLE
Not reading config.json right

### ISSUE THREAD

**Issue by DarkPhily** [Impostor/Impostor#393]
It seems like that the newest build isn't reading the config file. I changed the PublicIP to the one of my server. The netstat -tulpn command and the journallog still say it would be 127.0.0.1.
![wrongIP](https://user-images.githubusercontent.com/14162738/115114370-35ff5e00-9f8f-11eb-8c0a-d0b7e1a70f40.PNG)

**Comment by js6pak** [comment]
Make sure to set your systemd service `WorkingDirectory` to place where your config is

**Comment by DarkPhily** [comment]
Thank you.

For some reason it worked fine with an ealier release of your mod.
