### ISSUE TITLE
How to see the clear Server API requests and response? 

### ISSUE THREAD

**Issue by Lucaffo** [Impostor/Impostor#394]
I want ask if there some way out there to read the API docs with requests and response?

In short, i had to do a school project for a game dev class and reimplement Among us. I would like to study the base code for the server side, but i'm unable to read it the API.

**Comment by miniduikboot** [comment]
Hi there, although we have an implementation of the game protocol that is able to relay Among Us games, we don't have documentation for the entire protocol. You could take a look around the Impostor.Server code which is available in this Github repository. Note that the Impostor.Api package contains the API for impostor plugins which is probably not directly useful for you, but they may lead you to the place where that packet is received by Impostor.Server.

**Comment by miniduikboot** [comment]
A resource like https://github.com/codyphobe/among-us-protocol or https://github.com/cybershard/wireshark-amongus may help you better when you want a more global overview of the protocol, although the latter is slightly outdated at this point
