### ISSUE TITLE
How to use the debug feature

### ISSUE THREAD

**Issue by DarkPhily** [Impostor/Impostor#396]
Good day,

I had some hiccups with the Server I host. It happend from time to time that the server freezed in a meeting. To investigate the problem I wanted to use the debugger. I configured it right and got a .dat file, but when I open it with a text editor there are symbols that it can't show properly. Is that intended? Am I using the wrong programm to open the file?
![debug-file](https://user-images.githubusercontent.com/14162738/115153705-a5e91380-a077-11eb-9623-d42ffe55a55a.PNG)

**Comment by miniduikboot** [comment]
Hi there,

First up, we're not aware of a bug that freezes the server while in a meeting and I personally haven't encountered it yet. If you have clear reproduction steps for this issue, feel free to create a bug report for them.

WIth respect to debugging: I believe you're using the wrong tool here. I don't know how you generated that .dat file. Your favorite C# IDE should have debugging options available that allow for stepwise debugging, but I'm not sure if that's of use as that'll will likely disconnect all clients

**Comment by DarkPhily** [comment]
Hey,

I can't reproduce it consistantly. I try to get as much information as i can and let you know what maybe causing it. It very well could be an issue with the 'OtherRoles - Mod' that's causing the freeze.

The .dat file got generated by your debug option:
```{
  "Server": {
    "PublicIp": "127.0.0.1",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "Enabled": false,
    "BanIpFromGame": false
  },
  "Debug": {
    "GameRecorderEnabled": true,
    "GameRecorderPath": "/root/Impostor-Server/debug"
  }
}
```
Am I using this feature wrong? I thought that it would give me an indepth debug log.

**Comment by js6pak** [comment]
Debug game recorder is not meant for public use, its for development only.
Mods are not supported, and if its client side freeze, its probably caused by them.
If you get this issue again on vanilla client, make an issue with reproducible steps.
