### ISSUE TITLE
Chinese characters in username are rejected by Impostor server

### ISSUE THREAD

**Issue by linepro6** [Impostor/Impostor#403]
Good days,
Please allow Chinese characters in username. The official server has allowed.
Thanks a lot!
https://github.com/Impostor/Impostor/blob/901deeff5919c9d23fb344ca950a69c917c3b291/src/Impostor.Api/Innersloth/TextBox.cs#L5-L8

**Comment by Mondanzo** [comment]
Maybe change the issue title from "Disallow Chinese characters in username" to "Allow Chinese characters in username". Otherwise your issue title and your issue description describe the complete opposite.

**Comment by linepro6** [comment]
> Maybe change the issue title from "Disallow Chinese characters in username" to "Allow Chinese characters in username". Otherwise your issue title and your issue description describe the complete opposite.

I think the title of an issue should describe the problem so I use "disallow". LOL

**Comment by miniduikboot** [comment]
Hmm, I missed that change in the changelog.

Are there still limits on the allowed characters in nicknames or can you also use emojis in nicknames?

**Comment by linepro6** [comment]
> Hmm, I missed that change in the changelog.
> 
> Are there still limits on the allowed characters in nicknames or can you also use emojis in nicknames?

Emojis are not allowed by the input control of the nickname in game. I tried Chinese and Japanese characters and they are all rejected by Impostor server (nightly version in Dockerhub). It shows that "Your username contains illegal characters, please remove them".

**Comment by miniduikboot** [comment]
I'm not that familiar with CJK characters, I'll look at it later and see which ranges are accepted by AU. If the standard Among Us servers accepts these nicknames you can send in a PR that fixes it if you want.

**Comment by js6pak** [comment]
Since TMP update (2021.4.12) textboxes and player names can render (basically) all characters.
Only limit on player names is on server side now (textbox has it aswell but seems like it allows much more than official servers, for example some invisible characters), we'd have to make allowed list ourselves ig

**Comment by itsTyrion** [comment]
> Since TMP update (2021.4.12) textboxes and player names can render (basically) all characters.

 TMP update?

**Comment by Seba10** [comment]
> > Since TMP update (2021.4.12) textboxes and player names can render (basically) all characters.
> 
> TMP update?

I believe they’re referring to TextMeshPro a unity package
