### ISSUE TITLE
IGamePlayerLeftEvent not triggered

### ISSUE THREAD

**Issue by MatuxGG** [Impostor/Impostor#405]
Hello,

In the particular case of the last player of a game leaving it, the event IGamePlayerLeftEvent  is not triggered.
I also tried to use the event IGameDestroyedEvent but it is not triggered either.

Am I missing something ?

Thanks in advance !

**Comment by js6pak** [comment]
Are you sure you can reproduce this on vanilla client on master branch?

**Comment by MatuxGG** [comment]
I'm using Impostor v1.4.0 build

**Comment by js6pak** [comment]
You are not using 1.4.0 build, as it doesn't exist yet. You are probably referring to CI builds of master, if so please provide exact build number

**Comment by MatuxGG** [comment]
You're absolutely right. The build used is Impostor-Server_1.4.0-ci.184_linux-x64.tar.gz
