### ISSUE TITLE
Update the nuget package

### ISSUE THREAD

**Issue by Peasplayer** [Impostor/Impostor#407]
Hi,
Could you please update the nuget package of the api?

**Comment by danielklessa** [comment]
+1

Would like to use some of the new events.

**Comment by Peasplayer** [comment]
Yes

**Comment by js6pak** [comment]
From now on I'm going to deploy nugets as soon as api is changed, so there it is https://www.nuget.org/packages/Impostor.Api/1.4.0-ci.193

**Comment by Peasplayer** [comment]
Thank you!
