### ISSUE TITLE
Specify LogLevel in Config

### ISSUE THREAD

**Issue by CyreX541** [Impostor/Impostor#409]
# Feature Request

Set LogLevel in Server Config File and / or Docker Environment Variables

## Feature Information:

Trimming Output at Console by specifying some kind of LogLevel could be useful.

LogLevel for Instance.
- Debug: Print as many Infos as collected to the console and / or LogFile
- Info: Print less Info than Debug Level but still with useful Info
- Warning: Print less Info than Info Level to console
- Error: Just print Error Messages to Console e.g. Config Error at Server side

## I confirm:
- [x ] that I have searched for an existing feature request matching the description.

**Comment by js6pak** [comment]
You already kinda can do that, if you use debug build loglevel is Debug, if release then Information, if you use --verbose or --errors-only as command line argument its going to be Verbose or Error respectively.

**Comment by iwa** [comment]
would be great to be able to disable anticheat logs, cause even if you disable the anticheat, it stills show up warnings in console and it spams a lot when playing with modded client (cf. screenshot) ://
![Screen Shot 2021-11-16 at 22 10 36](https://user-images.githubusercontent.com/19956672/142066261-27e250b2-7fdd-4b80-be5c-015adc3dd3fb.png)
