### ISSUE TITLE
Tickrate configuration

### ISSUE THREAD

**Issue by ostamour** [Impostor/Impostor#418]
# Feature Request

## Feature Information:
Hi,

First I would like to say thank you for this implementation, our group of friends have been using this server and were very happy with the result compared to the official servers.

One thing we wanted to do was to host this server with a higher tick rate than the default. From tests ran using Wireshark, I believe the default tick rate we saw was around 8 updates per second. I tried to find a way to increase it to 64, either in the code or with some configuration options but that was not obvious to me. If you know of a way to do this, please let me know! Otherwise, this would be a nice feature to add.

Thank you,
Olivier

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
This is handled client side.

**Comment by danbudworthmead** [comment]
Lmao who the fuck needs a 64 tick among us server?  🤣
