### ISSUE TITLE
Impostor server application won't open

### ISSUE THREAD

**Issue by MiggyXyz** [Impostor/Impostor#420]
I'm struggling on how to open the impostor server application, I have the api-ms-win-crt-runtime-l1-1-0.dll and Microsoft Visual C++ 2015 Redistributable. but it wont open even I open it with admin privilages, is there someone that can solve the issue?, a big thanks to those who answer my question

**Comment by js6pak** [comment]
Assuming you are on windows, can you try launching the server using `run.bat` which should be included with zip you downloaded?

**Comment by MiggyXyz** [comment]
[image: as.png]
this is always the result.. I am sorry for the late reply

**Comment by js6pak** [comment]
I don't think image quite worked, my tip is never use github via email, can you try with github website/app?

**Comment by MiggyXyz** [comment]
well I'll try it, and what do you mean by "never use github via email?

**Comment by miniduikboot** [comment]
Hi Miggy,

If you look at the github issue you see that picture you wanted to share rendered itself as the following piece of text: `[image: as.png]`. If you wanted to send an actual picture, please try again in a different way.

if you want support with Impostor, I recommend joining our Discord: https://discord.gg/Mk3w6Tb

**Comment by js6pak** [comment]
Join https://discord.gg/Mk3w6Tb for support
