### ISSUE TITLE
Push latest to Docker?

### ISSUE THREAD

**Issue by 1upCAD** [Impostor/Impostor#424]
The latest version in Docker is 1.3 and Nightly is 1.4.

It looks like 1.5 is available here:
https://ci.appveyor.com/project/Impostor/Impostor/build/artifacts

I tested 1.5 Windows version and it works but I want to implement using Docker on my Linux server.

I'm not sure how easy that is but would greatly appreciate an update push.

Thank you for your work on this.

**Comment by js6pak** [comment]
1.5.0 you linked is a PR (#423), its going to be on docker nightly once its merged.
