### ISSUE TITLE
Server doesn't start on public ip address

### ISSUE THREAD

**Issue by netzpixel** [Impostor/Impostor#426]
# Bug Report

## Base Information
- Operating System
macOS 11.4
- Impostor Version
v1.5.0-ci.197
- Among Us Version
v2021.6.15s

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 

No matter what I configure in the config.json the server always listens on 127.0.0.1
```
[22:57:10 INF] Starting Impostor v1.5.0-ci.197
[22:57:19 INF] Matchmaker is listening on 127.0.0.1:22023, the public server ip is 127.0.0.1:22023.
[22:57:19 INF] Announcements server is listening on 0.0.0.0:22024
[22:57:19 INF] Loading plugins.
[22:57:19 INF] Loaded 0 plugins.
[22:57:19 INF] Application started. Press Ctrl+C to shut down.
[22:57:19 INF] Hosting environment: Production
```

## Reproduction

Download Impostor-Server_1.5.0-ci.197_osx-x64.tar.gz, unzip, enter public ip in config.json (I tried the actual ip and dynDNS) and start the server in terminal.

**Comment by netzpixel** [comment]
I just tried to do the same thing on linux and it works right away...

**Comment by miniduikboot** [comment]
Huh, that's weird. Are you using the same config.json file on both platforms? You should put in the public ip, not a domain name.

Unfortunately I don't have a Mac available, so I can't really dig deeper into this problem.

**Comment by netzpixel** [comment]
Yep, both the same. But it works on Linux, so If you want to you can close the ticket…

Am 03.07.2021 um 14:31 schrieb miniduikboot ***@***.***>:

﻿

Huh, that's weird. Are you using the same config.json file on both platforms? You should put in the public ip, not a domain name.

Unfortunately I don't have a Mac available, so I can't really dig deeper into this problem.

**Comment by js6pak** [comment]
Are you sure you editied correct config file? Sounds like changes are not applying at all. I 
don't ha

**Comment by netzpixel** [comment]
Yes I’m sure. Since there is only one config file.

Am 05.07.2021 um 21:15 schrieb js6pak ***@***.***>:

﻿

Are you sure you editied correct config file? Sounds like changes are not applying at all.

**Comment by Thiladon** [comment]
I had the same problem and fix it this way : 

I check in the config file for the client side, and located an error generated by the API given from https://impostor.github.io/Impostor/

In your line, you should have the "Port" attribute with the number 22023 in it, but written like that : `"Port" : "22023"`
Change it to : `"Port" : 22023`

Be sure to do it while the game is shutdown.
When done, start the game, and also, check if yourserver terminal is not frozen, if so just unfreeze it by pressing space while on the cmd terminal.

Then try to host a game, u should be able to normally.

Have fun, Thilladon :)

**Comment by nathan130200** [comment]
For public IP you should use `0.0.0.0` (that means listen in all adapters) not `127.0.0.1` (local host ONLY)

**Comment by miniduikboot** [comment]
Issue is stale. If you still have issues with Impostor, please visit the Impostor Discord
