### ISSUE TITLE
Plugin system ideas / expections

### ISSUE THREAD

**Issue by AeonLucid** [Impostor/Impostor#43]
The plan is to create a plugin system for Impostor, allowing you to create plugins such as:
- Auto mute on discord
- Custom gamemodes (i.e. hide and seek)

You will need to create a C# project (.NET 5 library) and reference the Impostor library. The resulting `.dll` can be placed in a `plugins` directory with optionally a directory for the plugin where configs or other data can be stored.

Any ideas / wishes you might have regarding the plugin system can be posted in this issue.

**Comment by GerardSmit** [comment]
We'll need to disable `PublishTrimmed` so plugins don't get the issue that methods / assemblies are being trimmed that they want to use.

**Comment by js6pak** [comment]
Simple and cool events based on attributes, i.e.
```cs
[Plugin] // info about plugin should be gathered from assembly attributes :)
public class TestPlugin
{
	public TestPlugin([Inject] EventManager eventManager) // Dependency injection on constructor and properties?
	{
		eventManager.Subscribe(this);
	}

	[EventHandler]
	public void OnPlayerConnect(PlayerConnectEvent @event)
	{
		this.Logger.LogInfo(@event.Player.Name); // Microsoft.Extensions.Logging?
	}
}
```

I guess I just like reflection

**Comment by AeonLucid** [comment]
@GerardSmit I want to put the plugin API stuff in a separate library so it can just be disabled in there. I believe it is also possible to exclude stuff from trimming with annotations but I can't find where I read that anymore.

**Comment by BrightSkyz** [comment]
I would like to see a way to get low level packet data for if something isn't implemented yet or you just need it. Also, I would like to see a way to cancel relaying the packet to the other players.

**Comment by Mm2PL** [comment]
I would like to have a simple enough API for high level things, like chat, maybe commands. IMO it would be nice if plugins could change properties of players and Games directly. A good example to use here is a plugin that would change the number of impostors or the current map, which should technically be possible AFAIK, but isn't in the game probably due to searching for public lobbies. IMO Enabling things that aren't possible with the client's UI is a good use of commands.

**Comment by roobscoob** [comment]
This is awesome! I'm looking for access to to events such as
```
Functions:
 - Create Game
 - Destroy Game

Events:
 - Game Start
 - On Meeting Start
 - On Meeting end

Live Data:
 - Connected Players
 - States of connected players (Name / Color / Hat / Position / Is Dead, etc.)
```

**Comment by HolyStephano** [comment]
> This is awesome! I'm looking for access to to events such as
> 
> ```
> Functions:
>  - Create Game
>  - Destroy Game
> 
> Events:
>  - Game Start
>  - On Meeting Start
>  - On Meeting end
> 
> Live Data:
>  - Connected Players
>  - States of connected players (Name / Color / Hat / Position / Is Dead, etc.)
> ```

In terms of the live data, i think it would be better suited to effectively just serve those as events. Connected players? Just log all players who connect with an event callback. States of them? In theory, I would want to have them as an object to manipulate, or at the very least for querying info about them, and having a "playerUpdate" callback that receives the new updated player object whenever something happens to them.

**Comment by roobscoob** [comment]
I would like to have a WebSocket or TCP connection to Imposter, that way it can be interfaced with any language or multiple programs at once.

**Comment by js6pak** [comment]
> I would like to have a WebSocket or TCP connection to Imposter, that way it can be interfaced with any language or multiple programs at once.

Thats plugin territory

**Comment by maks100** [comment]
Hi could anybode help me in code in which place it is crearly seen that meeting has started? (I wanna make discrod mute functionality...)

**Comment by fredthedoggy** [comment]
1 Suggestion that I talked with AeonLucid about on discord, is a way to cancel events.
This way I could cancel a meeting event if I wanted to, or cancel a message from being sent to everyone (Custom Filters/Chat)
This would not remove the action on the users-end, but would cancel it for everyone else (but canceling a meeting would have to cancel it for everyone).

**Comment by Trolldemorted** [comment]
Registering to all kind of events (movement, kill, vent usage, object usage) would be awesome, I'd like to create [heatmaps like wot has](https://static.armorinspector.com/heatmaps/pc/final/1566380705/hm-12-0-dm-vPFg.png).

**Comment by DiamondDagger590** [comment]
Currently working on a system for decoding packets to turn these into events. Current project is the settings change packet and I plan to hook that into an event. I also have a semi functional PlayerJoinGame event with cancellable status, however it doesn't cleanly kick the player so there needs to be further modifications to make that work

**Comment by real2two** [comment]
> This is awesome! I'm looking for access to to events such as
> 
> ```
> Functions:
>  - Create Game
>  - Destroy Game
> 
> Events:
>  - Game Start
>  - On Meeting Start
>  - On Meeting end
> 
> Live Data:
>  - Connected Players
>  - States of connected players (Name / Color / Hat / Position / Is Dead, etc.)
> ```

maybe "On connect", "On join" and "On disconnect" if not already.

"on connect" would be while joining. (possibly cancellation of kicking the player even if the max players is already greater than 10)
"on join" would be if you successfully join the game (like the player successfully joins without any errors like there is already max players in the game).
"on disconnect"... well if you disconnect from the game.

**Comment by real2two** [comment]
If anyone actually is going to make plugins here, here's suggestions:
- Chat moderation plugin.
- Anticheat.
- Spectator (not you being a ghost... a spectator).
- Better chatting. (possibly make a "/imposchat" as an addition for chatting)

**Comment by Gideon357** [comment]
What about using another scripting language for extensions. Also are extensions server or client?

**Comment by AeonLucid** [comment]
The initial beta api is now out, please see https://github.com/Impostor/Impostor/blob/dev/docs/Writing-a-plugin.md and use the issues on the bottom for future discussion.
