### ISSUE TITLE
Connect to 2020.9.22 servers

### ISSUE THREAD

**Issue by E4zily** [Impostor/Impostor#437]
# Feature Request

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

https://impostor.github.io/Impostor/ only works for newer versions, but 2020.9.22 and others use 
regionInfo.dat that has content like this:
`    Europe172.105.251.170   Europe-Master-1¬iыЄV    `

is there a way to connect to 2020.9.22 Impostor servers?

**Comment by miniduikboot** [comment]
Thta's an old version and no longer officially supported by the Impostor team.

If you still want to connect, try one of the following:

1. I've placed a copy of the old impostor site on my website which you could use: https://duikbo.at/impostor-region-generator/2020.12.9/
2. In case you're reading this in the future and I broke my copy, create a local checkout of this commit and open index.html in the browser: https://github.com/Impostor/Impostor/tree/7e9960b865fc7c6cc11b63f8633d62b862557fd2
