### ISSUE TITLE
How to compile for Windows 32 Bit?

### ISSUE THREAD

**Issue by eyadtamer2121** [Impostor/Impostor#441]
I want to know how to compile a version of Impostor to a Windows 32 Bit or someone compile it for me.
I have already found something like this issue but it was about Ubuntu.
Please help me!

**Comment by miniduikboot** [comment]
Hi there, unfortunately nobody in the development team still has a 32-bit Windows install, so we cannot support Impostor on such systems.

That being said, you can try following the [normal compilation instructions](https://github.com/Impostor/Impostor/blob/master/docs/Building-from-source.md) and changing `linux-x64` into `win-x86`.

We have no clue if it works, so you're on your own here. We recommend either moving to a 64-bit Windows system or getting a cheap Linux VPS and installing it there.

**Comment by eyadtamer2121** [comment]
Ok thanks but please when installing vs 2019, what do I have to select in the programming languages?

**Comment by miniduikboot** [comment]
I have not installed VS myself so I don't know how the options are called, but enable everything that states "C#" or ".NET"

**Comment by eyadtamer2121** [comment]
Ok thanks!
