### ISSUE TITLE
您好，请问什么时候更新支持v2021.12.15s的版本？

### ISSUE THREAD

**Issue by SamHuang14** [Impostor/Impostor#448]
Steam上的版本已经更新到v2021.12.15s的版本，我使用这个版本无法连接到您制作的服务器。
当我创建游戏时，提示已经与服务器的链接断开。

Google translate:
Hello, when will the version supporting 2021.12.15s be updated?
The version on steam has been updated to V2021 12.15s. I can't connect to the server you made with this version.
When I create a game, the prompt has been disconnected from the server.

**Comment by miniduikboot** [comment]
The latest build from the master branch works fine and can be downloaded from Appveyor: https://ci.appveyor.com/project/Impostor/Impostor/branch/master/artifacts

**Comment by culion-bear** [comment]
but it can not work successfully
config.json :
`{
  "Server": {
    "PublicIp": "xxxxxxxxxx",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "Enabled": true,
    "BanIpFromGame": true
  }
}`
among us client'log :
"发生未知错误，您与服务器的连接已中断"

**Comment by miniduikboot** [comment]
There are multiple ways that can happen. 

Try to connect to a server running on your local machine first by using your local IP address, 127.0.0.1, in your client. You can create a region file using https://impostor.github.io/Impostor/ . If that works fine and you want to try portforwarding, you can create a new region file using the same method. Normally I'd recommend using https://aucheck.duikbo.at to check if portforwarding works correctly, but I have no clue if that tool works properly in mainland China.

Unfortunately Github isn't a great platform for user support, please check out our FAQ: https://github.com/Impostor/Impostor/blob/master/docs/TROUBLESHOOTING.md or join our Discord if you still have problems: https://discord.gg/Mk3w6Tb . Please include the full server log in your message.

**Comment by wowwm** [comment]
> but it can not work successfully config.json : `{ "Server": { "PublicIp": "xxxxxxxxxx", "PublicPort": 22023, "ListenIp": "0.0.0.0", "ListenPort": 22023 }, "AntiCheat": { "Enabled": true, "BanIpFromGame": true } }` among us client'log : "发生未知错误，您与服务器的连接已中断"

我这里使用游客登录能登录成功，用账号就不行了

**Comment by wowwm** [comment]
> > but it can not work successfully config.json : `{ "Server": { "PublicIp": "xxxxxxxxxx", "PublicPort": 22023, "ListenIp": "0.0.0.0", "ListenPort": 22023 }, "AntiCheat": { "Enabled": true, "BanIpFromGame": true } }` among us client'log : "发生未知错误，您与服务器的连接已中断"
> 
> 我这里使用游客登录能登录成功，用账号就不行了

噢我发现问题出在不可以使用中文名！
Oh I find using English name is ok!
