### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Kanorto** [Impostor/Impostor#449]
Будете ли вы делать команды на сервер impostor? Возможно уже есть команды?
Например сделать команду impostor <nickname> или команду role <nickname> <role>

**Comment by miniduikboot** [comment]
Sorry, please rephrase your question in English, I'm unable to speak Russian

**Comment by Kanorto** [comment]
Will you be making commands to the impostor server? Perhaps there are already commands?

For example, make an impostor command or a role command
