### ISSUE TITLE
Doesn't Appear to work with new update

### ISSUE THREAD

**Issue by sdh91** [Impostor/Impostor#450]
I had this working a while back. I stopped as I was doing some network changes to my environment as I self host a lot and needed to get some firewall protections in place properly. 

Since starting this back my AmongUS has updated to version 2021.12.15s and I can not seem to make a connection with the generic of generic installs. I've tried docker, linux, and windows. Nothing seems to be working. Can anyone confirm that the new update breaks something?

I get a different error other than the reliability one. It says something along the lines of an unexpected error disconnected you from the server.

**Comment by miniduikboot** [comment]
Hi there, which version of Impostor did you use? The version compatible with 2021.12.15 has not yet been released, but you can download developer builds from Appveyor: https://ci.appveyor.com/project/Impostor/Impostor/branch/master/artifacts

If you run into any other issues, please join the [Discord](https://discord.gg/Mk3w6Tb), as that's quicker for tech support

**Comment by sdh91** [comment]
I'm running the nightly version of the docker now. Yes everyone has updated to 2021.12.15 at this point and it basically broke using the private server.
