### ISSUE TITLE
Hosting availability 

### ISSUE THREAD

**Issue by Cat4eve** [Impostor/Impostor#454]
I'd like to use impostor for a project where the among us server must be hosted, is there any suggestions where I can find a free hosting (not trial version) for this c# code? On the other side, is there any js or python version of an impostor?

**Comment by miniduikboot** [comment]
There are a few options here:

- Use someone elses Impostor server: if you don't need to modify the server in any way and just want to play a few games, feel free to use mine: `impostor.duikbo.at`
- If you have a credit card, you can get a free VPS at Google and Oracle Cloud.
- Repl.it, Heroku and co are not supported as they don't handle UDP connections.

Spending a bit of money will make setup a lot easier: I personally use Hetzner Cloud and it's pretty easy to setup if you're familiar with Linux or able to follow the steps in the setup guide. If you sign up using my referral link, you get 20 euros of free credits and once you pay 10 euros, I get a 10 euro discount towards my next bill, which helps me to keep my test server online.

Alternatively you can run Impostor on your local PC and portforward it to the outside world, but that won't be available if you turn off that computer.

Hope this helps you out. If you have more questions, please join the Discord.

**Comment by Cat4eve** [comment]
> There are a few options here:
> 
> * Use someone elses Impostor server: if you don't need to modify the server in any way and just want to play a few games, feel free to use mine: `impostor.duikbo.at`
> * If you have a credit card, you can get a free VPS at Google and Oracle Cloud.
> * Repl.it, Heroku and co are not supported as they don't handle UDP connections.
> 
> Spending a bit of money will make setup a lot easier: I personally use Hetzner Cloud and it's pretty easy to setup if you're familiar with Linux or able to follow the steps in the setup guide. If you sign up using my referral link, you get 20 euros of free credits and once you pay 10 euros, I get a 10 euro discount towards my next bill, which helps me to keep my test server online: https://hetzner.cloud/?ref=mAlO3aA18OBp
> 
> Alternatively you can run Impostor on your local PC and portforward it to the outside world, but that won't be available if you turn off that computer.
> 
> Hope this helps you out. If you have more questions, please join the Discord.

Thanks a lot, especially for such a fast answer. I would like to handle some data relating to the people, connected to the game, player cound during specific time in game, kill counts, ect.

About payment, the problem is that I don't obtain any VISA/MASTER card allowing me to pay for something distantly.

What about hosting on my own pc I know that it's not 24/7 solution but there is an additional problem which is related to the fact that my internet provider has closed users' routers' ports and doesnt allow to open it. IDK whether it's even legal. They advise to buy another router...

**Comment by miniduikboot** [comment]
Your plugin idea sounds possible with features the Impostor API allows.

Not having a credit card does not help you here as most free cloud plans require a card to prevent abuse: blame the individuals who are mining cryptocurrency on free cloud resources. If your ISP blocks port forwarding that doesn't help and I can't recommend a workaround here.

`impostor.duikbo.at` is the address of my test server that people can use to play a game, but it won't be of use if you want to modify the server itself.

**Comment by Cat4eve** [comment]
Sounds like it is the time to get a credit card snd abuse 1 year free vps from google, aws, ect.
