### ISSUE TITLE
[Xbox App] Failed to join game session

### ISSUE THREAD

**Issue by zhzy0077** [Impostor/Impostor#459]
# Bug Report

## Base Information
- Operating System
  Windows 11 Pro 22000.483
- Impostor Version
  master/nightly
- Among Us Version
  2021.12.14m

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 
I'm unable to join a game with error: `Failed to join game session`.
I can see below log in server side: `Server received unknown flag 22`.
I searched the codebase and it looks like this `QueryPlatformIds`.

## Reproduction
1. Open Among Us from Xbox App.
2. Click Online button
3. Click Enter Code under PRIVATE section.
4. Enter an arbitray code and it throws an error after several seconds.

My guess would be it's relating to the version as all of my friends' games using Steam are working well.

**Comment by miniduikboot** [comment]
Hi there, thanks for your bug report. We don't regularly use that version, but we managed to reproduce it. Unfortunately I don't have the time right now to fix it, but we do have a workaround: if you host the game from your Microsoft Store version, other players can join your game.

**Comment by miniduikboot** [comment]
Could you test pull request #460 and tell us if it works for you?

**Comment by zhzy0077** [comment]
@miniduikboot  Thank you. I tested and it's working!
