### ISSUE TITLE
Disable anitcheat check or supress logging of it

### ISSUE THREAD

**Issue by lightsing** [Impostor/Impostor#476]
# Feature Request

disable anitcheat check or supress logging of it.

## Feature Information:
L40 in the following code produces huge amount of logging when playing with mods.
https://github.com/Impostor/Impostor/blob/aeefc40ef1336542750ecf959ca943db6bd16dc1/src/Impostor.Server/Net/Client.cs#L38-L55

Move logging in L40 after checking if anticheat enable can supress the log.

Or, maybe we can kill all anitcheat check if the anticheat is disabled?

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by miniduikboot** [comment]
Fixed by #498
