### ISSUE TITLE
add multiple custom server support in the server installer website

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [Impostor/Impostor#480]
# Feature Request

## I confirm:
- [ X] that I have searched for an existing feature request matching the description.

**Comment by miniduikboot** [comment]
Sorry for the delay in getting back for you. We're not planning to implement this ourself, but feel free to submit a pull request. While for PC it is possible to make one region file with multiple regions, it should be easy to combine the data yourself, so I doubt the feature is used enough to justify the dev time. For mobile the deeplink only allows submitting one server anyway, so it'd be impossible to implement it there.
