### ISSUE TITLE
Can't start server : address already in use

### ISSUE THREAD

**Issue by MatuxGG** [Impostor/Impostor#487]
# Bug Report

## Base Information
- Linux (Centos 7)
- Impostor 1.7.1

## I confirm:
- [ X] that I have searched for an existing bug report for this issue.

## Problem

Hi!

I tried to update an old Impostor server on a Centos 7 server that used to worked.
For that, I updated the server to use dotnet 6 now.
I also downloaded the latest build for linux x64.
However, when I try to start the server, I got the error "System.Net.Sockets.SocketException (98): Address already in use".

![image](https://user-images.githubusercontent.com/12508157/178271995-bcb6c8aa-fe6d-4caa-a507-cbfb3e8f4762.png)

But there is nothing running on this port:

![image](https://user-images.githubusercontent.com/12508157/178272151-2758a5be-ef56-4f88-9b40-c1a89ebc848a.png)

Am i missing something ?

Thanks in advance for your help

**Comment by miniduikboot** [comment]
Sorry for leaving this issue open for so long, Github is not the best channel for support, please visit the Impostor Discord instead
