### ISSUE TITLE
Change the unchangeable via chat commands?

### ISSUE THREAD

**Issue by p0358** [Impostor/Impostor#49]
# Feature Request

## Feature Information:
I would appreciate to see the ability to change a few room settings, namely:
- the map
- the maximum amount of players
- the amount of impostors

To my current knowledge, it is not possible to change those in the stock server without leaving to main menu and recreating the lobby. Which is of course problematic, because we have to distribute the new game code and get all the people to re-join. What I propose is some kind of commands that could be executed in the chat while in lobby (by host only? configurable?), which could let us alter these on-the-fly, in an existing lobby, assuming there isn't any major obstable client-side that would prevent that from being possible.
Not sure if that's something for the core or the incoming plugins system though...

## I confirm:
- [X] that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
Check out the beta branch of the game. It allows you to do some of those things iirc.

**Comment by p0358** [comment]
@AeonLucid Can you show me? I installed the beta and it indeed has a few new cool options, like anonymous voting, but I can't find the option to change any of the mentioned 3 anywhere still sadly :/

**Comment by p0358** [comment]
Apparently maps are changable in local LAN games. Maybe it could be possible to enable some flag to allow it on a server too?

**Comment by Gideon357** [comment]
> Apparently maps are changable in local LAN games. Maybe it could be possible to enable some flag to allow it on a server too?

What do you mean by "flag"?

**Comment by AlgeDoesntGiveHeadLikeWolf** [comment]
this is possible, but afaik only through memory editing in online (map and imposter count, i think that the 10 player limit is hardcoded)

Map (0 = Skeld, 1 = Mira, 2 = Polus, other maps are afaik that what comes near (>2 = polus and minus numbers are probably skeld))
Imposter Count (you wont get over 3 tho, bcs of the Playerlimit system)
Or wait lemme just put all the lobby settings that i know rn (only host editabable, also works on normal servers):
- Map (byte): "GameAssembly.dll"+01468910 + {5C + 4 + 10}
- Impostor Count (int): "GameAssembly.dll"+01468910 + {5C + 4 + 38}
- Player Speed (float): "GameAssembly.dll"+01468910 + {5C + 4 +14}
- Emergency Meeting amount (byte): "GameAssembly.dll"+01468910 + {5C + 4 + 30}
- Emergency Meeting Cooldown (int): "GameAssembly.dll"+01468910 + {5C + 4 +34}
- Discussion Time (int): "GameAssembly.dll"+01468910 + {5C + 4 + 44}
- Player Vote Time (int): "GameAssembly.dll"+01468910 + {5C + 4 +48}
- Crewmate Vision (float):"GameAssembly.dll"+01468910 + {5C + 4 + 1C}
- Impostor Vision (float): "GameAssembly.dll"+01468910 + {5C + 4 + 18}
i have some more but im too busy to copy all of them

**Comment by AeonLucid** [comment]
This is now possible using the plugin api, see https://github.com/Impostor/Impostor/blob/dev/docs/Writing-a-plugin.md.
