### ISSUE TITLE
Only 1 impostor is recognized as an impostor in a game with 2 impostors 

### ISSUE THREAD

**Issue by NotSugden** [Impostor/Impostor#496]
# Bug Report
Only 1 impostor is recognized as an impostor in a game with 2 impostors

## Base Information
- Operating System - Windows 10
- Impostor Version - 1.7.2
- Among Us Version 2022.9.20

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

In a game with two impostors only 1 impostor seems to actually be recognized - observe:
![image](https://user-images.githubusercontent.com/28943913/196783397-66d1335e-0021-4e22-a5e5-f65963476ad1.png)

## Reproduction

```csharp
public void OnGameStarted(IGameStartedEvent evt) {
  var game = evt.Game;
  foreach (var player in game.Players) {
    var character = player.Character.PlayerInfo;
    _logger.LogInformation("{0} IsImpostor = {1}", character.PlayerName, character.IsImpostor);
  }
}
```

**Comment by anthonydesmartin** [comment]
Hey dude, how did you start multiple instance pls?

**Comment by wherget** [comment]
I think this just landed me a disconnect because of 
```
 was caught cheating: [CloseDoorsOfType] Failed impostor check
```
as a second (already ejected) impostor.

**Comment by GD825** [comment]
i cant speak for the devs, but did you disable the anticheat in your  impostor config file?

**Comment by NotSugden** [comment]
in any case the anticheat shouldnt have to be disabled

**Comment by GD825** [comment]
the anticheat is exactly why your having issues.. its acting just like the official servers that will will give you the same exact result.. the modded servers that other mods use , are with anticheat off so their mods work 100% and are playable.. anything that isnt doable in the base game is considered cheating by the anticheat system, thus  it must be turned off  for mods to work correctly.. there is no other option

**Comment by GD825** [comment]
i heard they fixed your issue, you just need to wait for an impostor update

**Comment by miniduikboot** [comment]
OP didn't indicate they were using mods (and I don't see the mod stamp in their screenshot), so in this case the impostor detection should be amended.

If the impostor detection doesn't work properly, the AC may malfunction as wherget reported.

We're investigating the issue and will open a PR when we have found a solution.
