### ISSUE TITLE
when i connect to my server it shows server_didn't_respond_to_modded_handshake

### ISSUE THREAD

**Issue by flagsk** [Impostor/Impostor#497]
when i connect to my server it shows server_didn't_respond_to_modded_handshake
how do i fix it 。is that a server config problem？
server version 1.7.2
client version 2020.8.24s
tou 3.3.2

**Comment by miniduikboot** [comment]
Hi there, to play with mods like ToU you need to install an extra plugin: https://github.com/NuclearPowered/Reactor.Impostor/ . v1.0.0 is recommended for the current version.
