### ISSUE TITLE
You disconnected from the server 

### ISSUE THREAD

**Issue by buhron** [Impostor/Impostor#521]
# Bug Report

## Base Information
- Operating System Android 12
- Impostor Version 1.8.1
- Among Us Version: 2023.3.28

## I confirm:
- [Y ] that I have searched for an existing bug report for this issue.

![Screenshot_20230328-202942](https://user-images.githubusercontent.com/103539649/228396421-d66d13f8-5d69-4a82-af37-a6c853cfe305.png)

## Reproduction

 I pressed create shared link then opened among us, then I get this error

Enter reproductions steps here.

**Comment by miniduikboot** [comment]
Hi there,

Did you install the [Impostor.Http plugin](https://github.com/Impostor/Impostor.Http) and set up a reverse proxy such that your server can be accessed over HTTPS?

If you have Among Us on PC it's easier to debug issues, so if you have that we recommend trying to connect from a PC first. Second, communication over GitHub is a bit slow, so we usually prefer Discord for user support: https://discord.gg/6UybPYB3

**Comment by miniduikboot** [comment]
Hi there, it's been a while, so I'm going to close this issue. If you still have issues, feel free to reopen this ticket
