### ISSUE TITLE
How to let a player send message by using Impostor.API

### ISSUE THREAD

**Issue by commandf1** [Impostor/Impostor#528]
I want to send a message by using Impostor.API
Just like this:
![image](https://github.com/Impostor/Impostor/assets/76681129/f3959eea-4b54-4a6e-8842-8217de415677)
How do I do this?

**Comment by miniduikboot** [comment]
Try using the SendChatAsync (or SendChatToPlayerAsync) function: https://github.com/Impostor/Impostor/blob/7b341bea147b763ef879e13e82c072dcf5ae6e25/src/Impostor.Api/Net/Inner/Objects/IInnerPlayerControl.cs#L78
