### ISSUE TITLE
[New API]Add API to check if other Games exist in the server to IGameDestroyedEvent

### ISSUE THREAD

**Issue by yukieiji** [Impostor/Impostor#529]
# Api Suggestion

## Suggestion

Add API to check if other Games exist in the server to IGameDestroyedEvent(bool IGameDestroyedEvent.EmptyServer?)

## Use case

Add the function to restart the server when there is no one on the server.

**Comment by js6pak** [comment]
You can already achieve this by injecting `IGameManager` into your class (in the constructor, just like you would do with the logger) and then checking `_gameManager.Games.Count()`
![image](https://github.com/Impostor/Impostor/assets/35262707/c0fba904-b24d-46c1-8411-3e6cc7290172)

**Comment by yukieiji** [comment]
Thank you, I have also confirmed that it works, so close it.
