### ISSUE TITLE
Creating a room will result in cancellation of login. Is there any way to solve it?

### ISSUE THREAD

**Issue by luoyinhuan** [Impostor/Impostor#537]

**Comment by miniduikboot** [comment]
Hi there, I think you have not set up Impostor correctly using the Impostor.Http plugin. Please check out the documentation: https://github.com/Impostor/Impostor/blob/master/docs/Running-the-server.md

**Comment by miniduikboot** [comment]
Since this issue has not been responded to for a while, I'm going to close this issue now. If you need more help, please reply and reopen this issue.
