### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by TechDevOfficial** [Impostor/Impostor#539]
# Bug Report

## Base Information
- Operating System
- Impostor Version
- Among Us Version

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Enter Symptoms on this line.

## Reproduction

Enter reproductions steps here.

I created a issue few hours ago, but you telled me it's not possibile play withh old versions..... Today i user impostor for ten minute i restarted among us and it donato worked... I use impostor in 12.9 and it works like in Among Us Community. So, it is fixable, pls help me.

**Comment by TechDevOfficial** [comment]
https://youtu.be/6_1hx9DdM88

**Comment by TechDevOfficial** [comment]
![image](https://github.com/Impostor/Impostor/assets/89547375/0dc18491-fafa-4511-b835-7c817c9bf06a)

**Comment by TechDevOfficial** [comment]
or someone know other servers for 12.9?

**Comment by TechDevOfficial** [comment]
https://github.com/KyuDeathsBR/DragonBallZ_Roles/releases/tag/0.0.3 i have this mod installed and with this impostor dont work

**Comment by miniduikboot** [comment]
Hi there,

As I said in my previous message: we don't support versions of the game that are *that* old. That does not mean it doesn't work, it just means that if it doesn't, you get to keep both the pieces and you can try to figure out yourself why it doesn't.

Please stop opening additional issues or expecting us to quickly answer your messages: if you need user support, our Discord is a better fit
