### ISSUE TITLE
Issuses

### ISSUE THREAD

**Issue by fiftys7ven** [Impostor/Impostor#540]
# Bug Report

## Base Information
- Operating System: Windows 11
- Impostor Version: 1.8.4
- Among Us Version: 2023
### 1
impostor.http Plugin Shows I Dont Have dotnet 7.0 But I Have.
### 2
I Have Among Us On Bluestacks And When I Trying To Login To Server, It Log Me Off And I Need To Restart Game. Also I Use ngrok If You Wondered.

**Comment by miniduikboot** [comment]
Hi there,

Sorry in the delay in getting back to you, this issue fell through the cracks.

1. Have you also installed the ASP.Net bundle? You'll need that for Impostor.Http
2. You get automatically logged out when Among Us fails to connect to the http server. Fix issue 1 and this should hopefully fix itself
