### ISSUE TITLE
Creating a room will result in cancellation of login.  It is in Docker Version.

### ISSUE THREAD

**Issue by pilldesomebody** [Impostor/Impostor#541]
# Bug Report

## Base Information
- Operating System Docker20
- Impostor Version  1.8.4
- Among Us Version latest

Enter reproductions steps here.

**Comment by miniduikboot** [comment]
Hi there,

You get automatically logged out when Among Us fails to connect to the http server.
1. Have you installed the Impostor.Http plugin?
2. Have you correctly portforwarded the http service?
If you fix the http server, you should be able to stay logged in and hopefully also connect to your impostor server.

**Comment by pilldesomebody** [comment]
thank for the respond
but i downloaded the http plugin but dont know where it should be placed
i saw some dll in the docker folder so i tried to put it in that folder but it didnt worked
and i found all of the docker file but didnt find a folder called plugin
Should I create a new folder called plugin directly?

**Comment by miniduikboot** [comment]
If you're using the latest Docker container it should already have Impostor.Http installed, and it should list that the plugin is installed when starting it. Can you confirm it is loaded?

**Comment by pilldesomebody** [comment]
![屏幕截图 2023-09-11 211536](https://github.com/Impostor/Impostor/assets/41865335/804132a0-baa3-4b63-afd8-e2978ac0f375)
i'm reloaded the latest docker container.Firewall sets as all tcp/udp open(i will close it when i close the docker.just for test)
This is what the terminal and the game shows.
Is this correct?

**Comment by miniduikboot** [comment]
I don't speak Chinese so I don't know the message that's on your screen, but I think I can read enough to help you. It looks like you connected directly using the UDP server. Can you generate a new region file using https://impostor.github.io/Impostor/ and check if that works better?

A few releases ago, Among Us started requiring HTTP Matchmaking otherwise you get logged out. Old region files contain a region of type "StaticRegionInfo" or "DnsRegionInfo", new files contain one called "StaticHttpRegionInfo". Make sure your region file only contains the latter type

**Comment by pilldesomebody** [comment]
It works worse.
I cant create a new room and get logged out
I generated a new region and replaced the old region![屏幕截图 2023-09-12 111543](https://github.com/Impostor/Impostor/assets/41865335/809288b2-c232-49cc-8844-5ec773afe0c4)
This is what the terminal,the game and the region shows.
(i dont have a json format tool so a make a format in a different file but it is the same contant)

**Comment by miniduikboot** [comment]
Even though you may not believe me, you're almost there. It looks that your client doesn't connect to the HTTP server yet. Can you check if you have portforwarded port 22023 TCP next to the UDP port? In particular, check if you have added the port to your Docker configuration: `-p 22023:22023/tcp`

Note that by default our docs recommend you to bind Impostor.Http to localhost and use a reverse proxy for HTTPS support, but if you don't need that you can also bind it to all ports.

To verify that you've done it correctly, run the following command: `netstat -tlpen`. It should contain a line as follows:
> **tcp**        0      0 **0.0.0.0:22023**           0.0.0.0:*               **LISTEN**      1000       65599      9556/./Impostor.Server
I've made a few fields bold, they should match exactly

**Comment by Huier-Huang** [comment]
你开放的可能是运营商提供的网络防火墙，你可以尝试关闭系统防火墙
What you have open may be the network firewall provided by your carrier, you can try turning off the system firewall

**Comment by miniduikboot** [comment]
Your configuration seems correct. It could still be that you have an extra firewall you'd need to add an exception to, or need to port forward the required ports

**Comment by pilldesomebody** [comment]
thanks!!!
Successfully created the room and no logged out again!
it's the firewall issus.
i forgot to open the required ports :P
