### ISSUE TITLE
host with TOH_ForE mod is disconnected from server when other joins

### ISSUE THREAD

**Issue by zrotl** [Impostor/Impostor#545]
# Bug Report

## Base Information
- Operating System: Host/Guest:Windows11, Server:Ubuntu Server(arm64)
- Impostor Version: 1.8.4 / 1.8.4 in docker
- Among Us Version: Latest in steam
- Mod: TownOfHost_ForE vAMONGUS-α(https://github.com/AsumuAkaguma/TownOfHost_ForE)

## I confirm:
- When I try in asia server, this bug doesn't occur.
- I try both directly installed Impostor server and dockered one.

## Symptoms 
When other joins the room I created, I'm always disconnected from the room.
Game says: Reliable packet 16 (size=4711) was not ack'd after 7511ms (11 resends), ping:11)
Server Logs: 
[14:40:27 INF] XXXXXX - Player (2) is joining.
[14:40:35 INF] XXXXXX - Player (1) has left.
[14:40:35 INF] XXXXXX - Assigned Player (2) as new host.
[14:40:35 INF] Client 1 disconnecting, reason: The remote sent a disconnect request

I used tcpdump to capture packets in host pc and server. I noticed that asia server return some fragmented udp packets to host, but Impostor server does never return it. So after about 7 seconds, host sends a disconnect request.
When I try with TownOfHost mod, server doesn't send fragmented udp packets, only sends small ones.

## Reproduction
1. install the mod
2. make the room
3. join other person
4. after about 7 seconds, host is disconnected from the room

**Comment by miniduikboot** [comment]
> Reliable packet 16 (size=4711)

That's a very large packet, and I'm surprised the Asia server seems to handle it correctly. Do you know which packet is so gigantic?

My usual recommendation is to change the mod such that all packets are smaller than 1000 bytes, and avoid packets larger than 1400 bytes.
