### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by pilldesomebody** [Impostor/Impostor#556]
# Bug Report

## Base Information
- Operating System:Dokcer
- Impostor Version:1.9.0(Docker)
- Among Us Version:2023.11.28s

work well in 1.8.4(docker) with old Among Us Version(2023.6.27s)
but dont work at 1.9.0(docker) with latest Among Us(2023.11.28s) or old Among Us Version(2023.6.27s)
player.log shows "Curl error 7: Failed to connect to "IP address" port 22023 after 2251 ms: Connection refused"
regionInfo.json have no changing
firewall have no changing
only run a new docker image when the 1.8.4 is off

**Comment by miniduikboot** [comment]
Hi there, this is weird to hear, we haven't made significant changes to the HTTP interface between 1.8.4 and the most recent nightly version. (Although we are planning to merge 553 soon, but that should be a seamless transition)

Can you share your Impostor log? Please redact the last 2 octets of your IP address for your privacy (so 127.0.0.1 becomes 127.0.x.x)

**Comment by pilldesomebody** [comment]
I cant find the log
Which file do you need?
![屏幕截图 2023-12-17 201209](https://github.com/Impostor/Impostor/assets/41865335/7f333252-dc82-40f4-a8f3-ec2a8f345853)

**Comment by miniduikboot** [comment]
I want to see what is printed in the console when you start Impostor

**Comment by pilldesomebody** [comment]
![屏幕截图 2023-12-17 201707](https://github.com/Impostor/Impostor/assets/41865335/d880b6cc-699c-45f7-9aee-7feda1994fa9)

**Comment by pilldesomebody** [comment]
OK it run
it is the reverse proxy problem 
remove the 127.0.0.1: and worked
thanks

**Comment by miniduikboot** [comment]
Okay, have fun!
