### ISSUE TITLE
can add ipdb to give client diffrent public ip?

### ISSUE THREAD

**Issue by RhythmNz** [Impostor/Impostor#570]
# Feature Request
can add ipdb to give client diffrent public ip?

## Feature Information:
use custom ipdatabse to let server know client isp and area
and give them diffrent public ip to connect udp

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by Huier-Huang** [comment]
一般人不会开多台服务器，感觉不会有多少人使用
(The average player doesn't open multiple servers, it doesn't feel like it will be used by many people)

**Comment by RhythmNz** [comment]
> 一般人不会开多台服务器，感觉不会有多少人使用 (The average player doesn't open multiple servers, it doesn't feel like it will be used by many people)

not start multiple servers,just set port forward.

**Comment by miniduikboot** [comment]
I think this is out of scope for Impostor: we're currently not supporting any functionality to cluster servers together and as it adds a lot of complexity for a feature nobody used or wanted to support I don't want to add it back. But feel free to create your own solution, the HTTP matchmaking API is pretty simple although it's pretty ugly.
