### ISSUE TITLE
docker.yml not work with version 2024.3.5

### ISSUE THREAD

**Issue by GianniIta87** [Impostor/Impostor#572]
Hi, I saw that you corrected the files to support the new version of among, , but I using Docker on a Synology and  I can't modify them manually. 
How can I update it?
Thank you

**Comment by miniduikboot** [comment]
Sorry for the delay in getting back to you, we just merged a pull request adding support for 2024.3.5 so you should be able to run it if you update to the latest Impostor nightly.

In future you can also set environment variables to change config options
