### ISSUE TITLE
ERROR "Among us directory was not found, is it installed? Try running it  once"

### ISSUE THREAD

**Issue by Fluffy728** [Impostor/Impostor#575]
### Discussed in https://github.com/Impostor/Impostor/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **paulopimentel** January 12, 2021</sup>
When I click save to start the client, the following message "Among us directory was not found, is it installed? Try running it  once" how to solve?</div>

**Comment by miniduikboot** [comment]
I believe this refers to the old Patcher software, which is no longer supported to set up custom servers. Please use the website instead: https://impostor.github.io/Impostor/

**Comment by Fluffy728** [comment]
> ** miniduikboot said from issue 575 https://github.com/Impostor/Impostor/issues/575  **

 I believe this refers to the old Patcher software, which is no longer supported to set up custom servers. Please use the website instead: https://impostor.github.io/Impostor/
