### ISSUE TITLE
Jail breaking for iOS? Why?

### ISSUE THREAD

**Issue by Fluffy728** [Impostor/Impostor#578]
### Discussed in https://github.com/Impostor/Impostor/discussions/577

<div type='discussions-op-text'>

<sup>Originally posted by **Fluffy728** April  7, 2024</sup>
Why do we need to jailbreak iOS to access imposter? But with cloud hosting you don’t have to, and that is probably illegal .</div>

**Comment by miniduikboot** [comment]
Please don't convert discussions into issues immediately.

**Comment by Fluffy728** [comment]
Hi! Thanks for telling me

**Comment by Fluffy728** [comment]
Thanks for telling me
