### ISSUE TITLE
Imposter Fourms issue

### ISSUE THREAD

**Issue by Fluffy728** [Impostor/Impostor#582]
- [ ] GitHub is saying I am the most useful person when I solved my own issue? Why, I think it is becuase I am getting more acti e than anyone else?

- [ ] is imposter still having updates?

**Comment by Fluffy728** [comment]
GitHub is saying I am the most useful person when I solved my own issue? Why, I think it is becuase I am getting more acti e than anyone else?

is imposter still having updates?

**Comment by miniduikboot** [comment]
> GitHub is saying I am the most useful person when I solved my own issue? Why, I think it is becuase I am getting more acti e than anyone else?

We don't actively use the discussions tab, getting support through the discord is more effective. So solving a single discussion probably makes you the most active contributor of the month.

>  is imposter still having updates?

The last commit was 3 days ago and the last release a whole 4 days ago. If that does not match your standards for maintainability, I recommend you find another Among Us game server that is more actively maintained.

**Comment by miniduikboot** [comment]
Also please, stop spamming the Impostor github with issues. I woke up this morning with 20 unread emails, all from you
