### ISSUE TITLE
Dashboard Design

### ISSUE THREAD

**Issue by Fluffy728** [Impostor/Impostor#583]
# Feature Request

## I confirm:
- [x] that I have searched for an existing feature request matching the description.
- [ ] 

### Expected
- [x] Suggestion sent
- [ ] Users discussed on it
- [ ] Team marked as “Planned”
- [ ] Team making it
- [ ] Done!
- [ ] 

### Pros
- impress new users
- Buetfiofil in any way
- Ease of access
- No more plain text
- 

### Cons
- it is not all about Looking nice
- It may be a bit unneccary
- More work for the imposter team, that is bad in some ways
- 
### The option to opt out
Users can opt out!

**Comment by miniduikboot** [comment]
Impostor has a plugin API which allows third-party plugins to implement dashboards like this, and this in fact has already been done by someone, although their plugin is very outdated now.

The Impostor team implementing their own dashboard is a giant increase of scope that we currently don't want to undertake. If you want to create a dashboard, you can use the plugin API to create it.

**Comment by Fluffy728** [comment]
Oh… thanks

**Comment by Fluffy728** [comment]
I can hide messages

**Comment by Fluffy728** [comment]
Lol

**Comment by Fluffy728** [comment]
I SAID USERS CAN OPT OUT
