### ISSUE TITLE
Server stopped working.

### ISSUE THREAD

**Issue by danbudworthmead** [Impostor/Impostor#592]
# Bug Report

## Base Information
- Operating System
- Impostor Version
- Among Us Version

## I confirm:
- [ ] that I have searched for an existing bug report for this issue.

## Symptoms 

Impostor server stopped working. No one could connect.

## Reproduction

No idea. Provided logs tho.

[logs.txt](https://github.com/Impostor/Impostor/files/15053067/logs.txt)

**Comment by NikoCat233** [comment]
seems like your http matchmaker is down.
How did u setup your http matchmaker?

**Comment by danbudworthmead** [comment]
it's using the impostor.http plugin.

**Comment by NikoCat233** [comment]
latest impostor already got http plugin implement ed i think.  u shouldnt add a plugin if u are using layest version

**Comment by miniduikboot** [comment]
@danbudworthmead, is this still a problem?

Note that you shouldn't use the Impostor.Http plugin anymore and instead use the inbuilt HTTP matchmaker. These two will conflict if you run them at the same time
