### ISSUE TITLE
Support for 2024.3.1?

### ISSUE THREAD

**Issue by tkbstudios** [Impostor/Impostor#606]
# Feature Request

## Feature Information:
Support Among Us version 2024.3.1 (latest as of time I'm writing this)

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by Log4Jake** [comment]
Yes please support the latest version. 🙏

**Comment by ugackMiner53** [comment]
Support for `2024.6.18` is being worked on in #600. If you want to help test it, you can download the latest CI from [the actions](https://github.com/Impostor/Impostor/actions).

([Link to latest action for 2024.6.18 as of 7/22/2024](https://github.com/Impostor/Impostor/actions/runs/10012387120))

**Comment by tkbstudios** [comment]
Thanks! It works fine :)
