### ISSUE TITLE
Docker Version Update Issues

### ISSUE THREAD

**Issue by pilldesomebody** [Impostor/Impostor#636]
I'm using the docker version
i found that the doc said the version is v1.9.3
but when i updated it show v1.9.1-docker.717
Is there no update yet?
![屏幕截图 2024-08-07 223937](https://github.com/user-attachments/assets/696f4ba7-b18f-4458-82b9-fe69e4c15f52)

**Comment by NikoCat233** [comment]
the 6.18 release is still under testing. Docker build is not uet generated.
you can get the latest binary file here or you can just build your own one
https://github.com/Impostor/Impostor/actions/runs/10151846590
