### ISSUE TITLE
Linux client

### ISSUE THREAD

**Issue by TheEpicProgrammer** [Impostor/Impostor#69]
# Feature Request

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

I would really appreciate a linux client for this. I know that .NET doesen't work on linux but please make it so it is easily runnable using mono or wine.

**Comment by masterworgen** [comment]
Maybe, used .net core?

**Comment by tuxinal** [comment]
it is runable using mono

**Comment by js6pak** [comment]
In the dev branch both patchers are runnable on linux, CLI version using .net core and GUI (WinForms) using mono, also both support steam/proton.

**Comment by AeonLucid** [comment]
Use `Impostor.Patcher.Cli`.
