### ISSUE TITLE
Any way to add mods?

### ISSUE THREAD

**Issue by E-N-Y** [Impostor/Impostor#72]
Is there a way to add mods to the server?
I want to add the CodeIsNotAmongUs mod by js6pak, anyone knows how to do that ?
(I know my questing is probably dumb, so sorry in advance)

**Comment by fullonrager** [comment]
No, that mod is private and there is no way to make the client-side mod files work with the server from scratch.

**Comment by AeonLucid** [comment]
That's a client-side mod. Server-side plugins for Impostor are coming soon.
