### ISSUE TITLE
Bug with scan, lights repair

### ISSUE THREAD

**Issue by kptLucek** [Impostor/Impostor#77]
# Bug Report

## Base Information
- Operating System - Win10
- Imposter Version - 1.2.0
- Among Us Version - v2020.9.22s

## I confirm:
- [x ] that I have searched for an existing bug report for this issue.

## Symptoms 

Try to submit scan as crewmate, you're getting banned for hacking :)

## Reproduction

Go submit scan as crewmate, sometimes work perfectly, but for many others it gonna result as ban.

## Log
`Oct 25 15:39:37 94-130-125-94 IMPOSTOR[4620]: [15:39:37 INF] Client 31 disconnecting, reason: Client sent RepairSystem as crewmate.`

-- Edit
the same is happening while trying to "fix" any of sabotage or similar, open doors (Polus) and so on.

Conclusion, propably packets are miss-*(ing|mapped) or something?

**Comment by AeonLucid** [comment]
Thanks, I know what is wrong and will fix it in a bit.

**Comment by AeonLucid** [comment]
I can't seem to reproduce the error, are you in the discord server? Please ping me

**Comment by AeonLucid** [comment]
Nevermind I did
