### ISSUE TITLE
Add an event for the initial connection to the matchmaker.

### ISSUE THREAD

**Issue by antisharp** [Impostor/Impostor#79]
# Api Suggestion

## Suggestion
We would like to be able to implement bans based on IP Addresses. For that, we shall need an event that is fired when a client connects to the server, so we can check if he is banned, and terminate his connection before he can request any data.

## Use case
Ban systems for cheaters / country heatmapping / DoS detection.

## Expected result
An event which shall be fired when a client connects to the server, before any kind of authentication or requests. If the connection shall be terminated inside the event handler, the authentication shall not continue.

**Comment by AeonLucid** [comment]
Are you asking for a cancelable event that is triggered before this line?

https://github.com/Impostor/Impostor/blob/9e55a9738beed4dd18c35842541eef2abf0f620f/src/Impostor.Server/Net/Matchmaker.cs#L59

**Comment by danbudworthmead** [comment]
Couldn't this be achieved by sending a packet to kick the client if they don't pass the auth check?
