### ISSUE TITLE
Connecting via Mobile

### ISSUE THREAD

**Issue by eyesoffaith** [Impostor/Impostor#8]
Firstly, amazing job! Me and some friends haven't been able to play via the official means and this has completely saved our game nights. Kudos!

I saw in the README though that BOTH desktop and mobile are supported by the private server. If there are any instructions on how a mobile user can join a dedicated server then I would love to give them a shot! 😁

**Comment by cristimalita** [comment]
You can simply generate a regionInfo.dat file using the Impostor Client with your server's ip and copy it to your phone. However, on iOS it only works if your phone is jailbroken.

**Comment by eyesoffaith** [comment]
Ah! Okay. I will admit I don't know anything on how to generate the regionInfo.dat file or where to place it on the mobile device. I only ask because I'm not seeing any info when I open the Imposter client program. If you have any steps to reproduce this I would be very interested. Also, I could add those steps to the README if other people are in the same boat.

**Comment by cristimalita** [comment]
When you hit save on the Impostor client it changes the game's regionInfo.dat file which contains the the server name and ip. This file is located in c:\Users\YourUser\AppData\LocalLow\Innersloth\Among Us\regionInfo.dat. All you have to do is copy that file to your phone and overwrite the existing one, for me it's under internal storage -> Android/data/com.innersloth.spacemafia/files/regionInfo.dat

**Comment by eyesoffaith** [comment]
Thank you so much for this information. I have been able to connect friends on mobile to my PC server!

I have taken to trying to write an apk that could automate the process (i.e. something akin to the PC client but for Android). I have managed to get as far as being able to generate what will go into the regionInfo.dat file however I am running into permission issues with overwriting the existing file that Among Us uses. I understand this might not be your expertise but can you let me know if this interests you or would be interested in including it in the repo if this problem can be solved?

**Comment by AeonLucid** [comment]
What android version @eyesoffaith? I know Android 11 has scoped storage stuff that will mess with this.
You might need to ask for sdcard permission or something.

I don't know about including an android application in this repository, I will have to think about that.

**Comment by eyesoffaith** [comment]
As far as generating the data for the file? I haven't seen anything that
suggests it couldn't run as far back as Android 4.4. As far as creating an
apk that has access to the regionInfo.dat so it can write that data though,
it really depends on the Android version like you said.

Unfortunately I haven't found a solution that doesn't require root for any
version. If this can be done via the SD card then that would be possible to
request permission, but if I'm not mistaken the regionInfo.dat is stored in
internal storage, yeah?

**Comment by eyesoffaith** [comment]
It should also be possible if the apk I am building can be installed as a
system app but I'm very new to .apk development lol. There is a process of
signing an app with a firmware key so that when a user installs the app it
has those system privileges (a legit process that file browsers and system
apps use to handle file i/o operations) but I have no idea how to go about
it.

**Comment by Andruida** [comment]
I created a modded apk for the game, and it works just fine. I could create a recompiler script, that puts your server's IP in the APK. Unfortunately, this has the drawback of needing to install an unofficial app, but this is the least finnicky way for the end user.

**Comment by eyesoffaith** [comment]
Oh nice, that's awesome. If there were a way to mod the apk so that a
person has the option to enter an ip address that would be the dream. How
do you think future updates would work? Would a new modded apk need to be
built? My curiosity is peaked 😁

**Comment by Andruida** [comment]
Unfortunately I was only able to replace the hardcoded IP adresses, but I'm looking into how the adresses could be dynamically changed.
Currently you have to build a new APK for every private server you would like to play on.

**Comment by AeonLucid** [comment]
@Andruida I have thought about that idea as well but I don't like the idea of sharing around modified APKs.

**Comment by Andruida** [comment]
I can understand that. But I think most of the risks can be mitigated, if the users generate their own APKs with a script. In our group this was the quickest solution, because we didn't want to manually generate/copy regionInfo.dat files, and I think others may find this a more comfortable approach. But also, I can fully understand if you don't want to touch the APK.

**Comment by eyesoffaith** [comment]
@Andruida if you have a script that lets a user generate the APK themselves, I would love to have a look at that. That sounds like a solid solution all things considered and if you open to sharing.

**Comment by Andruida** [comment]
Currently I can create them manually, but it could be automated. I will get
back here in a few days with a script, to do that automatically.

eyesoffaith <notifications@github.com> ezt írta (időpont: 2020. szept. 29.,
K 0:24):

**Comment by evGiac** [comment]
Any update?

**Comment by Andruida** [comment]
I ran into an issue, but I'm working on it as I have time to do it. I will post a more detailed update during the week.

**Comment by bakublade2002** [comment]
any update?

**Comment by Mm2PL** [comment]
> any update?

> Any update?

Android works rootless (from my experience, ymmv), IOS requires jail-breaking and a tweak.

**Comment by eyesoffaith** [comment]
Nothing so far as I know

**Comment by Trolldemorted** [comment]
Since the android app has a LAN mode, can't one send a broadcast (which advertizes a public ipv4 address) from an arbitrary device to the smartphone, and the user may connect to the advertized game through the vanilla UI?

**Comment by AeonLucid** [comment]
@Trolldemorted Which "arbitrary device" do you suggest to do the broadcast? Perhaps the an android app can be created that does the broadcast to itself.

**Comment by Trolldemorted** [comment]
You are totally right, an app of the phone itself should work, since they are literally doing that for lobby discovery/advertisements in LAN mode. However that depends on the correctness of the assumption that the lobby discovery protocol is a simple layer2 broadcast, did you check that yet? I didn't find the time to have a look at it with wireshark yet, unfortunately.

**Comment by AeonLucid** [comment]
@Trolldemorted Someone in the Impostor server did a hacky broadcast. The problem with local games is that it joins them with the hardcoded room code `32`, so it won't work unless the android app also acts as a small server that redirects the client to the correct room using the `Redirect` packet.

[Broadcast code image from p0358](https://user-images.githubusercontent.com/4643257/95979033-4df8f800-0e1b-11eb-9f63-74c8321575fc.png)

**Comment by NaokiStark** [comment]
I made an app for android 🙂

**Comment by eyesoffaith** [comment]
Oh? That's exciting 😀. How did you go about setting the regionInfo.dat
file?

**Comment by pepijnmm** [comment]
@eyesoffaith it is opensource so you can check it here: https://github.com/NaokiStark/Crewmate-switcher/blob/58e4efab9037564c1dc40b0af0fbf03d3cd5689b/app/src/main/java/pw/fabi/crewmate/MainActivity.java#L82
