### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by ProfessorVarox** [Impostor/Impostor#80]
# Bug Report

## Base Information
- operating System: Debian 9
- Imposter Version: 1.1.0

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

When I try to run `dotnet build Impostor.Server` on Linux (Debian 9) I get the following error
```
Microsoft (R) Build Engine version 16.8.0-preview-20475-05+aed5e7ed0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/opt/amongus-server/Impostor.Server(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

Build FAILED.

/opt/amongus-server/Impostor.Server(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
```

## `dotnet --info` output:

```
root@project-ki:/opt/amongus-server# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /opt/amongus-server/sdk/5.0.100-rc.2.20479.15/

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [/opt/amongus-server/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/opt/amongus-server/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/opt/amongus-server/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Reproduction

1. Download Imposter v1.1.0
2. Download .NET v5.0.0-rc.2.20475.5
3. Run `dotnet build Impostor.Server`

_I really apologize if I made something wrong but I worked very little with .NET before_

**Comment by Mm2PL** [comment]
try `dotnet build src/Impostor.Server`

**Comment by ProfessorVarox** [comment]
same error

**Comment by tuxinal** [comment]
could it be because you have root privileges?

**Comment by ProfessorVarox** [comment]
yes, I run it with root. I'll try with another user

**Comment by Mm2PL** [comment]
Did you clone the repo/download source code  into `/opt/amongus-server` or is this the binaries you downloaded?
PS: support in discord would probably be easier, since we're just exchanging single sentences

**Comment by ProfessorVarox** [comment]
I deleted `/opt/amongus-server` and reinstalled Impostor v1.1.0 in `/usr/src`

Where can I find the invite link for the Discord Server?

**Comment by Mm2PL** [comment]
[here, https://discord.gg/Mk3w6Tb](https://discord.gg/Mk3w6Tb)

**Comment by AeonLucid** [comment]
Seems like you cloned the repository incorrectly.
