### ISSUE TITLE
If a player gets banned for hacking, they can rejoin that lobby after the game is over

### ISSUE THREAD

**Issue by 8bit-coder** [Impostor/Impostor#84]
# Bug Report

## Base Information
- Operating System: Windows 10 Pro 1909 x64
- Imposter Version: 1.2.0
- Among Us Version: 9.22

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 
You can rejoin the lobby after you get banned from it for hacking

## Reproduction
1. Get banned from that lobby for hacking
2. Wait for that lobby's game to finish
3. Rejoin that lobby instead of still being banned

**Comment by 8bit-coder** [comment]
It also turns out that if you get banned for hacking(like noclipping in the lobby), you can immediately rejoin without any issues

**Comment by Saghetti0** [comment]
FYI the list of rooms you're banned from is stored client-side, so this might not be something that can be fixed using Impostor. It's up to the client to prevent itself from joining rooms it's banned from, and that can be patched out by a cheater afaik.

**Comment by AeonLucid** [comment]
I will make it ban the IP from the room by default, which will also be configurable.

**Comment by AeonLucid** [comment]
Fixed in 1.2.1.
