### ISSUE TITLE
Improve disconnect reliability

### ISSUE THREAD

**Issue by AeonLucid** [Impostor/Impostor#89]
Currently we have this in the `DisconnectAsync`.

https://github.com/Impostor/Impostor/blob/b670800c540ff43699a18f90c043ba89133e204e/src/Impostor.Server/Net/ClientBase.cs#L53

It would be better if the error message and the disconnect packet (caused by `Connection.DisconnectAsync`) were sent as one packet. By doing that, there will be no issue with showing the correct error message in the client.

**Comment by js6pak** [comment]
Implemented in a56eed2680d807987bd993a54bbd38e76a228ac3
