### ISSUE TITLE
Add an event for player death.

### ISSUE THREAD

**Issue by benjaminpants** [Impostor/Impostor#91]
# Api Suggestion

## Suggestion
An event that gets triggered/called whenever a player is killed for any reason. With a DeathReason and the person who got killed, plus the person who caused the kill(an impostor, null if exiled)

## Use case
Anti-cheat, custom gamemodes where you might want something special/extra to happen when someone is killed, auto-completing the ghost's tasks once killed(simulating the "GhostsDoTask" setting which as far as I can tell doesn't work)

## Expected result
A function that gets called whenever a player is killed, and being able to get the player who got killed and the person responsible(if applicable) along with a death reason.

**Comment by Saghetti0** [comment]
#93 adds IPlayerMurderEvent, but exiles don't work.

**Comment by danbudworthmead** [comment]
> #93 adds IPlayerMurderEvent, but exiles don't work.

These are my logs from a round of voting where someone got excited.
You can see all of the RPC calls.

`
[RPC] SendChatNote
[11:32:33 VRB] [2] Server got 6.
[11:32:33 VRB] Received GameData for target 1.
[RPC] CastVote
[11:32:34 VRB] [1] Server got 5.
[RPC] SendChatNote
[11:32:41 VRB] [4] Server got 6.
[11:32:41 VRB] Received GameData for target 1.
[RPC] CastVote
[11:32:41 VRB] [1] Server got 5.
[RPC] SendChatNote
[11:32:46 VRB] [3] Server got 6.
[11:32:46 VRB] Received GameData for target 1.
[RPC] CastVote
[11:32:46 VRB] [1] Server got 5.
[RPC] VotingComplete
[RPC] SendChatNote
[11:32:51 VRB] [1] Server got 5.
[RPC] Close
`

**Comment by Saghetti0** [comment]
The exiled player is given on a VotingComplete RPC. I'll make PlayerExiledEvent trigger on that in a future PR.

**Comment by danbudworthmead** [comment]
Is it worth closing this issue and opening a new one for exiled?

**Comment by reecebenson** [comment]
Does #112 close this?

**Comment by AlexejheroYTB** [comment]
Yep, it should fix this issue according to the author, but they didn't use the `closes` keyword properly. (see [this article](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords))
