### ISSUE TITLE
Add event cancelling to chat messages

### ISSUE THREAD

**Issue by wickedlizerd** [Impostor/Impostor#92]
# Api Suggestion

## Suggestion
As the ability to cancel events with the API

## Use case
For my particular use case, I want to be able to cancel message events starting with `/` 

## Expected result
Player Sends Message Starting With "/",
The Event Is Cancelled,
No player receives the message
(Message can still be sent with e.Game.SendToAsync())

**Comment by Mm2PL** [comment]
Due to how events work, this should be doable on every type of event.
###### I think

  1. Receive packet from client
  2. Decode packet
  3. Fire off appropriate events
  4. Forward packet to other clients

The fourth step can be ignored if the event was canceled, and other players won't see the thing happen.

**Comment by wickedlizerd** [comment]
Could this lead to possible desync?

**Comment by Mm2PL** [comment]
> Could this lead to possible desync?

🤔 Probably on some events.

**Comment by AeonLucid** [comment]
@Mm2PL this will lead to desync, it will only work for specific type of events like this. For other cancelling other events (such as venting) we would need to send the inverse of that event (going out of the vent). Because client's do not verify their action with the server before doing it.

**Comment by danbudworthmead** [comment]
I've been messing around with blocking packets.
Here's an example of blocking chat packets beginning with "/"

https://github.com/danbudworthmead/Impostor/commit/e032c0d4abd4f2d2b5a78e4929b01d3fa074ede5

**Comment by AeonLucid** [comment]
@danbudworthmead I won't be merging that if you PR it. Reason for that is that there can be another GameData message after the GameData event you are canceling. You are returning, effectively canceling everything in that stream.

**Comment by danbudworthmead** [comment]
> @danbudworthmead I won't be merging that if you PR it. Reason for that is that there can be another GameData message after the GameData event you are canceling. You are returning, effectively canceling everything in that stream.

Aha dw not planning to PR. Just through it might be useful in this thread if someone's looking to do something similar.
