### ISSUE TITLE
Tasks are partially working

### ISSUE THREAD

**Issue by kptLucek** [Impostor/Impostor#98]
# Bug Report

## Base Information
- Operating System: win10
- Imposter Version: 56th build? - https://ci.appveyor.com/project/Impostor/Impostor/build/56/artifacts
- Among Us Version: 2020.09.22

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Disconnecting player after upload try on Polus map

### 1.
- Download in weapons
- Upload in comms*
### 2.
- Go below O2, to room where are two wheels (water?), and use them *

*there's a something like 50/50 chance that you gonna get disconnected in any of those*

### Logs
```
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]: [19:49:22 ERR] Invoking data received failed
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Hazel.MessageReader.ReadByte()
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Server.Net.Inner.Objects.InnerMeetingHud.PlayerVoteArea.Deserialize(IMessageReader reader)
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Server.Net.Inner.Objects.InnerMeetingHud.Deserialize(IClientPlayer sender, IClientPlayer target, IMessageReader reader, Boolean initialState)
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Server.Net.State.Game.HandleGameDataAsync(IMessageReader parent, ClientPlayer sender, Boolean toPlayer)
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Server.Net.Client.HandleMessageAsync(IMessageReader reader, MessageType messageType)
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Server.Net.Hazel.HazelConnection.ConnectionOnDataReceived(DataReceivedEventArgs e)
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]:    at Impostor.Hazel.Connection.InvokeDataReceived(IMessageReader msg, MessageType messageType)
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]: [19:49:22 INF] BSEASX - Player XXX (100) has left.
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]: [19:49:22 INF] BSEASX - Assigned YYY(102) as new host.
Oct 28 19:49:22 94-130-125-94 IMPOSTOR_STABLE[19418]: [19:49:22 INF] Client 100 disconnecting, reason: Invoking data received failed.
```
From client perspective:
![image](https://user-images.githubusercontent.com/6822027/97485072-eb931200-1959-11eb-90df-7399905505e6.png)

**Comment by AeonLucid** [comment]
_For documentation purposes since we already spoke about this on discord._

Waiting on more information on how to reproduce this error.  
You can get a packet recording by adding this to your `config.json` file.
```json
"Debug": {
    "GameRecorderEnabled": true,
    "GameRecorderPath": "/some/path"
}
```

When you are done playing on the server, shut it down and copy the `session_` file from the GameRecorderPath directory.

**Comment by AeonLucid** [comment]
Any update? @kptLucek
